from typing import *  # noqa: F403
from typing_extensions import *  # type: ignore # noqa: F403
from paddle._typing import *  # noqa: F403
from paddle.static import Program

class MeasureResult:
    def __init__(self) -> None: ...

    @property
    def compile_time(self) -> float: ...
    @property
    def avg_kernel_execute_time(self) -> float: ...
    @property
    def avg_total_execute_time(self) -> float: ...
    err_msg: str
    


class Measurer:
    def __init__(program: Program) -> None: ...
    
    def compile(self) -> None: ...
    def run(self, map: Dict[str, List[int]], repeat: int) -> None: ...
    def result(self) -> MeasureResult: ...
    