apiVersion: batch/v1
kind: Job
metadata:
  name: paddle-cluster-job
spec:
  parallelism: 3
  completions: 3
  template:
    metadata:
      name: paddle-cluster-job
    spec:
      volumes:
      - name: jobpath
        hostPath: 
          path: /home/work/paddle_output              
      containers:
      - name: trainer
        image: registry.baidu.com/public/paddle:mypaddle
        command: ["bin/bash",  "-c", "/root/start.sh"]        
        env:
        - name: JOB_NAME
          value: paddle-cluster-job
        - name: JOB_PATH
          value: /home/jobpath     
        - name: JOB_NAMESPACE
          value: default         
        - name: TRAIN_CONFIG_DIR
          value: recommendation
        - name: CONF_PADDLE_NIC
          value: eth0  
        - name: CONF_PADDLE_PORT
          value: "7164"
        - name: CONF_PADDLE_PORTS_NUM
          value: "2"     
        - name: CONF_PADDLE_PORTS_NUM_SPARSE
          value: "2"  
        - name: CONF_PADDLE_GRADIENT_NUM
          value: "3"                                                               
        volumeMounts:
        - name: jobpath
          mountPath: /home/jobpath       
      restartPolicy: Never
    
