import numpy as np
p = np.load('sdpa.npy')
p1 = np.load('sdpa1.npy')
t = np.load('t_sdpa.npy')
t1 = np.load('t_sdpa1.npy')
#t = t.transpose(1,0,2)
#t = t.reshape(t.shape[0], -1)
diff = np.max(np.abs(p - t))
diff1 = np.max(np.abs(p1 - t1))
diff2 = np.max(np.abs(p1 - p))
diff3 = np.max(np.abs(t1 - t1))
print("linear_diff: ", diff)
print("matmul_diff: ", diff1)
print("paddle_linear_matmul_diff: ", diff2)
print("torch_linear_matmul_diff: ", diff3)
import pdb; pdb.set_trace()
