/* Copyright (c) 2022 PaddlePaddle Authors. All Rights Reserved.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0 Unless required by applicable law or
agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
or implied. See the License for the specific language governing permissions and
limitations under the License. */

#ifdef PADDLE_WITH_XPU
#include <string>
#include <unordered_map>
#include <unordered_set>
#include "paddle/phi/backends/xpu/xpu_op_list.h"

namespace phi {
namespace backends {
namespace xpu {

XPUOpMap& get_kl1_ops() {
  // KL1支持的op，通过op_name, data_type
  static XPUOpMap s_xpu1_kernels{
      {"abs", XPUKernelSet({FLOAT32, INT32, INT64})},
      {"add_layernorm_xpu", XPUKernelSet({FLOAT32})},
      {"accuracy", XPUKernelSet({FLOAT32})},
      {"adam", XPUKernelSet({FLOAT32})},
      {"adamw", XPUKernelSet({FLOAT32})},
      {"affine_channel_grad", XPUKernelSet({FLOAT32})},
      {"affine_channel", XPUKernelSet({FLOAT32})},
      {"arg_max", XPUKernelSet({FLOAT32})},
      {"assign", XPUKernelSet({FLOAT32, FLOAT64, INT32, INT64, BOOL})},
      {"assign_raw", XPUKernelSet({FLOAT32, FLOAT64, INT32, INT64, BOOL})},
      {"assign_value", XPUKernelSet({FLOAT32, INT32, INT64, BOOL})},
      {"batch_norm_grad", XPUKernelSet({FLOAT32})},
      {"batch_norm", XPUKernelSet({FLOAT32})},
      {"bilinear_interp", XPUKernelSet({FLOAT32})},
      {"bilinear_interp_grad", XPUKernelSet({FLOAT32})},
      {"bilinear_interp_v2", XPUKernelSet({FLOAT32})},
      {"bilinear_interp_v2_grad", XPUKernelSet({FLOAT32})},
      {"broadcast", XPUKernelSet({FLOAT32, FLOAT64, INT32, INT64})},
      {"cast", XPUKernelSet({FLOAT32, INT64, BOOL, INT32})},
      {"clip_by_norm", XPUKernelSet({FLOAT32})},
      {"coalesce_tensor", XPUKernelSet({FLOAT32, FLOAT64, INT32})},
      {"concat", XPUKernelSet({FLOAT32, FLOAT16, BOOL, INT8, INT64, INT32})},
      {"concat_grad", XPUKernelSet({FLOAT32})},
      {"conv2d", XPUKernelSet({FLOAT32})},
      {"conv2d_grad", XPUKernelSet({FLOAT32})},
      {"conv2d_xpu", XPUKernelSet({FLOAT32})},
      {"deformable_conv", XPUKernelSet({FLOAT32})},
      {"deformable_conv_grad", XPUKernelSet({FLOAT32})},
      {"depthwise_conv2d", XPUKernelSet({FLOAT32})},
      {"depthwise_conv2d_grad", XPUKernelSet({FLOAT32})},
      {"dropout", XPUKernelSet({FLOAT32})},
      {"dropout_grad", XPUKernelSet({FLOAT32})},
      {"c_allreduce_sum", XPUKernelSet({FLOAT32})},
      {"c_reduce_sum", XPUKernelSet({FLOAT32})},
      {"elementwise_add", XPUKernelSet({FLOAT32, INT64, INT32})},
      {"elementwise_add_grad", XPUKernelSet({FLOAT32})},
      {"elementwise_div_grad", XPUKernelSet({FLOAT32})},
      {"elementwise_div", XPUKernelSet({FLOAT32})},
      {"elementwise_floordiv", XPUKernelSet({FLOAT32, FLOAT16, INT32, INT64})},
      {"elementwise_max_grad", XPUKernelSet({FLOAT32})},
      {"elementwise_max", XPUKernelSet({FLOAT32, FLOAT16, INT32, INT64})},
      {"elementwise_min_grad", XPUKernelSet({FLOAT32})},
      {"elementwise_min", XPUKernelSet({FLOAT32, FLOAT16, INT32, INT64})},
      {"elementwise_mul_grad", XPUKernelSet({FLOAT32})},
      {"elementwise_mul", XPUKernelSet({FLOAT32})},
      {"elementwise_pow", XPUKernelSet({FLOAT32})},
      {"elementwise_sub_grad", XPUKernelSet({FLOAT32})},
      {"elementwise_sub", XPUKernelSet({FLOAT32, FLOAT16, INT32, INT64})},
      {"embedding_with_eltwise_add_xpu", XPUKernelSet({FLOAT32, FLOAT16})},
      {"equal", XPUKernelSet({INT64})},
      {"expand_as_v2", XPUKernelSet({INT32, INT64, BOOL, FLOAT16, FLOAT32})},
      {"expand_v2", XPUKernelSet({INT32, INT64, BOOL, FLOAT16, FLOAT32})},
      {"fc_xpu", XPUKernelSet({FLOAT32})},
      {"fill_any_like", XPUKernelSet({INT64})},
      {"fill_constant", XPUKernelSet({INT32, INT64, FLOAT64, BOOL, FLOAT32})},
      {"gather_grad", XPUKernelSet({FLOAT32})},
      {"gather", XPUKernelSet({FLOAT32})},
      {"gaussian_random", XPUKernelSet({FLOAT32})},
      {"gelu_grad", XPUKernelSet({FLOAT32})},
      {"gelu", XPUKernelSet({FLOAT32})},
      {"generate_sequence_xpu", XPUKernelSet({FLOAT32, INT32, INT64})},
      {"greater_than", XPUKernelSet({INT64, INT32, FLOAT32})},
      {"group_norm_silu_xpu", XPUKernelSet({FLOAT32})},
      {"hard_switch_grad", XPUKernelSet({FLOAT32})},
      {"hard_switch", XPUKernelSet({FLOAT32})},
      {"index_select", XPUKernelSet({FLOAT32, INT32, INT64})},
      {"lamb", XPUKernelSet({FLOAT32})},
      {"layer_norm_grad", XPUKernelSet({FLOAT32})},
      {"layer_norm", XPUKernelSet({FLOAT32})},
      {"leaky_relu_grad", XPUKernelSet({FLOAT32})},
      {"leaky_relu", XPUKernelSet({FLOAT32})},
      {"less_than", XPUKernelSet({INT64, INT32, FLOAT32})},
      {"load", XPUKernelSet({FLOAT64, INT8, INT32, INT64, FLOAT32})},
      {"logicaland", XPUKernelSet({BOOL, INT8, INT16, INT32, INT64, FLOAT32})},
      {"logicalnot", XPUKernelSet({BOOL, INT8, INT16, INT32, INT64, FLOAT32})},
      {"logicalor", XPUKernelSet({BOOL, INT8, INT16, INT32, INT64, FLOAT32})},
      {"log_loss_grad", XPUKernelSet({FLOAT32})},
      {"log_loss", XPUKernelSet({FLOAT32})},
      {"logsumexp", XPUKernelSet({FLOAT32})},
      {"log", XPUKernelSet({FLOAT32})},
      {"lookup_table_v2_grad", XPUKernelSet({FLOAT32})},
      {"lookup_table_v2", XPUKernelSet({FLOAT32})},
      {"matmul_grad", XPUKernelSet({FLOAT32})},
      {"matmul_v2_grad", XPUKernelSet({FLOAT32})},
      {"matmul_v2", XPUKernelSet({FLOAT32})},
      {"matmul", XPUKernelSet({FLOAT32})},
      {"mean_grad", XPUKernelSet({FLOAT32})},
      {"mean", XPUKernelSet({FLOAT32})},
      {"momentum", XPUKernelSet({FLOAT32})},
      {"mul_grad", XPUKernelSet({FLOAT32})},
      {"mul", XPUKernelSet({FLOAT32})},
      {"nearest_interp_grad", XPUKernelSet({FLOAT32})},
      {"nearest_interp_v2_grad", XPUKernelSet({FLOAT32})},
      {"nearest_interp_v2", XPUKernelSet({FLOAT32})},
      {"nearest_interp", XPUKernelSet({FLOAT32})},
      {"one_hot_v2", XPUKernelSet({INT32, INT64})},
      {"one_hot", XPUKernelSet({INT32, INT64})},
      {"pool2d_grad", XPUKernelSet({FLOAT32})},
      {"pool2d", XPUKernelSet({FLOAT32})},
      {"pow", XPUKernelSet({FLOAT32})},
      {"range", XPUKernelSet({FLOAT64, INT64, INT32, FLOAT32})},
      {"reduce_max_grad", XPUKernelSet({FLOAT32})},
      {"reduce_max", XPUKernelSet({FLOAT32})},
      {"reduce_mean", XPUKernelSet({FLOAT32})},
      {"reduce_mean_grad", XPUKernelSet({FLOAT32})},
      {"reduce_prod", XPUKernelSet({FLOAT32})},
      {"reduce_sum_grad", XPUKernelSet({FLOAT32})},
      {"reduce_sum", XPUKernelSet({FLOAT32})},
      {"relu_grad", XPUKernelSet({FLOAT32})},
      {"relu", XPUKernelSet({FLOAT32})},
      {"reshape2_grad", XPUKernelSet({FLOAT64, INT64, INT32, BOOL, FLOAT32})},
      {"reshape2", XPUKernelSet({FLOAT64, INT64, INT32, BOOL, FLOAT32})},
      {"rmsprop", XPUKernelSet({FLOAT32})},
      {"rnn_grad", XPUKernelSet({FLOAT32})},
      {"rnn", XPUKernelSet({FLOAT32})},
      {"roi_align_grad", XPUKernelSet({FLOAT32})},
      {"roi_align", XPUKernelSet({FLOAT32})},
      {"scale", XPUKernelSet({FLOAT32, INT64, INT32})},
      {"sgd", XPUKernelSet({FLOAT32})},
      {"shape", XPUKernelSet({FLOAT64, INT64, INT32, BOOL, FLOAT32})},
      {"shape64", XPUKernelSet({FLOAT64, INT64, INT32, BOOL, FLOAT32})},
      {"sigmoid_grad", XPUKernelSet({FLOAT32})},
      {"sigmoid", XPUKernelSet({FLOAT32})},
      {"sign", XPUKernelSet({FLOAT32})},
      {"slice_grad", XPUKernelSet({FLOAT32})},
      {"slice", XPUKernelSet({FLOAT32, INT32, INT64, FLOAT16})},
      {"softmax_grad", XPUKernelSet({FLOAT32})},
      {"softmax_with_cross_entropy", XPUKernelSet({FLOAT32})},
      {"softmax_with_cross_entropy_grad", XPUKernelSet({FLOAT32})},
      {"softmax", XPUKernelSet({FLOAT32})},
      {"split", XPUKernelSet({FLOAT32, INT32})},
      {"sqrt_grad", XPUKernelSet({FLOAT32})},
      {"sqrt", XPUKernelSet({FLOAT32})},
      {"square_grad", XPUKernelSet({FLOAT32})},
      {"square", XPUKernelSet({FLOAT32})},
      {"squeeze2_grad",
       XPUKernelSet({FLOAT64, INT64, INT32, BOOL, INT8, UINT8, FLOAT32})},
      {"squeeze2",
       XPUKernelSet({FLOAT64, INT64, INT32, BOOL, INT8, UINT8, FLOAT32})},
      {"squeeze_grad",
       XPUKernelSet({FLOAT64, INT64, INT32, BOOL, INT8, UINT8, FLOAT32})},
      {"squeeze",
       XPUKernelSet({FLOAT64, INT64, INT32, BOOL, INT8, UINT8, FLOAT32})},
      {"stack", XPUKernelSet({FLOAT32})},
      {"stack_grad", XPUKernelSet({FLOAT32})},
      {"sum", XPUKernelSet({FLOAT32})},
      {"tanh_grad", XPUKernelSet({FLOAT32})},
      {"tanh", XPUKernelSet({FLOAT32})},
      {"top_k", XPUKernelSet({FLOAT32})},
      {"transpose2_grad", XPUKernelSet({FLOAT32})},
      {"transpose2", XPUKernelSet({FLOAT32})},
      {"transpose_grad", XPUKernelSet({FLOAT32})},
      {"transpose", XPUKernelSet({FLOAT32})},
      {"truncated_gaussian_random", XPUKernelSet({FLOAT32})},
      {"uniform_random", XPUKernelSet({FLOAT32})},
      {"unsqueeze2_grad",
       XPUKernelSet({FLOAT64, INT64, INT32, BOOL, INT8, UINT8, FLOAT32})},
      {"unsqueeze2",
       XPUKernelSet({FLOAT64, INT64, INT32, BOOL, INT8, UINT8, FLOAT32})},
      {"unsqueeze_grad",
       XPUKernelSet({FLOAT64, INT64, INT32, BOOL, INT8, UINT8, FLOAT32})},
      {"unsqueeze",
       XPUKernelSet({FLOAT64, INT64, INT32, BOOL, INT8, UINT8, FLOAT32})},
      {"where_index", XPUKernelSet({BOOL})},
      {"where", XPUKernelSet({INT32, INT64, FLOAT32})},
      {"fast_where_xpu", XPUKernelSet({FLOAT32, INT32, INT64})},
      // AddMore
  };

  return s_xpu1_kernels;
}

}  // namespace xpu
}  // namespace backends
}  // namespace phi
#endif
