/* Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License. */

#ifdef PADDLE_WITH_XPU
#include <string>
#include <unordered_map>
#include <unordered_set>
#include "paddle/phi/backends/xpu/xpu_op_list.h"

namespace phi {
namespace backends {
namespace xpu {

XPUOpMap& get_kl2_ops() {
  // KL2支持的op，通过op_name, data_type, place来索引
  static XPUOpMap s_xpu2_kernels{
      {"add_act_xpu", XPUKernelSet({FLOAT32, FLOAT16})},
      {"add_layernorm_xpu", XPUKernelSet({FLOAT32, FLOAT16})},
      {"abs", XPUKernelSet({FLOAT32, FLOAT16, INT32, INT8, INT64})},
      {"abs_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"accuracy", XPUKernelSet({FLOAT32})},
      {"adadelta", XPUKernelSet({FLOAT32})},
      {"adamw", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"adam", XPUKernelSet({FLOAT32, FLOAT16})},
      {"adam_dense_param_sparse_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"adagrad", XPUKernelSet({FLOAT32})},
      {"addcmul_xpu", XPUKernelSet({FLOAT32, FLOAT16})},
      {"addmm", XPUKernelSet({FLOAT32, FLOAT16})},
      {"addmm_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"arange_tensor", XPUKernelSet({FLOAT32, INT32, INT64})},
      {"arg_max", XPUKernelSet({INT32, FLOAT32, FLOAT16})},
      {"argsort_grad", XPUKernelSet({INT32, INT64, FLOAT32})},
      {"argsort", XPUKernelSet({INT32, INT64, FLOAT16, FLOAT32})},
      {"assign", XPUKernelSet({FLOAT32, FLOAT64, INT32, FLOAT16, INT64, BOOL})},
      {"assign_raw",
       XPUKernelSet({FLOAT32, FLOAT64, INT32, FLOAT16, INT64, BOOL})},
      {"assign_value", XPUKernelSet({FLOAT32, INT32, INT64, BOOL})},
      {"atan", XPUKernelSet({FLOAT32, FLOAT16})},
      {"atan_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"batch_norm_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"batch_norm", XPUKernelSet({FLOAT32, FLOAT16})},
      {"bn_act_xpu", XPUKernelSet({FLOAT32, FLOAT16})},
      {"bmm", XPUKernelSet({FLOAT32, FLOAT16})},
      {"bmm_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"bce_loss_grad", XPUKernelSet({FLOAT32})},
      {"bce_loss", XPUKernelSet({FLOAT32})},
      {"beam_search", XPUKernelSet({FLOAT32, FLOAT64, INT32, INT64})},
      {"beam_search_decode",
       XPUKernelSet({FLOAT32, FLOAT64, FLOAT16, INT32, INT64})},
      {"bilinear_interp_v2", XPUKernelSet({FLOAT32, FLOAT16})},
      {"bilinear_interp_v2_grad", XPUKernelSet({FLOAT32})},
      {"bitwise_not", XPUKernelSet({BOOL})},
      {"bitwise_and", XPUKernelSet({BOOL})},
      {"bitwise_or", XPUKernelSet({BOOL})},
      {"broadcast", XPUKernelSet({FLOAT32})},
      {"c_alltoall", XPUKernelSet({FLOAT16, FLOAT32, INT32, INT64, UINT8})},
      {"c_allreduce_max", XPUKernelSet({FLOAT16, FLOAT32, INT32})},
      {"c_allreduce_sum", XPUKernelSet({FLOAT16, FLOAT32, INT32})},
      {"c_broadcast", XPUKernelSet({FLOAT16, FLOAT32, FLOAT64, INT32, INT64})},
      {"c_concat", XPUKernelSet({FLOAT16, FLOAT32, INT32, INT64})},
      {"c_embedding", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"c_embedding_grad", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"c_identity",
       XPUKernelSet({FLOAT16, FLOAT32, FLOAT64, BFLOAT16, INT32, INT64})},
      {"gather_part", XPUKernelSet({FLOAT32, FLOAT16, INT32, INT64, BOOL})},
      {"c_softmax_with_cross_entropy", XPUKernelSet({FLOAT32})},
      {"c_softmax_with_cross_entropy_grad", XPUKernelSet({FLOAT32})},
      {"c_reduce_sum", XPUKernelSet({FLOAT32})},
      {"c_split", XPUKernelSet({FLOAT16, FLOAT32, INT32, BFLOAT16})},
      {"c_sync_calc_stream",
       XPUKernelSet({FLOAT16, FLOAT32, FLOAT64, INT32, INT64})},
      {"c_sync_comm_stream", XPUKernelSet({FLOAT32})},
      {"cast",
       XPUKernelSet({FLOAT32,
                     FLOAT16,
                     BFLOAT16,
                     FLOAT64,
                     BOOL,
                     INT8,
                     UINT8,
                     INT16,
                     INT64,
                     INT32})},
      {"check_finite_and_unscale", XPUKernelSet({FLOAT32, FLOAT16})},
      {"clip", XPUKernelSet({FLOAT32, FLOAT16, INT64, INT32})},
      {"clip_by_norm", XPUKernelSet({FLOAT32})},
      {"clip_grad", XPUKernelSet({FLOAT32, INT64, INT32})},
      {"coalesce_tensor", XPUKernelSet({FLOAT32, FLOAT16})},
      {"concat_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"concat",
       XPUKernelSet({FLOAT32, FLOAT16, FLOAT64, BOOL, INT8, INT64, INT32})},
      {"conv2d_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"conv2d", XPUKernelSet({FLOAT32, FLOAT16})},
      {"conv1d_xpu", XPUKernelSet({FLOAT32, FLOAT16})},
      {"conv2d_xpu", XPUKernelSet({FLOAT32, FLOAT16, INT8})},
      {"conv3d_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"conv3d", XPUKernelSet({FLOAT32, FLOAT16})},
      {"conv2d_transpose_grad", XPUKernelSet({FLOAT32})},
      {"conv2d_transpose", XPUKernelSet({FLOAT32, FLOAT16})},
      {"conv2d_transpose_xpu", XPUKernelSet({FLOAT32, FLOAT16})},
      {"cumsum", XPUKernelSet({FLOAT32, FLOAT16, INT32, INT64, BFLOAT16})},
      {"cumsum_grad", XPUKernelSet({FLOAT32, INT32, INT64})},
      {"cumprod", XPUKernelSet({FLOAT32, INT32, INT64})},
      {"deformable_conv_grad", XPUKernelSet({FLOAT32})},
      {"deformable_conv", XPUKernelSet({FLOAT32})},
      {"deformable_conv_v1_grad", XPUKernelSet({FLOAT32})},
      {"deformable_conv_v1", XPUKernelSet({FLOAT32})},
      {"depthwise_conv2d_grad", XPUKernelSet({FLOAT32})},
      {"depthwise_conv2d", XPUKernelSet({FLOAT32, FLOAT16})},
      {"depthwise_conv2d_transpose_grad", XPUKernelSet({FLOAT32})},
      {"depthwise_conv2d_transpose", XPUKernelSet({FLOAT32, FLOAT16})},
      {"dequantize_xpu", XPUKernelSet({INT16, INT8})},
      {"diag_v2", XPUKernelSet({FLOAT32, FLOAT16, INT32, INT64})},
      {"distribute_fpn_proposals", XPUKernelSet({FLOAT32})},
      {"diagonal", XPUKernelSet({INT64, INT32, BOOL, FLOAT16, FLOAT32})},
      {"dropout_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"dropout", XPUKernelSet({FLOAT32, FLOAT16})},
      {"einsum", XPUKernelSet({FLOAT32})},
      {"einsum_grad", XPUKernelSet({FLOAT32})},
      {"elementwise_add_grad", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"elementwise_add",
       XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16, INT64, INT32})},
      {"elementwise_div_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"elementwise_div", XPUKernelSet({FLOAT32, FLOAT16, INT64, INT32})},
      {"elementwise_floordiv", XPUKernelSet({FLOAT32, FLOAT16, INT32, INT64})},
      {"elementwise_max_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"elementwise_max", XPUKernelSet({FLOAT32, FLOAT16, INT32, INT64})},
      {"elementwise_min_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"elementwise_min", XPUKernelSet({FLOAT32, FLOAT16, INT32, INT64})},
      {"elementwise_mul_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"elementwise_mul", XPUKernelSet({FLOAT32, FLOAT16, INT32, INT64})},
      {"elementwise_pow", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"elementwise_sub_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"elementwise_sub", XPUKernelSet({FLOAT32, FLOAT16, INT32, INT64})},
      {"elementwise_mod", XPUKernelSet({FLOAT32, FLOAT16, INT64, INT32})},
      {"elu", XPUKernelSet({FLOAT32, FLOAT16})},
      {"embedding_with_eltwise_add_xpu", XPUKernelSet({FLOAT32, FLOAT16})},
      {"empty",
       XPUKernelSet({INT64,
                     INT32,
                     INT16,
                     INT8,
                     UINT8,
                     BOOL,
                     FLOAT16,
                     FLOAT32,
                     FLOAT64,
                     BFLOAT16})},
      {"empty_like",
       XPUKernelSet({INT64,
                     INT32,
                     INT16,
                     INT8,
                     UINT8,
                     BOOL,
                     FLOAT16,
                     FLOAT32,
                     FLOAT64,
                     BFLOAT16})},
      {"embedding_grad", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"embedding_sparse_grad", XPUKernelSet({FLOAT32})},
      {"equal", XPUKernelSet({INT64, INT32, FLOAT16, FLOAT32, BOOL})},
      {"exp_grad", XPUKernelSet({FLOAT32})},
      {"exp", XPUKernelSet({FLOAT32})},
      {"expand_as_v2", XPUKernelSet({INT32, INT64, BOOL, FLOAT16, FLOAT32})},
      {"expand_v2",
       XPUKernelSet({INT32, INT64, BOOL, FLOAT16, FLOAT32, BFLOAT16})},
      {"fast_where_xpu", XPUKernelSet({INT32, FLOAT32, FLOAT16})},
      {"layer_norm_act_xpu", XPUKernelSet({FLOAT32, FLOAT16})},
      {"fast_layernorm_xpu", XPUKernelSet({FLOAT32, FLOAT16})},
      {"fc_xpu", XPUKernelSet({FLOAT32, FLOAT16, INT8})},
      {"fill",
       XPUKernelSet({INT64, INT32, FLOAT16, BFLOAT16, FLOAT64, FLOAT32})},
      {"fill_any",
       XPUKernelSet({INT64, INT32, FLOAT16, BFLOAT16, FLOAT64, FLOAT32})},
      {"fill_any_like", XPUKernelSet({INT64, INT32, BOOL, FLOAT16, FLOAT32})},
      {"fill_diagonal_tensor",
       XPUKernelSet({INT64, INT32, BOOL, FLOAT16, FLOAT32})},
      {"fill_constant",
       XPUKernelSet({INT64,
                     INT32,
                     INT16,
                     INT8,
                     UINT8,
                     BOOL,
                     FLOAT32,
                     FLOAT16,
                     BFLOAT16})},
      {"fill_constant_batch_size_like",
       XPUKernelSet({INT64, INT32, FLOAT32, FLOAT16, BFLOAT16})},
      {"flatten2_grad", XPUKernelSet({INT64, INT32, INT8, FLOAT32})},
      {"flatten2", XPUKernelSet({INT64, INT32, INT8, FLOAT32})},
      {"flatten_contiguous_range_grad",
       XPUKernelSet({INT64, INT32, INT8, FLOAT16, BFLOAT16, FLOAT32})},
      {"flatten_contiguous_range",
       XPUKernelSet({INT64, INT32, INT8, FLOAT16, BFLOAT16, FLOAT32})},
      {"flatten_grad",
       XPUKernelSet({INT64, INT32, INT8, FLOAT16, BFLOAT16, FLOAT32})},
      {"flatten", XPUKernelSet({INT64, INT32, INT8, FLOAT32})},
      {"flip", XPUKernelSet({FLOAT32})},
      {"full",
       XPUKernelSet({INT64, INT32, BOOL, FLOAT64, FLOAT16, FLOAT32, BFLOAT16})},
      {"full_batch_size_like",
       XPUKernelSet({INT64, INT32, BOOL, FLOAT32, FLOAT16, BFLOAT16})},
      {"full_like",
       XPUKernelSet({INT64, INT32, BOOL, FLOAT32, FLOAT64, FLOAT16, BFLOAT16})},
      {"fused_multi_transformer_xpu", XPUKernelSet({FLOAT32, FLOAT16})},
      {"fused_multi_transformer_int8_xpu", XPUKernelSet({FLOAT16})},
      {"fused_rotary_position_embedding",
       XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"fused_rotary_position_embedding_grad",
       XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"unfold", XPUKernelSet({FLOAT32, FLOAT16})},
      {"unfold_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"floor", XPUKernelSet({FLOAT32})},
      {"gather_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"gather_nd_grad", XPUKernelSet({INT32, INT64, FLOAT32})},
      {"gather_nd", XPUKernelSet({INT32, INT64, FLOAT32, FLOAT16})},
      {"gather", XPUKernelSet({FLOAT32, FLOAT16, INT32, INT64, BOOL})},
      {"gather_inplace", XPUKernelSet({FLOAT32, FLOAT16, INT32, INT64, BOOL})},
      {"gaussian_random", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"gelu_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"gelu", XPUKernelSet({FLOAT32, FLOAT16})},
      {"generate_proposals_v2", XPUKernelSet({FLOAT32})},
      {"generate_sequence_xpu",
       XPUKernelSet({
           FLOAT32,
           INT32,
           INT64,
       })},
      {"grad_add", XPUKernelSet({FLOAT32, FLOAT16})},
      {"greater_equal", XPUKernelSet({INT64, INT32, FLOAT16, FLOAT32})},
      {"greater_than", XPUKernelSet({INT64, INT32, FLOAT16, FLOAT32})},
      {"grid_sampler_grad", XPUKernelSet({FLOAT32})},
      {"grid_sampler", XPUKernelSet({FLOAT32})},
      {"group_norm_silu_xpu", XPUKernelSet({FLOAT32, FLOAT16})},
      {"layer_norm_relu_xpu", XPUKernelSet({FLOAT32, FLOAT16})},
      {"hard_sigmoid_grad", XPUKernelSet({FLOAT32})},
      {"hard_sigmoid", XPUKernelSet({FLOAT32, FLOAT16})},
      {"hard_swish_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"hard_swish", XPUKernelSet({FLOAT32, FLOAT16})},
      {"huber_loss_grad", XPUKernelSet({FLOAT32})},
      {"huber_loss", XPUKernelSet({FLOAT32})},
      {"kldiv_loss", XPUKernelSet({FLOAT32})},
      {"kldiv_loss_grad", XPUKernelSet({FLOAT32})},
      {"increment", XPUKernelSet({FLOAT32, INT32, INT64})},
      {"index_put", XPUKernelSet({FLOAT32, INT32, INT64})},
      {"index_put_grad", XPUKernelSet({FLOAT32, INT32, INT64})},
      {"index_sample_grad", XPUKernelSet({FLOAT32})},
      {"index_sample",
       XPUKernelSet({INT8, INT16, INT32, FLOAT16, FLOAT32, BOOL})},
      {"index_select_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"index_select", XPUKernelSet({FLOAT32, INT32, INT64})},
      {"instance_norm", XPUKernelSet({FLOAT32, FLOAT16})},
      {"instance_norm_grad", XPUKernelSet({FLOAT32})},
      {"inverse", XPUKernelSet({FLOAT32, FLOAT64})},
      {"label_smooth", XPUKernelSet({FLOAT32})},
      {"lamb", XPUKernelSet({FLOAT32, FLOAT16})},
      {"lars_momentum", XPUKernelSet({FLOAT32, FLOAT16})},
      {"layer_norm_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"layer_norm", XPUKernelSet({FLOAT32, FLOAT16})},
      {"leaky_relu_grad", XPUKernelSet({FLOAT32})},
      {"leaky_relu", XPUKernelSet({FLOAT32, FLOAT16})},
      {"less_equal", XPUKernelSet({INT64, INT32, FLOAT16, FLOAT32})},
      {"less_than", XPUKernelSet({INT64, INT32, FLOAT16, FLOAT32})},
      {"load", XPUKernelSet({FLOAT32})},
      {"load_combine", XPUKernelSet({FLOAT32, FLOAT64, INT8, INT32, INT64})},
      {"log", XPUKernelSet({FLOAT32, FLOAT16})},
      {"log_grad", XPUKernelSet({FLOAT32})},
      {"log_softmax", XPUKernelSet({FLOAT32})},
      {"log_softmax_grad", XPUKernelSet({FLOAT32})},
      {"logical_and", XPUKernelSet({BOOL})},
      {"logical_not", XPUKernelSet({BOOL})},
      {"logical_or", XPUKernelSet({BOOL})},
      {"logical_xor", XPUKernelSet({BOOL})},
      {"lookup_table_v2_grad", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"lookup_table_v2", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"masked_select",
       XPUKernelSet({INT32, INT64, FLOAT16, BFLOAT16, FLOAT32})},
      {"masked_select_grad",
       XPUKernelSet({INT32, INT64, BOOL, FLOAT16, BFLOAT16, FLOAT32})},
      {"max_pool2d_with_index", XPUKernelSet({FLOAT32, FLOAT16})},
      {"max_pool2d_with_index_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"matmul_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"matmul_v2_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"matmul_v2", XPUKernelSet({FLOAT32, FLOAT16})},
      {"matmul", XPUKernelSet({FLOAT32, FLOAT16})},
      {"mean_grad", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"mean", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"merged_adam", XPUKernelSet({FLOAT32})},
      {"merged_momentum", XPUKernelSet({FLOAT32, FLOAT16})},
      {"mish_grad", XPUKernelSet({FLOAT32})},
      {"mish", XPUKernelSet({FLOAT32})},
      {"momentum", XPUKernelSet({FLOAT32, FLOAT16})},
      {"mul", XPUKernelSet({FLOAT32, FLOAT16})},
      {"mul_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"multiply", XPUKernelSet({FLOAT32, FLOAT16, INT32, INT64})},
      {"multi_encoder_xpu", XPUKernelSet({FLOAT32, FLOAT16})},
      {"multiclass_nms3", XPUKernelSet({FLOAT32})},
      {"multinomial", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"nearest_interp_v2", XPUKernelSet({FLOAT32, FLOAT16, INT64})},
      {"nearest_interp_v2_grad", XPUKernelSet({FLOAT32})},
      {"nll_loss", XPUKernelSet({FLOAT32})},
      {"nll_loss_grad", XPUKernelSet({FLOAT32})},
      {"norm", XPUKernelSet({FLOAT32})},
      {"not_equal", XPUKernelSet({INT64, INT32, FLOAT16, FLOAT32})},
      {"one_hot", XPUKernelSet({INT32, INT64})},
      {"one_hot_v2", XPUKernelSet({INT32, INT64})},
      {"p_norm", XPUKernelSet({FLOAT32})},
      {"p_norm_grad", XPUKernelSet({FLOAT32})},
      {"pad3d_grad", XPUKernelSet({FLOAT32})},
      {"pad3d", XPUKernelSet({FLOAT32, FLOAT16})},
      {"pad", XPUKernelSet({FLOAT32, INT32, INT16, FLOAT16})},
      {"pad_grad", XPUKernelSet({FLOAT32, INT32, INT16, FLOAT16})},
      {"pixel_shuffle", XPUKernelSet({FLOAT32})},
      {"pixel_shuffle_grad", XPUKernelSet({FLOAT32})},
      {"pool2d_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"pool2d", XPUKernelSet({FLOAT32, FLOAT16})},
      {"pool3d_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"pool3d", XPUKernelSet({FLOAT32, FLOAT16})},
      {"pow", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"pow_grad", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"pow2_decay_with_linear_warmup", XPUKernelSet({FLOAT32})},
      {"prior_box", XPUKernelSet({FLOAT32})},
      {"prelu", XPUKernelSet({FLOAT32})},
      {"prelu_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"prod_raw", XPUKernelSet({FLOAT32})},
      {"quantize_xpu", XPUKernelSet({FLOAT32, FLOAT16})},
      {"range", XPUKernelSet({FLOAT32, INT64, INT32})},
      {"randperm", XPUKernelSet({INT32, INT64, FLOAT32, FLOAT64})},
      {"reciprocal", XPUKernelSet({FLOAT32})},
      {"reciprocal_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"reduce_all", XPUKernelSet({BOOL})},
      {"reduce_any", XPUKernelSet({BOOL})},
      {"reduce_max_grad", XPUKernelSet({FLOAT32})},
      {"reduce_max",
       XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16, INT32, INT64, FLOAT16})},
      {"reduce_mean_grad", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"reduce_mean", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"reduce_min_grad", XPUKernelSet({FLOAT32})},
      {"reduce_min", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"reduce_prod", XPUKernelSet({FLOAT32, INT32, INT64})},
      {"reduce_sum_grad", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"reduce_sum",
       XPUKernelSet({FLOAT16, INT64, INT32, INT8, FLOAT32, BFLOAT16})},
      {"relu6", XPUKernelSet({FLOAT32, FLOAT16})},
      {"relu6_grad", XPUKernelSet({FLOAT32})},
      {"relu_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"relu", XPUKernelSet({FLOAT32, FLOAT16})},
      {"repeat_interleave", XPUKernelSet({INT32, INT64})},
      {"reshape2_grad",
       XPUKernelSet({FLOAT64, FLOAT16, INT64, INT32, BOOL, FLOAT32})},
      {"reshape2",
       XPUKernelSet({FLOAT64, FLOAT16, INT64, INT32, BOOL, FLOAT32})},
      {"reshape",
       XPUKernelSet({FLOAT64, FLOAT16, INT64, INT32, BOOL, FLOAT32})},
      {"resnet_unit", XPUKernelSet({FLOAT16, FLOAT32})},
      {"resnet_unit_grad", XPUKernelSet({FLOAT16, FLOAT32})},
      {"rmsprop", XPUKernelSet({FLOAT32})},
      {"rnn", XPUKernelSet({FLOAT32})},
      {"rnn_grad", XPUKernelSet({FLOAT32})},
      {"roi_align", XPUKernelSet({FLOAT32})},
      {"roi_align_grad", XPUKernelSet({FLOAT32})},
      {"roll", XPUKernelSet({FLOAT32})},
      {"roll_grad", XPUKernelSet({FLOAT32})},
      {"rsqrt", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"rsqrt_grad", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"save",
       XPUKernelSet(
           {FLOAT32, FLOAT64, INT32, UINT8, INT8, INT64, FLOAT16, BFLOAT16})},
      {"scale", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16, INT64, INT32})},
      {"scatter", XPUKernelSet({INT64, INT32, FLOAT32})},
      {"scatter_grad", XPUKernelSet({FLOAT16, FLOAT32})},
      {"scatter_nd_add", XPUKernelSet({FLOAT32, INT32, INT64})},
      {"scatter_nd_add_grad", XPUKernelSet({FLOAT32, FLOAT16, INT32, INT64})},
      {"set_value", XPUKernelSet({FLOAT32, INT32, INT64, FLOAT16, BOOL})},
      {"set_value_with_tensor",
       XPUKernelSet({FLOAT32, FLOAT16, INT32, INT64, BOOL})},
      {"set_value_grad", XPUKernelSet({FLOAT32, INT32, INT64, FLOAT16})},
      {"sgd", XPUKernelSet({FLOAT32, FLOAT16})},
      {"sgd_dense_param_sparse_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"silu_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"silu", XPUKernelSet({FLOAT32, FLOAT16})},
      {"size", XPUKernelSet({INT64, INT32, INT16, BOOL, FLOAT16, FLOAT32})},
      {"sigmoid_cross_entropy_with_logits_grad", XPUKernelSet({FLOAT32})},
      {"sigmoid_cross_entropy_with_logits", XPUKernelSet({FLOAT32})},
      {"shape", XPUKernelSet({FLOAT32, INT64, INT32, FLOAT16, BFLOAT16})},
      {"shape64", XPUKernelSet({FLOAT32, INT64, INT32, FLOAT16, BFLOAT16})},
      {"sigmoid", XPUKernelSet({FLOAT32, FLOAT16})},
      {"sigmoid_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"sign", XPUKernelSet({FLOAT32})},
      {"slice_grad", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16, INT32})},
      {"slice", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16, INT32, INT64})},
      {"softmax", XPUKernelSet({FLOAT32, FLOAT16})},
      {"fused_softmax_mask", XPUKernelSet({FLOAT32})},
      {"softmax_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"fused_softmax_mask_grad", XPUKernelSet({FLOAT32})},
      {"softmax_with_cross_entropy_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"softmax_with_cross_entropy", XPUKernelSet({FLOAT32, FLOAT16})},
      {"softplus", XPUKernelSet({FLOAT32})},
      {"softplus_grad", XPUKernelSet({FLOAT32})},
      {"sparse_coo_tensor",
       XPUKernelSet({FLOAT64, INT64, INT32, UINT8, INT16, FLOAT32, FLOAT16})},
      {"spatial_transformer_resblock_xpu", XPUKernelSet({FLOAT32, FLOAT16})},
      {"split", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16, INT32, INT64})},
      {"split_with_num",
       XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16, INT32, INT64})},
      {"sqrt", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"sqrt_grad", XPUKernelSet({FLOAT32})},
      {"square_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"square", XPUKernelSet({FLOAT32, FLOAT16})},
      {"squared_l2_norm", XPUKernelSet({FLOAT32, FLOAT16})},
      {"squared_l2_norm_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"squeeze2_grad",
       XPUKernelSet({FLOAT64,
                     INT64,
                     INT32,
                     BOOL,
                     INT8,
                     UINT8,
                     FLOAT16,
                     BFLOAT16,
                     FLOAT32})},
      {"squeeze2",
       XPUKernelSet({FLOAT64,
                     INT64,
                     INT32,
                     BOOL,
                     INT8,
                     UINT8,
                     FLOAT16,
                     BFLOAT16,
                     FLOAT32})},
      {"squeeze",
       XPUKernelSet({FLOAT64,
                     INT64,
                     INT32,
                     BOOL,
                     INT8,
                     UINT8,
                     FLOAT16,
                     BFLOAT16,
                     FLOAT32})},
      {"squeeze_grad",
       XPUKernelSet({FLOAT64,
                     INT64,
                     INT32,
                     BOOL,
                     INT8,
                     UINT8,
                     FLOAT16,
                     BFLOAT16,
                     FLOAT32})},
      {"stack", XPUKernelSet({FLOAT32, INT64, INT32, FLOAT16})},
      {"stack_grad", XPUKernelSet({FLOAT32, INT32})},
      {"strided_slice",
       XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16, INT16, INT32, INT64})},
      {"strided_slice_grad",
       XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16, INT16, INT32})},
      {"sum", XPUKernelSet({FLOAT32, FLOAT16})},
      {"swish", XPUKernelSet({FLOAT32, FLOAT16})},
      {"swish_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"swiglu", XPUKernelSet({FLOAT32, FLOAT16})},
      {"swiglu_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"take_along_axis", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"tanh_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"tanh", XPUKernelSet({FLOAT32, FLOAT16})},
      {"temporal_shift", XPUKernelSet({FLOAT32})},
      {"temporal_shift_grad", XPUKernelSet({FLOAT32})},
      {"transfer_dtype",
       XPUKernelSet({FLOAT32,
                     FLOAT16,
                     BFLOAT16,
                     FLOAT64,
                     BOOL,
                     UINT8,
                     INT8,
                     INT64,
                     INT32})},
      {"tril_triu", XPUKernelSet({FLOAT32, INT32, FLOAT16})},
      {"tril", XPUKernelSet({FLOAT32, INT32, FLOAT16})},
      {"triu", XPUKernelSet({FLOAT32, INT32, FLOAT16})},
      {"tril_triu_grad", XPUKernelSet({FLOAT32, INT32, FLOAT16})},
      {"tril_grad", XPUKernelSet({FLOAT32, INT32, FLOAT16})},
      {"triu_grad", XPUKernelSet({FLOAT32, INT32, FLOAT16})},
      {"tile", XPUKernelSet({INT32, INT64, BOOL, FLOAT64, FLOAT32, FLOAT16})},
      {"tile_grad", XPUKernelSet({FLOAT32})},
      {"transpose2_grad",
       XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16, INT64, INT32, BOOL})},
      {"transpose2",
       XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16, INT64, INT32, BOOL})},
      {"transpose_grad",
       XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16, INT64, INT32, BOOL})},
      {"transpose",
       XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16, INT64, INT32, BOOL})},
      {"truncated_gaussian_random", XPUKernelSet({FLOAT32})},
      {"top_k", XPUKernelSet({FLOAT32, FLOAT16})},
      {"top_k_v2", XPUKernelSet({FLOAT32, FLOAT16})},
      {"top_p_sampling", XPUKernelSet({FLOAT32, FLOAT16})},
      {"update_loss_scaling", XPUKernelSet({FLOAT32, FLOAT16})},
      {"unbind", XPUKernelSet({FLOAT32})},
      {"uniform_random", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"unique", XPUKernelSet({FLOAT32, INT32, INT64})},
      {"unsqueeze2_grad",
       XPUKernelSet({FLOAT64,
                     INT64,
                     INT32,
                     BOOL,
                     INT8,
                     UINT8,
                     FLOAT32,
                     FLOAT16,
                     BFLOAT16})},
      {"unsqueeze2",
       XPUKernelSet({FLOAT64,
                     INT64,
                     INT32,
                     BOOL,
                     INT8,
                     UINT8,
                     FLOAT32,
                     FLOAT16,
                     BFLOAT16})},
      {"unsqueeze_grad",
       XPUKernelSet({FLOAT64,
                     INT64,
                     INT32,
                     BOOL,
                     INT8,
                     UINT8,
                     FLOAT32,
                     FLOAT16,
                     BFLOAT16})},
      {"unsqueeze",
       XPUKernelSet({FLOAT64,
                     INT64,
                     INT32,
                     BOOL,
                     INT8,
                     UINT8,
                     FLOAT32,
                     FLOAT16,
                     BFLOAT16})},
      {"unstack", XPUKernelSet({INT64, INT32, FLOAT16, FLOAT32})},
      {"unstack_grad", XPUKernelSet({INT64, INT32, FLOAT16, FLOAT32})},
      {"warpctc_grad", XPUKernelSet({FLOAT32})},
      {"warpctc", XPUKernelSet({FLOAT32})},
      {"weight_only_linear", XPUKernelSet({FLOAT16, BFLOAT16})},
      {"where_index", XPUKernelSet({INT32, BOOL, FLOAT32, INT64})},
      {"where_grad", XPUKernelSet({INT32, INT64, FLOAT16, FLOAT32})},
      {"where", XPUKernelSet({INT32, INT64, FLOAT32, FLOAT16, BFLOAT16})},
      {"sin", XPUKernelSet({FLOAT32, FLOAT16})},
      {"sin_grad", XPUKernelSet({FLOAT32})},
      {"cos", XPUKernelSet({FLOAT32, FLOAT16})},
      {"cos_grad", XPUKernelSet({FLOAT32})},
      {"linspace", XPUKernelSet({FLOAT32, INT32, INT64})},
      {"randint", XPUKernelSet({INT32, INT64})},
      {"fused_rms_norm_quant", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"fused_rms_norm_quant_grad", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"group_norm", XPUKernelSet({FLOAT32})},
      {"group_norm_grad", XPUKernelSet({FLOAT32})},
      {"meshgrid", XPUKernelSet({FLOAT32, INT32, INT64})},
      {"expand_v2_grad", XPUKernelSet({FLOAT32, BFLOAT16, FLOAT16})},
      {"eye", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"isnan_v2", XPUKernelSet({FLOAT32, FLOAT16})},
      {"yolo_box_xpu", XPUKernelSet({FLOAT32, FLOAT16})},

      // AddMore
      {"sequence_conv", XPUKernelSet({FLOAT32})},
      {"sequence_conv_grad", XPUKernelSet({FLOAT32})},
      {"sequence_unpad", XPUKernelSet({FLOAT32})},
      // Fused op
      {"squeeze_excitation_block", XPUKernelSet({FLOAT32, FLOAT16})},
      {"resnet_basic_block_grad", XPUKernelSet({FLOAT32})},
      {"resnet_basic_block", XPUKernelSet({FLOAT32})},
      {"fused_gemm_epilogue", XPUKernelSet({FLOAT32, FLOAT16})},
      {"fused_gemm_epilogue_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"fused_bias_residual_layernorm", XPUKernelSet({FLOAT32, FLOAT16})},
      {"fused_attention", XPUKernelSet({FLOAT32, FLOAT16})},
      {"fused_attention_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"fused_bias_act", XPUKernelSet({FLOAT32, FLOAT16})},
      {"fused_feedforward", XPUKernelSet({FLOAT32, FLOAT16})},
      {"fused_feedforward_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"qkv_attention_xpu", XPUKernelSet({FLOAT32, FLOAT16, INT8})},
      {"lod_reset", XPUKernelSet({FLOAT32, FLOAT16, FLOAT64, INT32, INT64})},
      {"mp_allreduce_sum", XPUKernelSet({FLOAT16, FLOAT32, INT32})},
      {"sine_pos_xpu", XPUKernelSet({FLOAT16, FLOAT32})},
      {"pad2d_xpu", XPUKernelSet({FLOAT32})},
      {"roformer_relative_embedding_xpu", XPUKernelSet({FLOAT16, FLOAT32})},
      {"cross_attention_xpu", XPUKernelSet({FLOAT32, FLOAT16})},
      {"variable_length_memory_efficient_attention",
       XPUKernelSet({FLOAT16, FLOAT32})},
      {"flash_attn_unpadded", XPUKernelSet({FLOAT16, FLOAT32})},
      {"mask_adaptive_xpu", XPUKernelSet({FLOAT16, FLOAT32})},
      {"sequence_unpad_xpu", XPUKernelSet({FLOAT16, FLOAT32})},
      {"block_multihead_attention_xpu", XPUKernelSet({FLOAT16})},
      {"blha_get_max_len", XPUKernelSet({INT32, INT64})},
  };

  return s_xpu2_kernels;
}

}  // namespace xpu
}  // namespace backends
}  // namespace phi
#endif
