/* Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License. */

#ifdef PADDLE_WITH_XPU
#include <string>
#include <unordered_map>
#include <unordered_set>
#include "paddle/phi/backends/xpu/xpu_op_list.h"

namespace phi {
namespace backends {
namespace xpu {

XPUOpMap& get_kl3_ops() {
  // KL3支持的op，通过op_name, data_type, place来索引
  static XPUOpMap s_xpu3_kernels{
      {"acos", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"add_act_xpu", XPUKernelSet({FLOAT32, FLOAT16})},
      {"add_layernorm_xpu", XPUKernelSet({FLOAT32, FLOAT16})},
      {"abs", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"abs_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"accuracy", XPUKernelSet({FLOAT32, FLOAT16})},
      {"adadelta", XPUKernelSet({FLOAT32})},
      {"adamw", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"adam", XPUKernelSet({FLOAT32, FLOAT16})},
      {"adagrad", XPUKernelSet({FLOAT32})},
      {"addcmul_xpu", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"addmm", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"addmm_grad", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"arange_tensor",
       XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16, INT32, INT64})},
      {"all_gather",
       XPUKernelSet({INT32, INT64, BOOL, UINT8, FLOAT32, FLOAT16, BFLOAT16})},
      {"all_reduce", XPUKernelSet({INT32, INT64, FLOAT32, FLOAT16, BFLOAT16})},
      {"all_to_all",
       XPUKernelSet({INT32, INT64, BOOL, UINT8, FLOAT32, FLOAT16, BFLOAT16})},
      {"arg_max", XPUKernelSet({INT32, INT64, FLOAT32, FLOAT16, BFLOAT16})},
      {"arg_min", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"argsort_grad", XPUKernelSet({INT32, INT64, FLOAT32})},
      {"argsort", XPUKernelSet({INT32, INT64, FLOAT16, FLOAT32})},
      {"array_pop",
       XPUKernelSet({FLOAT32, FLOAT64, INT32, FLOAT16, BFLOAT16, INT64, BOOL})},
      {"array_read",
       XPUKernelSet({FLOAT32, FLOAT64, INT32, FLOAT16, BFLOAT16, INT64, BOOL})},
      {"array_to_tensor",
       XPUKernelSet({FLOAT32, FLOAT64, INT32, FLOAT16, BFLOAT16, INT64, BOOL})},
      {"array_write",
       XPUKernelSet({FLOAT32, FLOAT64, INT32, FLOAT16, BFLOAT16, INT64, BOOL})},
      {"assign",
       XPUKernelSet({FLOAT32,
                     FLOAT64,
                     INT32,
                     FLOAT16,
                     BFLOAT16,
                     INT64,
                     BOOL,
                     COMPLEX64})},
      {"assign_raw",
       XPUKernelSet({FLOAT32, FLOAT64, INT32, FLOAT16, BFLOAT16, INT64, BOOL})},
      {"assign_value",
       XPUKernelSet({FLOAT32,
                     FLOAT64,
                     INT32,
                     INT64,
                     FLOAT16,
                     BFLOAT16,
                     BOOL,
                     COMPLEX64})},
      {"atan", XPUKernelSet({FLOAT32, FLOAT16})},
      {"atan_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"batch_norm_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"barrier", XPUKernelSet({INT32})},
      {"batch_norm", XPUKernelSet({FLOAT32, FLOAT16})},
      {"bn_act_xpu", XPUKernelSet({FLOAT32, FLOAT16})},
      {"bmm", XPUKernelSet({FLOAT32, FLOAT16})},
      {"bmm_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"bce_loss_grad", XPUKernelSet({FLOAT32})},
      {"beam_search", XPUKernelSet({FLOAT32, FLOAT64, INT32, INT64})},
      {"beam_search_decode",
       XPUKernelSet({FLOAT32, FLOAT64, FLOAT16, INT32, INT64})},
      {"bilinear_interp_v2", XPUKernelSet({FLOAT32, FLOAT16})},
      {"bilinear_interp_v2_grad", XPUKernelSet({FLOAT32})},
      {"bicubic_interp_v2",
       XPUKernelSet({phi::DataType::FLOAT32, phi::DataType::FLOAT16})},
      {"bitwise_not", XPUKernelSet({BOOL})},
      {"bitwise_and", XPUKernelSet({BOOL})},
      {"bitwise_or", XPUKernelSet({BOOL})},
      {"broadcast",
       XPUKernelSet({INT32, INT64, BOOL, UINT8, FLOAT32, FLOAT16, BFLOAT16})},
      {"c_alltoall",
       XPUKernelSet({FLOAT16, FLOAT32, FLOAT64, INT32, INT64, UINT8, BOOL})},
      {"c_allreduce_max", XPUKernelSet({FLOAT16, FLOAT32, INT32})},
      {"c_allreduce_sum", XPUKernelSet({FLOAT16, FLOAT32, INT32})},
      {"c_broadcast", XPUKernelSet({FLOAT16, FLOAT32, FLOAT64, INT32, INT64})},
      {"c_concat", XPUKernelSet({FLOAT16, BFLOAT16, FLOAT32, INT32, INT64})},
      {"c_embedding", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"c_embedding_grad", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"c_identity",
       XPUKernelSet({FLOAT16, FLOAT32, FLOAT64, BFLOAT16, INT32, INT64})},
      {"c_softmax_with_cross_entropy", XPUKernelSet({FLOAT32, BFLOAT16})},
      {"c_softmax_with_cross_entropy_grad", XPUKernelSet({FLOAT32, BFLOAT16})},
      {"c_reduce_sum", XPUKernelSet({FLOAT32})},
      {"c_split", XPUKernelSet({FLOAT16, FLOAT32, BFLOAT16, INT32})},
      {"c_sync_calc_stream",
       XPUKernelSet({FLOAT16, FLOAT32, BFLOAT16, FLOAT64, INT32, INT64})},
      {"c_sync_comm_stream",
       XPUKernelSet({FLOAT16, FLOAT32, BFLOAT16, FLOAT64, INT32, INT64})},
      {"cast",
       XPUKernelSet({FLOAT32,
                     FLOAT16,
                     BFLOAT16,
#ifdef PADDLE_WITH_XPU_FFT
                     COMPLEX64,
#endif
                     FLOAT64,
                     BOOL,
                     INT8,
                     UINT8,
                     INT16,
                     INT64,
                     INT32})},
      {"check_finite_and_unscale", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"clip", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16, INT64, INT32})},
      {"clip_by_norm", XPUKernelSet({FLOAT32})},
      {"clip_grad", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16, INT64, INT32})},
      {"coalesce_tensor", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"concat_grad", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"concat",
       XPUKernelSet({FLOAT32,
                     FLOAT16,
                     BFLOAT16,
                     FLOAT64,
                     BOOL,
                     UINT8,
                     INT8,
                     INT16,
                     INT32,
                     INT64,
                     COMPLEX64})},
      {"conv2d_grad", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"conv2d", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"conv1d_xpu", XPUKernelSet({FLOAT32, FLOAT16})},
      {"conv2d_xpu", XPUKernelSet({FLOAT32, FLOAT16})},
      {"conv3d_grad", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"conv3d", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"conv3d_transpose", XPUKernelSet({FLOAT32, FLOAT16})},
      {"conv2d_transpose_grad", XPUKernelSet({FLOAT32})},
      {"conv2d_transpose", XPUKernelSet({FLOAT32, FLOAT16})},
      {"conv2d_transpose_xpu", XPUKernelSet({FLOAT32, FLOAT16})},
      {"create_array",
       XPUKernelSet({FLOAT32, FLOAT64, INT32, FLOAT16, BFLOAT16, INT64, BOOL})},
      {"create_array_like",
       XPUKernelSet({FLOAT32, FLOAT64, INT32, FLOAT16, BFLOAT16, INT64, BOOL})},
      {"cumsum", XPUKernelSet({FLOAT32, FLOAT16, INT32, INT64, BFLOAT16})},
      {"cumsum_grad", XPUKernelSet({FLOAT32, INT32, INT64})},
      {"cumprod", XPUKernelSet({FLOAT32, INT32, INT64})},
      {"deformable_conv_grad", XPUKernelSet({FLOAT32})},
      {"deformable_conv_v1_grad", XPUKernelSet({FLOAT32})},
      {"deformable_conv_v1", XPUKernelSet({FLOAT32})},
      {"depthwise_conv2d_grad", XPUKernelSet({FLOAT32})},
      {"depthwise_conv2d", XPUKernelSet({FLOAT32, FLOAT16})},
      {"depthwise_conv2d_transpose_grad", XPUKernelSet({FLOAT32})},
      {"depthwise_conv2d_transpose", XPUKernelSet({FLOAT32, FLOAT16})},
      {"dequantize_linear", XPUKernelSet({FLOAT32})},
      {"dequantize_linear_deprecated", XPUKernelSet({FLOAT32})},
      {"diag_v2", XPUKernelSet({FLOAT32, FLOAT16, INT32, INT64})},
      {"diagonal", XPUKernelSet({INT64, INT32, BOOL, FLOAT16, FLOAT32})},
      {"dropout_grad", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"dropout", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"einsum", XPUKernelSet({FLOAT32})},
      {"einsum_grad", XPUKernelSet({FLOAT32})},
      {"elementwise_add_grad",
       XPUKernelSet({FLOAT32,
                     FLOAT16,
                     BFLOAT16,
#ifdef PADDLE_WITH_XPU_FFT
                     COMPLEX64,
#endif
                     INT64,
                     INT32})},
      {"elementwise_add",
       XPUKernelSet({FLOAT64,
                     FLOAT32,
                     FLOAT16,
                     BFLOAT16,
#ifdef PADDLE_WITH_XPU_FFT
                     COMPLEX64,
#endif
                     INT64,
                     INT32})},
      {"elementwise_div_grad", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"elementwise_div",
       XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16, INT64, INT32})},
      {"elementwise_floordiv",
       XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16, INT64, INT32})},
      {"elementwise_max_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"elementwise_max",
       XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16, INT32, INT64})},
      {"elementwise_min_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"elementwise_min",
       XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16, INT32, INT64})},
      {"elementwise_mul_grad",
       XPUKernelSet({FLOAT32,
                     FLOAT16,
#ifdef PADDLE_WITH_XPU_FFT
                     COMPLEX64,
#endif
                     BFLOAT16,
                     INT64})},
      {"elementwise_mul",
       XPUKernelSet({BOOL,
                     FLOAT32,
                     FLOAT16,
                     BFLOAT16,
#ifdef PADDLE_WITH_XPU_FFT
                     COMPLEX64,
#endif
                     INT32,
                     INT64})},
      {"elementwise_pow", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"elementwise_sub_grad", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"elementwise_sub",
       XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16, INT32, INT64})},
      {"elementwise_mod",
       XPUKernelSet({FLOAT32,
                     FLOAT16,
#ifdef PADDLE_WITH_XPU_FFT
                     COMPLEX64,
#endif
                     INT64,
                     INT32})},
      {"embedding_with_eltwise_add_xpu", XPUKernelSet({FLOAT32, FLOAT16})},
      {"empty",
       XPUKernelSet({INT64,
                     INT32,
                     INT16,
                     INT8,
                     UINT8,
                     BOOL,
                     FLOAT16,
                     FLOAT32,
                     FLOAT64,
                     BFLOAT16})},
      {"empty_like",
       XPUKernelSet({INT64,
                     INT32,
                     INT16,
                     INT8,
                     UINT8,
                     BOOL,
                     FLOAT16,
                     FLOAT32,
                     FLOAT64,
                     BFLOAT16})},
      {"embedding_grad", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"equal", XPUKernelSet({INT64, INT32, FLOAT16, BFLOAT16, FLOAT32, BOOL})},
      {"exp_grad", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"exp", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"round", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"expand_as_v2",
       XPUKernelSet({INT32, INT64, BOOL, BFLOAT16, FLOAT16, FLOAT32, FLOAT64})},
      {"expand_v2",
       XPUKernelSet({INT32, INT64, BOOL, FLOAT16, FLOAT32, BFLOAT16, FLOAT64})},
      {"fast_where_xpu", XPUKernelSet({INT32, FLOAT32, FLOAT16})},
      {"layer_norm_act_xpu", XPUKernelSet({FLOAT32, FLOAT16})},
      {"fast_layernorm_xpu", XPUKernelSet({FLOAT32, FLOAT16})},
      {"fc_xpu", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"fill",
       XPUKernelSet({INT64, INT32, FLOAT16, BOOL, BFLOAT16, FLOAT64, FLOAT32})},
      {"fill_any",
       XPUKernelSet({INT64, INT32, FLOAT16, BOOL, BFLOAT16, FLOAT64, FLOAT32})},
      {"fill_any_like",
       XPUKernelSet({INT64, INT32, BOOL, FLOAT16, FLOAT64, BFLOAT16, FLOAT32})},
      {"fill_diagonal_tensor",
       XPUKernelSet({INT64, INT32, BOOL, FLOAT16, FLOAT32})},
      {"fill_constant",
       XPUKernelSet({INT64,
                     INT32,
                     INT16,
                     INT8,
                     UINT8,
                     BOOL,
                     FLOAT32,
                     FLOAT64,
                     FLOAT16,
                     BFLOAT16})},
      {"fill_constant_batch_size_like",
       XPUKernelSet({INT64, INT32, FLOAT32, FLOAT16, BFLOAT16})},
      {"flash_attn_grad", XPUKernelSet({BFLOAT16, FLOAT32, FLOAT16})},
      {"flash_attn_unpadded_grad", XPUKernelSet({BFLOAT16, FLOAT32, FLOAT16})},
      {"flash_attn", XPUKernelSet({BFLOAT16, FLOAT32, FLOAT16})},
      {"flashmask_attention", XPUKernelSet({BFLOAT16, FLOAT16})},
      {"flashmask_attention_grad", XPUKernelSet({BFLOAT16, FLOAT16})},
      {"flash_attn_unpadded", XPUKernelSet({BFLOAT16, FLOAT32, FLOAT16})},
      {"flatten2_grad",
       XPUKernelSet({FLOAT32,
                     INT64,
                     INT32,
                     FLOAT16,
                     BFLOAT16,
                     UINT8,
                     INT8,
                     INT16,
                     FLOAT64,
                     BOOL})},
      {"flatten2",
       XPUKernelSet({FLOAT32,
                     INT64,
                     INT32,
                     FLOAT16,
                     BFLOAT16,
                     UINT8,
                     INT8,
                     INT16,
                     FLOAT64,
                     BOOL})},
      {"flatten_contiguous_range_grad",
       XPUKernelSet({FLOAT32,
                     INT64,
                     INT32,
                     FLOAT16,
                     BFLOAT16,
                     UINT8,
                     INT8,
                     INT16,
                     FLOAT64,
                     BOOL})},
      {"flatten_contiguous_range",
       XPUKernelSet({FLOAT32,
                     INT64,
                     INT32,
                     FLOAT16,
                     BFLOAT16,
                     UINT8,
                     INT8,
                     INT16,
                     FLOAT64,
                     BOOL})},
      {"flatten_grad",
       XPUKernelSet({FLOAT32,
                     INT64,
                     INT32,
                     FLOAT16,
                     BFLOAT16,
                     UINT8,
                     INT8,
                     INT16,
                     FLOAT64,
                     BOOL})},
      {"flatten",
       XPUKernelSet({FLOAT32,
                     INT64,
                     INT32,
                     FLOAT16,
                     BFLOAT16,
                     UINT8,
                     INT8,
                     INT16,
                     FLOAT64,
                     BOOL})},
      {"flip", XPUKernelSet({FLOAT32})},
      {"full",
       XPUKernelSet({INT64, INT32, FLOAT64, FLOAT16, FLOAT32, BFLOAT16})},
      {"full_batch_size_like",
       XPUKernelSet({INT64, INT32, FLOAT32, FLOAT16, BFLOAT16})},
      {"full_like",
       XPUKernelSet({INT64, INT32, FLOAT32, FLOAT64, FLOAT16, BFLOAT16})},
      {"full_batch_size_like",
       XPUKernelSet({INT64, INT32, FLOAT32, FLOAT16, BFLOAT16})},
      {"fused_multi_transformer_xpu", XPUKernelSet({FLOAT32, FLOAT16})},
      {"fused_rotary_position_embedding",
       XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"fused_rotary_position_embedding_grad",
       XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"unfold", XPUKernelSet({FLOAT32, FLOAT16})},
      {"unfold_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"floor", XPUKernelSet({FLOAT32})},
      {"ceil", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"gather_grad",
       XPUKernelSet(
           {FLOAT32, FLOAT16, BFLOAT16, INT8, INT16, INT32, INT64, BOOL})},
      {"gather_nd_grad",
       XPUKernelSet({INT32, INT64, FLOAT32, FLOAT16, BFLOAT16})},
      {"gather_nd", XPUKernelSet({INT32, INT64, FLOAT32, FLOAT16, BFLOAT16})},
      {"gather",
       XPUKernelSet(
           {FLOAT32, FLOAT16, BFLOAT16, INT8, INT16, INT32, INT64, BOOL})},
      {"gaussian_random", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"gaussian_inplace", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"gelu_grad", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"gelu", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"generate_sequence_xpu",
       XPUKernelSet({
           FLOAT32,
           INT32,
           INT64,
       })},
      {"grad_add", XPUKernelSet({FLOAT32, FLOAT16})},
      {"greater_equal",
       XPUKernelSet({INT64, INT32, FLOAT16, BFLOAT16, FLOAT32})},
      {"greater_than",
       XPUKernelSet({INT64, INT32, FLOAT16, BFLOAT16, FLOAT32})},
      {"grid_sampler", XPUKernelSet({FLOAT32})},
      {"grid_sampler_grad", XPUKernelSet({FLOAT32})},
      {"group_norm_silu_xpu", XPUKernelSet({FLOAT32, FLOAT16})},
      {"hard_sigmoid_grad", XPUKernelSet({FLOAT32})},
      {"hard_sigmoid", XPUKernelSet({FLOAT32, FLOAT16})},
      {"hard_swish_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"hard_swish", XPUKernelSet({FLOAT32})},
      {"huber_loss_grad", XPUKernelSet({FLOAT32})},
      {"huber_loss", XPUKernelSet({FLOAT32})},
      {"kldiv_loss", XPUKernelSet({FLOAT32})},
      {"kldiv_loss_grad", XPUKernelSet({FLOAT32})},
      {"increment", XPUKernelSet({FLOAT32, INT32, INT64})},
      {"index_elementwise_get",
       XPUKernelSet({BOOL,
                     INT32,
                     INT8,
                     UINT8,
                     INT64,
                     FLOAT32,
                     FLOAT64,
                     FLOAT16,
                     BFLOAT16,
                     FLOAT64})},
      {"index_elementwise_get_grad",
       XPUKernelSet({INT32, FLOAT32, FLOAT16, BFLOAT16})},
      {"index_elementwise_put",
       XPUKernelSet({BOOL,
                     INT32,
                     INT8,
                     UINT8,
                     INT64,
                     FLOAT32,
                     FLOAT64,
                     FLOAT16,
                     BFLOAT16,
                     FLOAT64})},
      {"index_elementwise_put_with_tensor",
       XPUKernelSet({BOOL,
                     INT32,
                     INT8,
                     UINT8,
                     INT64,
                     FLOAT32,
                     FLOAT64,
                     FLOAT16,
                     BFLOAT16,
                     FLOAT64})},
      {"index_elementwise_put_grad",
       XPUKernelSet({BOOL,
                     INT32,
                     INT8,
                     UINT8,
                     INT64,
                     FLOAT32,
                     FLOAT64,
                     FLOAT16,
                     BFLOAT16,
                     FLOAT64})},
      {"index_elementwise_put_with_tensor_grad",
       XPUKernelSet({BOOL,
                     INT32,
                     INT8,
                     UINT8,
                     INT64,
                     FLOAT32,
                     FLOAT64,
                     FLOAT16,
                     BFLOAT16,
                     FLOAT64})},
      {"index_put", XPUKernelSet({FLOAT32, INT32, FLOAT16, BFLOAT16, INT64})},
      {"index_put_grad",
       XPUKernelSet({FLOAT32, INT32, FLOAT16, BFLOAT16, INT64})},
      {"index_sample_grad", XPUKernelSet({FLOAT32})},
      {"index_sample",
       XPUKernelSet({INT8, INT16, INT32, BFLOAT16, FLOAT16, FLOAT32, BOOL})},
      {"index_select_grad", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"index_select",
       XPUKernelSet({FLOAT32, INT32, FLOAT16, BFLOAT16, INT64})},
      {"index_add", XPUKernelSet({FLOAT32, INT32, INT64, FLOAT16, BFLOAT16})},
      {"index_add_grad",
       XPUKernelSet({FLOAT32, INT32, INT64, FLOAT16, BFLOAT16})},
      {"instance_norm", XPUKernelSet({FLOAT32, FLOAT16})},
      {"instance_norm_grad", XPUKernelSet({FLOAT32})},
      {"inverse", XPUKernelSet({FLOAT32, FLOAT64})},
      {"label_smooth", XPUKernelSet({FLOAT32})},
      {"layer_norm_grad", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"layer_norm", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"leaky_relu_grad", XPUKernelSet({FLOAT32})},
      {"leaky_relu", XPUKernelSet({FLOAT32, FLOAT16})},
      {"less_equal", XPUKernelSet({INT64, INT32, FLOAT16, BFLOAT16, FLOAT32})},
      {"less_than", XPUKernelSet({INT64, INT32, FLOAT16, BFLOAT16, FLOAT32})},
      {"load", XPUKernelSet({FLOAT32})},
      {"load_combine", XPUKernelSet({FLOAT32, FLOAT64, INT8, INT32, INT64})},
      {"log", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"log_grad", XPUKernelSet({FLOAT32})},
      {"log_softmax", XPUKernelSet({FLOAT32})},
      {"log_softmax_grad", XPUKernelSet({FLOAT32})},
      {"logical_and", XPUKernelSet({BOOL})},
      {"logical_not", XPUKernelSet({BOOL})},
      {"logical_or", XPUKernelSet({BOOL})},
      {"logical_xor", XPUKernelSet({BOOL})},
      {"logsumexp", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"logsumexp_grad", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"lookup_table_v2_grad", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"lookup_table_v2", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"masked_fill_grad", XPUKernelSet({FLOAT32, INT64, FLOAT16, BFLOAT16})},
      {"masked_select",
       XPUKernelSet({INT32, INT64, FLOAT16, BFLOAT16, FLOAT32})},
      {"masked_select_grad",
       XPUKernelSet({INT32, INT64, BOOL, FLOAT16, BFLOAT16, FLOAT32})},
      {"masked_fill",
       XPUKernelSet({FLOAT32, INT32, INT8, INT64, UINT8, FLOAT16, BFLOAT16})},
      {"max_pool2d_with_index", XPUKernelSet({FLOAT32, FLOAT16})},
      {"max_pool2d_with_index_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"matmul_grad", XPUKernelSet({FLOAT32, BFLOAT16, FLOAT16})},
      {"matmul_v2_grad", XPUKernelSet({FLOAT32, BFLOAT16, FLOAT16})},
      {"matmul_v2", XPUKernelSet({FLOAT32, BFLOAT16, FLOAT16})},
      {"matmul", XPUKernelSet({FLOAT32, BFLOAT16, FLOAT16})},
      {"batched_gemm", XPUKernelSet({FLOAT32, BFLOAT16})},
      {"mean_grad", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"mean", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"merged_momentum", XPUKernelSet({FLOAT32, FLOAT16})},
      {"momentum", XPUKernelSet({FLOAT32, FLOAT16})},
      {"mul", XPUKernelSet({FLOAT32, FLOAT16})},
      {"mul_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"multiply",
       XPUKernelSet({BOOL, FLOAT32, FLOAT16, BFLOAT16, INT32, INT64})},
      {"multi_encoder_xpu", XPUKernelSet({FLOAT32, FLOAT16})},
      {"multiclass_nms3", XPUKernelSet({FLOAT32})},
      {"multinomial", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"nearest_interp_v2", XPUKernelSet({FLOAT32, FLOAT16, INT64})},
      {"nearest_interp_v2_grad", XPUKernelSet({FLOAT32})},
      {"nll_loss", XPUKernelSet({FLOAT32})},
      {"nll_loss_grad", XPUKernelSet({FLOAT32})},
      {"nop", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"norm",
       XPUKernelSet({
           FLOAT32,
           FLOAT16,
       })},
      {"not_equal", XPUKernelSet({INT64, INT32, FLOAT16, BFLOAT16, FLOAT32})},
      {"one_hot", XPUKernelSet({INT32, INT64})},
      {"one_hot_v2", XPUKernelSet({INT32, INT64})},
      {"p_norm", XPUKernelSet({FLOAT32})},
      {"p_norm_grad", XPUKernelSet({FLOAT32})},
      {"p_recv",
       XPUKernelSet({
           FLOAT32,
           FLOAT16,
           BFLOAT16,
           FLOAT64,
           INT32,
           INT64,
           UINT8,
       })},
      {"p_recv_array",
       XPUKernelSet({
           FLOAT32,
           FLOAT16,
           BFLOAT16,
           FLOAT64,
           INT32,
           INT64,
           UINT8,
       })},
      {"p_send",
       XPUKernelSet({
           FLOAT32,
           FLOAT16,
           BFLOAT16,
           FLOAT64,
           INT32,
           INT64,
           UINT8,
       })},
      {"p_send_array",
       XPUKernelSet({
           FLOAT32,
           FLOAT16,
           BFLOAT16,
           FLOAT64,
           INT32,
           INT64,
           UINT8,
       })},
      {"pad3d_grad", XPUKernelSet({FLOAT32})},
      {"pad3d", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"pad",
       XPUKernelSet({FLOAT32,
                     INT32,
                     INT16,
                     INT64,
#ifdef PADDLE_WITH_XPU_FFT
                     COMPLEX64,
#endif
                     BFLOAT16,
                     FLOAT16})},
      {"pad_grad",
       XPUKernelSet({FLOAT32,
                     INT32,
                     INT16,
                     INT64,
#ifdef PADDLE_WITH_XPU_FFT
                     COMPLEX64,
#endif
                     BFLOAT16,
                     FLOAT16})},
      {"pixel_shuffle", XPUKernelSet({FLOAT32})},
      {"pixel_shuffle_grad", XPUKernelSet({FLOAT32})},
      {"pool2d_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"pool2d", XPUKernelSet({FLOAT32, FLOAT16})},
      {"pool3d_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"pool3d", XPUKernelSet({FLOAT32, FLOAT16})},
      {"pow", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"pow_grad", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"pow2_decay_with_linear_warmup", XPUKernelSet({FLOAT32})},
      {"prior_box", XPUKernelSet({FLOAT32})},
      {"prelu", XPUKernelSet({FLOAT32, FLOAT16})},
      {"prelu_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"prod_raw", XPUKernelSet({FLOAT32})},
      {"put_along_axis",
       XPUKernelSet({FLOAT32, INT32, INT64, BFLOAT16, FLOAT16})},
      {"quantize_linear_deprecated_infer", XPUKernelSet({FLOAT32})},
      {"quantize_linear", XPUKernelSet({FLOAT32})},
      {"range", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16, INT64, INT32})},
      {"randperm", XPUKernelSet({INT32, INT64, FLOAT32, FLOAT64})},
      {"reciprocal", XPUKernelSet({FLOAT32})},
      {"reciprocal_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"reduce_all", XPUKernelSet({BOOL})},
      {"reduce_any", XPUKernelSet({FLOAT32, INT32, INT64, BOOL})},
      {"reduce_max_grad",
       XPUKernelSet({
           FLOAT32,
           FLOAT16,
           BFLOAT16,
       })},
      {"reduce_max", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16, INT32, INT64})},
      {"reduce_mean_grad", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"reduce_mean",
       XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16, INT32, INT64, BOOL})},
      {"reduce_min_grad", XPUKernelSet({FLOAT32})},
      {"reduce_min",
       XPUKernelSet({
           FLOAT32,
           FLOAT16,
           BFLOAT16,
           INT32,
           INT64,
       })},
      {"reduce_prod", XPUKernelSet({FLOAT32, INT32, INT64})},
      {"reduce_scatter",
       XPUKernelSet({INT32, INT64, BOOL, UINT8, FLOAT32, FLOAT16, BFLOAT16})},
      {"reduce_sum_grad",
       XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16, INT64, INT32, BOOL})},
      {"reduce_sum",
       XPUKernelSet({FLOAT16, INT64, INT32, INT8, FLOAT32, BFLOAT16, BOOL})},
      {"relu6", XPUKernelSet({FLOAT32, FLOAT16})},
      {"relu6_grad", XPUKernelSet({FLOAT32})},
      {"relu_grad", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"relu", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"reshape2_grad",
       XPUKernelSet({FLOAT64,
                     FLOAT16,
                     BFLOAT16,
                     INT64,
                     INT32,
                     BOOL,
                     FLOAT32,
                     COMPLEX64})},
      {"reshape2",
       XPUKernelSet({FLOAT64,
                     FLOAT16,
                     BFLOAT16,
                     INT64,
                     INT32,
                     BOOL,
                     FLOAT32,
                     COMPLEX64})},
      {"reshape",
       XPUKernelSet({FLOAT64,
                     FLOAT16,
                     INT64,
                     INT32,
                     BFLOAT16,
                     BOOL,
                     FLOAT32,
                     COMPLEX64})},
      {"resnet_unit", XPUKernelSet({FLOAT16, FLOAT32})},
      {"resnet_unit_grad", XPUKernelSet({FLOAT16, FLOAT32})},
      {"repeat_interleave",
       XPUKernelSet({FLOAT32, INT32, INT64, BFLOAT16, FLOAT16})},
      {"repeat_interleave_with_tensor_index",
       XPUKernelSet({FLOAT32, INT32, INT64, BFLOAT16})},
      {"fused_rms_norm_quant", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"fused_rms_norm_quant_grad", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"rnn_grad", XPUKernelSet({FLOAT32})},
      {"roi_align", XPUKernelSet({FLOAT32})},
      {"roi_align_grad", XPUKernelSet({FLOAT32})},
      {"roll", XPUKernelSet({FLOAT32})},
      {"roll_grad", XPUKernelSet({FLOAT32})},
      {"rsqrt", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"rsqrt_grad", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"save",
       XPUKernelSet(
           {FLOAT32, FLOAT64, INT32, UINT8, INT8, INT64, FLOAT16, BFLOAT16})},
      {"scale",
       XPUKernelSet(
           {FLOAT32, FLOAT16, BFLOAT16, INT64, INT32, INT16, UINT8, INT8})},
      {"scatter", XPUKernelSet({INT64, INT32, FLOAT16, BFLOAT16, FLOAT32})},
      {"scatter_grad", XPUKernelSet({FLOAT16, BFLOAT16, FLOAT32})},
      {"scatter_nd_add",
       XPUKernelSet({FLOAT16, BFLOAT16, FLOAT32, INT32, INT64})},
      {"scatter_nd_add_grad",
       XPUKernelSet({FLOAT16, BFLOAT16, FLOAT32, INT32, INT64})},
      {"set_value",
       XPUKernelSet({FLOAT32, INT32, INT64, FLOAT16, BOOL, BFLOAT16})},
      {"set_value_with_tensor",
       XPUKernelSet(
           {FLOAT32, FLOAT16, BFLOAT16, INT32, INT64, BOOL, BFLOAT16})},
      {"set_value_grad",
       XPUKernelSet({FLOAT32, INT32, INT64, BFLOAT16, FLOAT16})},
      {"sgd", XPUKernelSet({FLOAT32, FLOAT16})},
      {"silu_grad", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"silu", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"size",
       XPUKernelSet({INT64,
                     INT32,
                     INT16,
                     UINT8,
                     BOOL,
                     FLOAT16,
                     FLOAT64,
                     BFLOAT16,
                     FLOAT32})},
      {"sigmoid_cross_entropy_with_logits_grad", XPUKernelSet({FLOAT32})},
      {"sigmoid_cross_entropy_with_logits", XPUKernelSet({FLOAT32})},
      {"share_data",
       XPUKernelSet({BOOL,
                     INT32,
                     INT8,
                     UINT8,
                     INT64,
                     FLOAT32,
                     FLOAT64,
                     FLOAT16,
                     BFLOAT16})},
      {"shape", XPUKernelSet({FLOAT32, INT64, INT32, FLOAT16, BFLOAT16})},
      {"shape64", XPUKernelSet({FLOAT32, INT64, INT32, FLOAT16, BFLOAT16})},
      {"sigmoid", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"sigmoid_grad", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"sign", XPUKernelSet({FLOAT32, INT32, INT64})},
      {"slice_grad",
       XPUKernelSet({FLOAT32,
                     FLOAT16,
                     BFLOAT16,
#ifdef PADDLE_WITH_XPU_FFT
                     COMPLEX64,
#endif
                     INT32})},
      {"slice",
       XPUKernelSet({FLOAT32,
                     FLOAT16,
                     BFLOAT16,
#ifdef PADDLE_WITH_XPU_FFT
                     COMPLEX64,
#endif
                     FLOAT64,
                     UINT8,
                     INT8,
                     INT16,
                     INT32,
                     INT64})},
      {"softmax", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"softmax_grad", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"fused_softmax_mask_grad", XPUKernelSet({FLOAT32})},
      {"softmax_with_cross_entropy_grad",
       XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"softmax_with_cross_entropy",
       XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"sparse_coo_tensor",
       XPUKernelSet({FLOAT64, INT64, INT32, UINT8, INT16, FLOAT32, FLOAT16})},
      {"split", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16, INT32, INT64})},
      {"split_with_num",
       XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16, INT32, INT64})},
      {"sqrt",
       XPUKernelSet({
           FLOAT32,
           FLOAT16,
           BFLOAT16,
       })},
      {"sqrt_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"square_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"square", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"squared_l2_norm", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"squared_l2_norm_grad", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"squeeze2_grad",
       XPUKernelSet({FLOAT64,
                     INT64,
                     INT32,
                     BOOL,
                     INT8,
                     UINT8,
                     FLOAT16,
                     BFLOAT16,
                     FLOAT32})},
      {"squeeze2",
       XPUKernelSet({FLOAT64,
                     INT64,
                     INT32,
                     BOOL,
                     INT8,
                     UINT8,
                     FLOAT16,
                     BFLOAT16,
                     FLOAT32})},
      {"squeeze",
       XPUKernelSet({FLOAT64,
                     INT64,
                     INT32,
                     BOOL,
                     INT8,
                     UINT8,
                     FLOAT16,
                     BFLOAT16,
                     FLOAT32})},
      {"squeeze_grad",
       XPUKernelSet({FLOAT64,
                     INT64,
                     INT32,
                     BOOL,
                     INT8,
                     UINT8,
                     FLOAT16,
                     BFLOAT16,
                     FLOAT32})},
      {"stack",
       XPUKernelSet({FLOAT32,
                     INT64,
                     INT32,
                     FLOAT16,
                     BFLOAT16,
                     UINT8,
                     INT8,
                     INT16,
                     BOOL,
                     FLOAT64})},
      {"stack_grad",
       XPUKernelSet(
           {FLOAT32, INT64, INT32, FLOAT16, BFLOAT16, UINT8, INT8, INT16})},
      {"strided_slice",
       XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16, INT16, INT32, INT64})},
      {"strided_slice_grad",
       XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16, INT16, INT32})},
      {"sum", XPUKernelSet({FLOAT32, BFLOAT16, FLOAT16})},
      {"swiglu", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"swiglu_grad", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"swish", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"swish_grad", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"take_along_axis", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"take_along_axis_grad", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"tanh_grad", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"tan", XPUKernelSet({FLOAT32, FLOAT16})},
      {"tanh", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"temporal_shift", XPUKernelSet({FLOAT32})},
      {"temporal_shift_grad", XPUKernelSet({FLOAT32})},
      {"tril_triu",
       XPUKernelSet({FLOAT32, INT32, INT64, FLOAT16, BFLOAT16, BOOL})},
      {"tril", XPUKernelSet({FLOAT32, INT32, INT64, FLOAT16, BFLOAT16, BOOL})},
      {"triu", XPUKernelSet({FLOAT32, INT32, INT64, FLOAT16, BFLOAT16, BOOL})},
      {"tril_triu_grad",
       XPUKernelSet({FLOAT32, INT32, INT64, FLOAT16, BFLOAT16, BOOL})},
      {"tril_grad",
       XPUKernelSet({FLOAT32, INT32, INT64, FLOAT16, BFLOAT16, BOOL})},
      {"triu_grad",
       XPUKernelSet({FLOAT32, INT32, INT64, FLOAT16, BFLOAT16, BOOL})},
      {"tile", XPUKernelSet({INT32, INT64, BOOL, FLOAT64, FLOAT32, BFLOAT16})},
      {"tile_grad", XPUKernelSet({FLOAT32, BFLOAT16})},
      {"transpose2_grad",
       XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16, INT64, INT32, BOOL})},
      {"transpose2",
       XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16, INT64, INT32, BOOL})},
      {"transpose_grad",
       XPUKernelSet({FLOAT32,
                     FLOAT16,
                     BFLOAT16,
#ifdef PADDLE_WITH_XPU_FFT
                     COMPLEX64,
#endif
                     INT64,
                     INT32,
                     BOOL})},
      {"transpose",
       XPUKernelSet({FLOAT32,
                     FLOAT16,
                     BFLOAT16,
#ifdef PADDLE_WITH_XPU_FFT
                     COMPLEX64,
#endif
                     INT64,
                     INT32,
                     BOOL})},
      {"truncated_gaussian_random", XPUKernelSet({FLOAT32})},
      {"top_k", XPUKernelSet({FLOAT32, FLOAT16})},
      {"top_k_v2", XPUKernelSet({FLOAT32, FLOAT16})},
      {"top_k_grad", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"top_k_v2_grad", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"top_p_sampling", XPUKernelSet({FLOAT32, FLOAT16})},
      {"update_loss_scaling", XPUKernelSet({FLOAT32, FLOAT16})},
      {"unbind", XPUKernelSet({FLOAT32, BFLOAT16})},
      {"uniform_random", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"unique", XPUKernelSet({FLOAT32, INT32, INT64})},
      {"unsqueeze2_grad",
       XPUKernelSet({FLOAT64,
                     INT64,
                     INT32,
                     BOOL,
                     INT8,
                     UINT8,
                     FLOAT32,
                     FLOAT16,
                     BFLOAT16})},
      {"unsqueeze2",
       XPUKernelSet({FLOAT64,
                     INT64,
                     INT32,
                     BOOL,
                     INT8,
                     UINT8,
                     FLOAT32,
                     FLOAT16,
                     BFLOAT16})},
      {"unsqueeze_grad",
       XPUKernelSet({FLOAT64,
                     INT64,
                     INT32,
                     BOOL,
                     INT8,
                     UINT8,
                     FLOAT32,
                     FLOAT16,
                     BFLOAT16})},
      {"unsqueeze",
       XPUKernelSet({FLOAT64,
                     INT64,
                     INT32,
                     BOOL,
                     INT8,
                     UINT8,
                     FLOAT32,
                     FLOAT16,
                     BFLOAT16})},
      {"unstack", XPUKernelSet({INT64, INT32, FLOAT16, FLOAT32})},
      {"unstack_grad", XPUKernelSet({INT64, INT32, FLOAT16, FLOAT32})},
      {"variable_length_memory_efficient_attention",
       XPUKernelSet({FLOAT32, FLOAT16})},
      {"view_shape",
       XPUKernelSet({BOOL,
                     INT32,
                     INT8,
                     UINT8,
                     INT64,
                     FLOAT32,
                     FLOAT64,
                     FLOAT16,
                     BFLOAT16})},
      {"view_slice",
       XPUKernelSet({BOOL,
                     INT32,
                     INT8,
                     UINT8,
                     INT64,
                     FLOAT32,
                     FLOAT64,
                     FLOAT16,
                     BFLOAT16})},
      {"warpctc_grad", XPUKernelSet({FLOAT32})},
      {"warpctc", XPUKernelSet({FLOAT32})},
      {"weight_only_linear", XPUKernelSet({FLOAT16, BFLOAT16})},
      {"where_index", XPUKernelSet({INT32, BOOL, FLOAT32, INT64})},
      {"weight_quantize", XPUKernelSet({FLOAT16, BFLOAT16})},
      {"where_grad",
       XPUKernelSet({INT32, INT64, FLOAT64, FLOAT32, FLOAT16, BFLOAT16})},
      {"where",
       XPUKernelSet({INT32, INT64, FLOAT64, FLOAT32, FLOAT16, BFLOAT16})},
      {"sin", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"sin_grad", XPUKernelSet({FLOAT32})},
      {"cos", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"cos_grad", XPUKernelSet({FLOAT32})},
      {"linspace", XPUKernelSet({FLOAT32, INT32, INT64})},
      {"randint", XPUKernelSet({INT32, INT64})},
      {"group_norm", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"group_norm_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"meshgrid", XPUKernelSet({FLOAT32, INT32, INT64})},
      {"expand_v2_grad",
       XPUKernelSet({FLOAT32, INT64, FLOAT64, BFLOAT16, FLOAT16})},
      {"eye", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"isinf_v2", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"isnan_v2", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"isfinite_v2", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"isfinite", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"yolo_box_xpu", XPUKernelSet({FLOAT32, FLOAT16})},
      {"yolo_box", XPUKernelSet({FLOAT32})},

      // AddMore
      {"sequence_unpad", XPUKernelSet({FLOAT32})},
      // Fused op
      {"squeeze_excitation_block", XPUKernelSet({FLOAT32, FLOAT16})},
      {"resnet_basic_block_grad", XPUKernelSet({FLOAT32})},
      {"resnet_basic_block", XPUKernelSet({FLOAT32})},
      {"fused_bias_act", XPUKernelSet({FLOAT16, BFLOAT16})},
      {"fused_bias_residual_layernorm",
       XPUKernelSet({FLOAT32, BFLOAT16, FLOAT16})},
      {"fused_gemm_epilogue", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"fused_gemm_epilogue_grad", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"fused_linear_param_grad_add",
       XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"fused_attention", XPUKernelSet({FLOAT32, FLOAT16})},
      {"fused_attention_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"fused_feedforward", XPUKernelSet({FLOAT32, FLOAT16})},
      {"fused_feedforward_grad", XPUKernelSet({FLOAT32, FLOAT16})},
      {"qkv_attention_xpu", XPUKernelSet({FLOAT32, FLOAT16, INT8})},
      {"lod_reset", XPUKernelSet({FLOAT32, FLOAT16, FLOAT64, INT32, INT64})},
      {"mp_allreduce_sum", XPUKernelSet({BFLOAT16, FLOAT16, FLOAT32, INT32})},
      {"expand_modality_expert_id", XPUKernelSet({INT32, INT64})},
      {"build_src_rank_and_local_expert_id", XPUKernelSet({INT32, INT64})},
      {"moe_gate_dispatch_partial_nosoftmaxtopk",
       XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"moe_gate_dispatch_partial_nosoftmaxtopk_grad",
       XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"blha_get_max_len", XPUKernelSet({INT32, INT64})},
      {"full_with_tensor",
       XPUKernelSet({FLOAT32,
                     FLOAT16,
                     BFLOAT16,
                     FLOAT64,
                     BOOL,
                     INT8,
                     UINT8,
                     INT16,
                     INT64,
                     INT32})},
      {"moe_combine", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"moe_combine_grad", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"moe_gate_dispatch", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"moe_gate_dispatch_grad", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"moe_permute", XPUKernelSet({BFLOAT16})},
      {"moe_unpermute", XPUKernelSet({BFLOAT16})},
      {"fused_rms_norm_ext", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"fused_rms_norm_ext_grad", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"rms_norm", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
      {"rms_norm_grad", XPUKernelSet({FLOAT32, FLOAT16, BFLOAT16})},
#ifdef PADDLE_WITH_XPU_FFT
      {"conj",
       XPUKernelSet({FLOAT32,
                     FLOAT16,
                     BFLOAT16,
                     FLOAT64,
                     BOOL,
                     INT64,
                     INT32,
                     COMPLEX64})},
      {"real", XPUKernelSet({COMPLEX64, COMPLEX128})},
      {"real_grad", XPUKernelSet({COMPLEX64, COMPLEX128})},
      {"imag", XPUKernelSet({COMPLEX64, COMPLEX128})},
      {"imag_grad", XPUKernelSet({COMPLEX64, COMPLEX128})},
      {"complex", XPUKernelSet({FLOAT32, FLOAT64})},
      {"complex_grad", XPUKernelSet({FLOAT32, FLOAT64})},
      {"as_complex", XPUKernelSet({FLOAT32})},
      {"as_real", XPUKernelSet({COMPLEX64})},
      {"fft_c2c", XPUKernelSet({COMPLEX64})},
      {"fft_c2r", XPUKernelSet({COMPLEX64})},
      {"fft_r2c", XPUKernelSet({FLOAT32})},
      {"fft_c2c_grad", XPUKernelSet({COMPLEX64})},
      {"fft_c2r_grad", XPUKernelSet({FLOAT32})},
      {"fft_r2c_grad", XPUKernelSet({COMPLEX64})},
      {"eig", XPUKernelSet({FLOAT32, COMPLEX64})},
      {"eig_grad", XPUKernelSet({COMPLEX64})},
#endif
  };

  return s_xpu3_kernels;
}

}  // namespace xpu
}  // namespace backends
}  // namespace phi
#endif
