version: 1.0
quantizers:
    quantizer_1:
        class: 'StaticQuantizer'
        weight_bits: 8
        activation_bits: 8
        window_size: 10000
strategies:
    strategy_1:
        class: 'QuantizationStrategy'
        quantizer: 'quantizer_1'
        start_epoch: 0
        end_epoch: 10
        dirname: 'output_static'
        target_device: 'mobile'
        save_as_int8: True
compress_pass:
    class: 'CompressPass'
    epoch: 2
    strategies:
        - strategy_1
