// Copyright (c) 2019 PaddlePaddle Authors. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baidu_paddle_lite_PaddleLiteInitializer */

#ifndef PADDLE_FLUID_LITE_API_ANDROID_JNI_NATIVE_PADDLE_INIT_JNI_H_
#define PADDLE_FLUID_LITE_API_ANDROID_JNI_NATIVE_PADDLE_INIT_JNI_H_
#ifdef __cplusplus
extern "C" {
#endif

namespace paddle {
namespace lite_api {

/*
 * Class:     com_baidu_paddle_lite_PaddleLiteInitializer
 * Method:    initNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_com_baidu_paddle_lite_PaddleLiteInitializer_initNative(JNIEnv *, jclass);

}  // namespace lite_api
}  // namespace paddle

#ifdef __cplusplus
}
#endif
#endif  // PADDLE_FLUID_LITE_API_ANDROID_JNI_NATIVE_PADDLE_INIT_JNI_H_
