# Copyright (c) 2025 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

phi_ops_yaml_legacy_static_ops = [
    ("add", ("Tensor", "x"), ("Tensor", "y")),
    ("add_n", ("Tensor[]", "inputs")),
    ("all_reduce", ("Tensor", "x"), ("int", "ring_id"), ("int", "reduce_type")),
    ("assign", ("Tensor", "x")),
    (
        "assign_value",
        ("int[]", "shape"),
        ("DataType", "dtype"),
        ("Scalar[]", "values"),
        ("Place", "place"),
    ),
    ("barrier", ("Tensor", "x"), ("int", "ring_id")),
    ("batch_fc", ("Tensor", "input"), ("Tensor", "w"), ("Tensor", "bias")),
    (
        "batch_norm",
        ("Tensor", "x"),
        ("Tensor", "mean"),
        ("Tensor", "variance"),
        ("Tensor", "scale"),
        ("Tensor", "bias"),
        ("bool", "is_test"),
        ("float", "momentum"),
        ("float", "epsilon"),
        ("str", "data_format"),
        ("bool", "use_global_stats"),
        ("bool", "trainable_statistics"),
    ),
    (
        "c_allreduce_avg",
        ("Tensor", "x"),
        ("int", "ring_id"),
        ("bool", "use_calc_stream"),
        ("bool", "use_model_parallel"),
    ),
    (
        "c_embedding",
        ("Tensor", "weight"),
        ("Tensor", "x"),
        ("int64_t", "start_index"),
        ("int64_t", "vocab_size"),
    ),
    (
        "c_reduce_avg",
        ("Tensor", "x"),
        ("int", "ring_id"),
        ("int", "root_id"),
        ("bool", "use_calc_stream"),
    ),
    (
        "c_reduce_max",
        ("Tensor", "x"),
        ("int", "ring_id"),
        ("int", "root_id"),
        ("bool", "use_calc_stream"),
    ),
    (
        "c_reduce_min",
        ("Tensor", "x"),
        ("int", "ring_id"),
        ("int", "root_id"),
        ("bool", "use_calc_stream"),
    ),
    (
        "c_reduce_prod",
        ("Tensor", "x"),
        ("int", "ring_id"),
        ("int", "root_id"),
        ("bool", "use_calc_stream"),
    ),
    (
        "c_reducescatter",
        ("Tensor", "x"),
        ("int", "ring_id"),
        ("int", "nranks"),
        ("bool", "use_calc_stream"),
    ),
    (
        "c_scatter",
        ("Tensor", "x"),
        ("int", "ring_id"),
        ("int", "root"),
        ("int", "nranks"),
        ("bool", "use_calc_stream"),
    ),
    (
        "c_split",
        ("Tensor", "x"),
        ("int", "rank"),
        ("int", "nranks"),
        ("int", "ring_id"),
        ("bool", "use_calc_stream"),
        ("bool", "use_model_parallel"),
    ),
    (
        "coalesce_tensor_",
        ("Tensor[]", "input"),
        ("DataType", "dtype"),
        ("bool", "copy_data"),
        ("bool", "set_constant"),
        ("bool", "persist_output"),
        ("float", "constant"),
        ("bool", "use_align"),
        ("int", "align_size"),
        ("int", "size_of_dtype"),
        ("int64_t[]", "concated_shapes"),
        ("int64_t[]", "concated_ranks"),
    ),
    (
        "dequantize_linear",
        ("Tensor", "x"),
        ("Tensor", "scale"),
        ("Tensor", "zero_point"),
        ("Tensor", "in_accum"),
        ("Tensor", "in_state"),
        ("int", "quant_axis"),
        ("int", "bit_length"),
        ("int", "round_type"),
        ("bool", "is_test"),
        ("bool", "only_observer"),
    ),
    (
        "distribute_fpn_proposals",
        ("Tensor", "fpn_rois"),
        ("Tensor", "rois_num"),
        ("int", "min_level"),
        ("int", "max_level"),
        ("int", "refer_level"),
        ("int", "refer_scale"),
        ("bool", "pixel_offset"),
    ),
    (
        "distributed_fused_lamb",
        ("Tensor[]", "param"),
        ("Tensor[]", "grad"),
        ("Tensor", "fp32_fused_param"),
        ("Tensor", "fp32_fused_grad"),
        ("Tensor", "fp16_fused_param"),
        ("Tensor", "fp16_fused_grad"),
        ("Tensor", "moment1"),
        ("Tensor", "moment2"),
        ("Tensor", "beta1pow"),
        ("Tensor", "beta2pow"),
        ("Tensor", "fused_param_offsets"),
        ("Tensor", "fp32_shard_fused_param_offsets"),
        ("Tensor", "fp16_shard_fused_param_offsets"),
        ("Tensor", "param_info"),
        ("Tensor", "param_order"),
        ("Tensor", "learning_rate"),
        ("Tensor", "global_scale"),
        ("float", "beta1"),
        ("float", "beta2"),
        ("float", "epsilon"),
        ("float", "max_global_grad_norm"),
        ("float", "weight_decay"),
        ("bool", "clip_after_allreduce"),
        ("int[]", "ring_ids"),
        ("int", "acc_steps"),
        ("bool", "use_master_param_norm"),
        ("bool", "use_master_acc_grad"),
        ("bool", "is_grad_scaled_by_nranks"),
        ("int64_t", "nranks"),
        ("bool", "use_hierarchical_allreduce"),
    ),
    (
        "distributed_lookup_table",
        ("Tensor[]", "ids"),
        ("Tensor", "w"),
        ("int", "table_id"),
        ("bool", "is_distributed"),
        ("str", "lookup_table_version"),
        ("int64_t", "padding_idx"),
        ("DataType", "dtype"),
        ("bool", "is_test"),
    ),
    (
        "distributed_push_sparse",
        ("Tensor[]", "ids"),
        ("Tensor[]", "shows"),
        ("Tensor[]", "clicks"),
        ("int", "table_id"),
        ("int", "size"),
        ("bool", "is_distributed"),
        ("str", "push_sparse_version"),
        ("int64_t", "padding_idx"),
        ("DataType", "dtype"),
        ("bool", "is_test"),
        ("bool", "use_cvm_op"),
    ),
    ("divide", ("Tensor", "x"), ("Tensor", "y")),
    ("einsum", ("Tensor[]", "x"), ("str", "equation")),
    ("elementwise_pow", ("Tensor", "x"), ("Tensor", "y")),
    (
        "embedding",
        ("Tensor", "x"),
        ("Tensor", "weight"),
        ("int64_t", "padding_idx"),
        ("bool", "sparse"),
    ),
    ("equal", ("Tensor", "x"), ("Tensor", "y")),
    ("feed", ("str", "name"), ("int", "col")),
    ("fetch", ("Tensor", "x"), ("str", "name"), ("int", "col")),
    ("floor_divide", ("Tensor", "x"), ("Tensor", "y")),
    (
        "fused_adam_",
        ("Tensor[]", "params"),
        ("Tensor[]", "grads"),
        ("Tensor", "learning_rate"),
        ("Tensor[]", "moments1"),
        ("Tensor[]", "moments2"),
        ("Tensor[]", "beta1_pows"),
        ("Tensor[]", "beta2_pows"),
        ("Tensor[]", "master_params"),
        ("Tensor", "skip_update"),
        ("Scalar", "beta1"),
        ("Scalar", "beta2"),
        ("Scalar", "epsilon"),
        ("int", "chunk_size"),
        ("float", "weight_decay"),
        ("bool", "use_adamw"),
        ("bool", "multi_precision"),
        ("bool", "use_global_beta_pow"),
    ),
    ("get_tensor_from_selected_rows", ("Tensor", "x")),
    (
        "global_gather",
        ("Tensor", "x"),
        ("Tensor", "local_count"),
        ("Tensor", "global_count"),
        ("int", "ring_id"),
        ("bool", "use_calc_stream"),
    ),
    (
        "global_scatter",
        ("Tensor", "x"),
        ("Tensor", "local_count"),
        ("Tensor", "global_count"),
        ("int", "ring_id"),
        ("bool", "use_calc_stream"),
    ),
    ("greater_equal", ("Tensor", "x"), ("Tensor", "y")),
    ("greater_than", ("Tensor", "x"), ("Tensor", "y")),
    ("hardswish", ("Tensor", "x")),
    ("less_equal", ("Tensor", "x"), ("Tensor", "y")),
    ("less_than", ("Tensor", "x"), ("Tensor", "y")),
    (
        "load_combine",
        ("str", "file_path"),
        ("bool", "load_as_fp16"),
        ("bool", "model_from_memory"),
    ),
    ("lod_array_length", ("Tensor[]", "x")),
    (
        "lrn",
        ("Tensor", "x"),
        ("int", "n"),
        ("float", "k"),
        ("float", "alpha"),
        ("float", "beta"),
        ("str", "data_format"),
    ),
    (
        "matmul",
        ("Tensor", "x"),
        ("Tensor", "y"),
        ("bool", "transpose_x"),
        ("bool", "transpose_y"),
    ),
    (
        "matmul_with_flatten",
        ("Tensor", "x"),
        ("Tensor", "y"),
        ("int", "x_num_col_dims"),
        ("int", "y_num_col_dims"),
    ),
    ("maximum", ("Tensor", "x"), ("Tensor", "y")),
    ("memcpy", ("Tensor", "x"), ("int", "dst_place_type")),
    ("min", ("Tensor", "x"), ("IntArray", "axis"), ("bool", "keepdim")),
    ("minimum", ("Tensor", "x"), ("Tensor", "y")),
    ("multiply", ("Tensor", "x"), ("Tensor", "y")),
    ("nop", ("Tensor", "x")),
    ("not_equal", ("Tensor", "x"), ("Tensor", "y")),
    (
        "partial_allgather",
        ("Tensor", "x"),
        ("int", "nranks"),
        ("int", "rank"),
        ("int", "ring_id"),
        ("bool", "use_calc_stream"),
    ),
    (
        "partial_recv",
        ("int", "ring_id"),
        ("int", "peer"),
        ("DataType", "dtype"),
        ("int[]", "out_shape"),
        ("bool", "use_calc_stream"),
        ("int", "num"),
        ("int", "id"),
    ),
    (
        "print",
        ("Tensor", "in"),
        ("int", "first_n"),
        ("str", "message"),
        ("int", "summarize"),
        ("bool", "print_tensor_name"),
        ("bool", "print_tensor_type"),
        ("bool", "print_tensor_shape"),
        ("bool", "print_tensor_layout"),
        ("bool", "print_tensor_lod"),
        ("str", "print_phase"),
        ("bool", "is_forward"),
    ),
    (
        "pull_box_sparse",
        ("Tensor", "w"),
        ("Tensor[]", "ids"),
        ("bool", "is_sparse"),
        ("bool", "is_distributed"),
        ("int", "size"),
    ),
    (
        "pull_gpups_sparse",
        ("Tensor", "w"),
        ("Tensor[]", "ids"),
        ("int[]", "size"),
        ("bool", "is_sparse"),
        ("bool", "is_distributed"),
    ),
    (
        "pull_sparse_v2",
        ("Tensor[]", "ids"),
        ("Tensor[]", "w"),
        ("int", "embedding_dim"),
        ("int", "table_id"),
        ("str", "accessor_class"),
        ("str", "ctr_label_name"),
        ("int", "padding_id"),
        ("bool", "scale_sparse_grad"),
        ("str[]", "input_names"),
        ("bool", "is_distributed"),
    ),
    (
        "push_dense",
        ("Tensor[]", "ids"),
        ("int", "table_id"),
        ("float", "scale_data_norm"),
        ("str[]", "input_names"),
    ),
    (
        "push_sparse_v2",
        ("Tensor[]", "ids"),
        ("Tensor[]", "w"),
        ("Tensor[]", "out_grad_in"),
        ("int", "embedding_dim"),
        ("int", "table_id"),
        ("str", "accessor_class"),
        ("str", "ctr_label_name"),
        ("int", "padding_id"),
        ("bool", "scale_sparse_grad"),
        ("str[]", "input_names"),
        ("bool", "is_distributed"),
    ),
    (
        "quantize_linear",
        ("Tensor", "x"),
        ("Tensor", "scale"),
        ("Tensor", "zero_point"),
        ("Tensor", "in_accum"),
        ("Tensor", "in_state"),
        ("int", "quant_axis"),
        ("int", "bit_length"),
        ("int", "round_type"),
        ("bool", "is_test"),
        ("bool", "only_observer"),
    ),
    (
        "recv_v2",
        ("int[]", "out_shape"),
        ("DataType", "dtype"),
        ("int", "peer"),
        ("int", "ring_id"),
        ("bool", "use_calc_stream"),
        ("bool", "dynamic_shape"),
    ),
    ("remainder", ("Tensor", "x"), ("Tensor", "y")),
    ("reshape", ("Tensor", "x"), ("IntArray", "shape")),
    ("row_conv", ("Tensor", "x"), ("Tensor", "filter")),
    (
        "save_combine",
        ("Tensor[]", "x"),
        ("str", "file_path"),
        ("bool", "overwrite"),
        ("bool", "save_as_fp16"),
        ("bool", "save_to_memory"),
    ),
    (
        "seed",
        ("int", "seed"),
        ("bool", "deterministic"),
        ("str", "rng_name"),
        ("bool", "force_cpu"),
    ),
    (
        "send_and_recv",
        ("Tensor[]", "x"),
        ("str", "message_name"),
        ("str[]", "send_var_name"),
        ("str[]", "recv_var_name"),
        ("int", "trainer_id"),
        ("str", "mode"),
        ("str[]", "endpoints"),
        ("str[]", "next_endpoints"),
        ("str[]", "previous_endpoints"),
    ),
    (
        "send_v2",
        ("Tensor", "x"),
        ("int", "ring_id"),
        ("int", "peer"),
        ("bool", "use_calc_stream"),
        ("bool", "dynamic_shape"),
    ),
    (
        "set_value",
        ("Tensor", "x"),
        ("IntArray", "starts"),
        ("IntArray", "ends"),
        ("IntArray", "steps"),
        ("int64_t[]", "axes"),
        ("int64_t[]", "decrease_axes"),
        ("int64_t[]", "none_axes"),
        ("int64_t[]", "shape"),
        ("Scalar[]", "values"),
    ),
    ("shadow_feed", ("Tensor", "x")),
    ("shadow_feed_tensors", ("Tensor[]", "x")),
    ("share_data_", ("Tensor", "x")),
    ("soft_relu", ("Tensor", "x"), ("float", "threshold")),
    ("softmax", ("Tensor", "x"), ("int", "axis")),
    ("subtract", ("Tensor", "x"), ("Tensor", "y")),
    ("tile", ("Tensor", "x"), ("IntArray", "repeat_times")),
    (
        "unique",
        ("Tensor", "x"),
        ("bool", "return_index"),
        ("bool", "return_inverse"),
        ("bool", "return_counts"),
        ("int[]", "axis"),
        ("DataType", "dtype"),
        ("bool", "is_sorted"),
    ),
    ("write_to_array", ("Tensor", "i"), ("Tensor", "x")),
    (
        "c_softmax_with_cross_entropy",
        ("Tensor", "logits"),
        ("Tensor", "label"),
        ("int64_t", "ignore_index"),
        ("int", "ring_id"),
        ("int", "rank"),
        ("int", "nranks"),
    ),
    (
        "dpsgd",
        ("Tensor", "param"),
        ("Tensor", "grad"),
        ("Tensor", "learning_rate"),
        ("float", "clip"),
        ("float", "batch_size"),
        ("float", "sigma"),
        ("int", "seed"),
    ),
    (
        "ftrl",
        ("Tensor", "param"),
        ("Tensor", "squared_accumulator"),
        ("Tensor", "linear_accumulator"),
        ("Tensor", "grad"),
        ("Tensor", "learning_rate"),
        ("float", "l1"),
        ("float", "l2"),
        ("float", "lr_power"),
    ),
    (
        "fused_attention",
        ("Tensor", "x"),
        ("Tensor", "ln_scale"),
        ("Tensor", "ln_bias"),
        ("Tensor", "qkv_weight"),
        ("Tensor", "qkv_bias"),
        ("Tensor", "cache_kv"),
        ("Tensor", "src_mask"),
        ("Tensor", "out_linear_weight"),
        ("Tensor", "out_linear_bias"),
        ("Tensor", "ln_scale_2"),
        ("Tensor", "ln_bias_2"),
        ("int", "num_heads"),
        ("bool", "transpose_qkv_wb"),
        ("bool", "pre_layer_norm"),
        ("float", "epsilon"),
        ("float", "attn_dropout_rate"),
        ("bool", "is_test"),
        ("bool", "attn_dropout_fix_seed"),
        ("int", "attn_dropout_seed"),
        ("str", "attn_dropout_implementation"),
        ("float", "dropout_rate"),
        ("bool", "dropout_fix_seed"),
        ("int", "dropout_seed"),
        ("str", "dropout_implementation"),
        ("float", "ln_epsilon"),
        ("bool", "add_residual"),
        ("int", "ring_id"),
    ),
    (
        "fused_feedforward",
        ("Tensor", "x"),
        ("Tensor", "dropout1_seed"),
        ("Tensor", "dropout2_seed"),
        ("Tensor", "linear1_weight"),
        ("Tensor", "linear1_bias"),
        ("Tensor", "linear2_weight"),
        ("Tensor", "linear2_bias"),
        ("Tensor", "ln1_scale"),
        ("Tensor", "ln1_bias"),
        ("Tensor", "ln2_scale"),
        ("Tensor", "ln2_bias"),
        ("bool", "pre_layer_norm"),
        ("float", "ln1_epsilon"),
        ("float", "ln2_epsilon"),
        ("str", "act_method"),
        ("float", "dropout1_prob"),
        ("float", "dropout2_prob"),
        ("str", "dropout1_implementation"),
        ("str", "dropout2_implementation"),
        ("bool", "is_test"),
        ("bool", "dropout1_fix_seed"),
        ("bool", "dropout2_fix_seed"),
        ("int", "dropout1_seed_val"),
        ("int", "dropout2_seed_val"),
        ("bool", "add_residual"),
        ("int", "ring_id"),
    ),
    (
        "lars_momentum",
        ("Tensor[]", "param"),
        ("Tensor[]", "grad"),
        ("Tensor[]", "velocity"),
        ("Tensor[]", "learning_rate"),
        ("Tensor[]", "master_param"),
        ("float", "mu"),
        ("float", "lars_coeff"),
        ("float[]", "lars_weight_decay"),
        ("float", "epsilon"),
        ("bool", "multi_precision"),
        ("float", "rescale_grad"),
    ),
    (
        "match_matrix_tensor",
        ("Tensor", "x"),
        ("Tensor", "y"),
        ("Tensor", "w"),
        ("int", "dim_t"),
    ),
    (
        "moving_average_abs_max_scale",
        ("Tensor", "x"),
        ("Tensor", "in_accum"),
        ("Tensor", "in_state"),
        ("float", "moving_rate"),
        ("bool", "is_test"),
    ),
    (
        "nce",
        ("Tensor", "input"),
        ("Tensor", "label"),
        ("Tensor", "weight"),
        ("Tensor", "bias"),
        ("Tensor", "sample_weight"),
        ("Tensor", "custom_dist_probs"),
        ("Tensor", "custom_dist_alias"),
        ("Tensor", "custom_dist_alias_probs"),
        ("int", "num_total_classes"),
        ("int[]", "custom_neg_classes"),
        ("int", "num_neg_samples"),
        ("int", "sampler"),
        ("int", "seed"),
        ("bool", "is_sparse"),
        ("bool", "remote_prefetch"),
        ("bool", "is_test"),
    ),
    ("onednn_to_paddle_layout", ("Tensor", "x"), ("int", "dst_layout")),
    (
        "partial_send",
        ("Tensor", "x"),
        ("int", "ring_id"),
        ("int", "peer"),
        ("bool", "use_calc_stream"),
        ("int", "num"),
        ("int", "id"),
    ),
    (
        "sparse_momentum",
        ("Tensor", "param"),
        ("Tensor", "grad"),
        ("Tensor", "velocity"),
        ("Tensor", "index"),
        ("Tensor", "learning_rate"),
        ("Tensor", "master_param"),
        ("float", "mu"),
        ("Scalar", "axis"),
        ("bool", "use_nesterov"),
        ("str", "regularization_method"),
        ("float", "regularization_coeff"),
        ("bool", "multi_precision"),
        ("float", "rescale_grad"),
    ),
]


phi_ops_yaml_ops = [
    ("abs", ("Tensor", "x")),
    ("accuracy", ("Tensor", "x"), ("Tensor", "indices"), ("Tensor", "label")),
    (
        "accuracy_check",
        ("Tensor", "x"),
        ("Tensor", "y"),
        ("str", "fn_name"),
        ("int64_t", "res_idx"),
    ),
    ("acos", ("Tensor", "x")),
    ("acosh", ("Tensor", "x")),
    (
        "adadelta_",
        ("Tensor", "param"),
        ("Tensor", "grad"),
        ("Tensor", "avg_squared_grad"),
        ("Tensor", "avg_squared_update"),
        ("Tensor", "learning_rate"),
        ("Tensor", "master_param"),
        ("float", "rho"),
        ("float", "epsilon"),
        ("bool", "multi_precision"),
    ),
    (
        "adagrad_",
        ("Tensor", "param"),
        ("Tensor", "grad"),
        ("Tensor", "moment"),
        ("Tensor", "learning_rate"),
        ("Tensor", "master_param"),
        ("float", "epsilon"),
        ("bool", "multi_precision"),
    ),
    (
        "adam_",
        ("Tensor", "param"),
        ("Tensor", "grad"),
        ("Tensor", "learning_rate"),
        ("Tensor", "moment1"),
        ("Tensor", "moment2"),
        ("Tensor", "beta1_pow"),
        ("Tensor", "beta2_pow"),
        ("Tensor", "master_param"),
        ("Tensor", "skip_update"),
        ("Scalar", "beta1"),
        ("Scalar", "beta2"),
        ("Scalar", "epsilon"),
        ("bool", "lazy_mode"),
        ("int64_t", "min_row_size_to_use_multithread"),
        ("bool", "multi_precision"),
        ("bool", "use_global_beta_pow"),
    ),
    (
        "adamax_",
        ("Tensor", "param"),
        ("Tensor", "grad"),
        ("Tensor", "learning_rate"),
        ("Tensor", "moment"),
        ("Tensor", "inf_norm"),
        ("Tensor", "beta1_pow"),
        ("Tensor", "master_param"),
        ("float", "beta1"),
        ("float", "beta2"),
        ("float", "epsilon"),
        ("bool", "multi_precision"),
    ),
    (
        "adamw_",
        ("Tensor", "param"),
        ("Tensor", "grad"),
        ("Tensor", "learning_rate"),
        ("Tensor", "moment1"),
        ("Tensor", "moment2"),
        ("Tensor", "beta1_pow"),
        ("Tensor", "beta2_pow"),
        ("Tensor", "master_param"),
        ("Tensor", "skip_update"),
        ("Scalar", "beta1"),
        ("Scalar", "beta2"),
        ("Scalar", "epsilon"),
        ("float", "lr_ratio"),
        ("float", "coeff"),
        ("bool", "with_decay"),
        ("bool", "lazy_mode"),
        ("int64_t", "min_row_size_to_use_multithread"),
        ("bool", "multi_precision"),
        ("bool", "use_global_beta_pow"),
    ),
    (
        "addmm",
        ("Tensor", "input"),
        ("Tensor", "x"),
        ("Tensor", "y"),
        ("float", "beta"),
        ("float", "alpha"),
    ),
    (
        "affine_grid",
        ("Tensor", "input"),
        ("IntArray", "output_shape"),
        ("bool", "align_corners"),
    ),
    ("all", ("Tensor", "x"), ("int64_t[]", "axis"), ("bool", "keepdim")),
    (
        "allclose",
        ("Tensor", "x"),
        ("Tensor", "y"),
        ("Scalar", "rtol"),
        ("Scalar", "atol"),
        ("bool", "equal_nan"),
    ),
    ("amax", ("Tensor", "x"), ("int64_t[]", "axis"), ("bool", "keepdim")),
    ("amin", ("Tensor", "x"), ("int64_t[]", "axis"), ("bool", "keepdim")),
    ("angle", ("Tensor", "x")),
    ("any", ("Tensor", "x"), ("int64_t[]", "axis"), ("bool", "keepdim")),
    (
        "ap_variadic",
        ("Tensor[]", "xs"),
        ("int", "num_outputs"),
        ("str", "code_module_lambda"),
        ("str", "infer_symbolic_lambda"),
        ("str", "infer_meta_lambda"),
        ("str", "kernel_dispatch_lambda"),
        ("str", "kernel_dispatch_const_data_lambda"),
    ),
    ("apply_per_channel_scale", ("Tensor", "x"), ("Tensor", "scales")),
    (
        "argmax",
        ("Tensor", "x"),
        ("Scalar(int64_t)", "axis"),
        ("bool", "keepdims"),
        ("bool", "flatten"),
        ("DataType", "dtype"),
    ),
    (
        "argmin",
        ("Tensor", "x"),
        ("Scalar(int64_t)", "axis"),
        ("bool", "keepdims"),
        ("bool", "flatten"),
        ("DataType", "dtype"),
    ),
    (
        "argsort",
        ("Tensor", "x"),
        ("int", "axis"),
        ("bool", "descending"),
        ("bool", "stable"),
    ),
    ("as_complex", ("Tensor", "x")),
    ("as_real", ("Tensor", "x")),
    (
        "as_strided",
        ("Tensor", "input"),
        ("int64_t[]", "dims"),
        ("int64_t[]", "stride"),
        ("int64_t", "offset"),
    ),
    (
        "asgd_",
        ("Tensor", "param"),
        ("Tensor", "grad"),
        ("Tensor", "learning_rate"),
        ("Tensor", "d"),
        ("Tensor", "y"),
        ("Tensor", "n"),
        ("Tensor", "master_param"),
        ("bool", "multi_precision"),
    ),
    ("asin", ("Tensor", "x")),
    ("asinh", ("Tensor", "x")),
    ("assign_out_", ("Tensor", "x"), ("Tensor", "output")),
    (
        "assign_pos",
        ("Tensor", "x"),
        ("Tensor", "cum_count"),
        ("Tensor", "eff_num_len"),
    ),
    (
        "assign_value_",
        ("Tensor", "output"),
        ("int[]", "shape"),
        ("DataType", "dtype"),
        ("Scalar[]", "values"),
        ("Place", "place"),
    ),
    ("atan", ("Tensor", "x")),
    ("atan2", ("Tensor", "x"), ("Tensor", "y")),
    ("atanh", ("Tensor", "x")),
    (
        "auc",
        ("Tensor", "x"),
        ("Tensor", "label"),
        ("Tensor", "stat_pos"),
        ("Tensor", "stat_neg"),
        ("Tensor", "ins_tag_weight"),
        ("str", "curve"),
        ("int", "num_thresholds"),
        ("int", "slide_steps"),
    ),
    (
        "average_accumulates_",
        ("Tensor", "param"),
        ("Tensor", "in_sum_1"),
        ("Tensor", "in_sum_2"),
        ("Tensor", "in_sum_3"),
        ("Tensor", "in_num_accumulates"),
        ("Tensor", "in_old_num_accumulates"),
        ("Tensor", "in_num_updates"),
        ("float", "average_window"),
        ("int64_t", "max_average_window"),
        ("int64_t", "min_average_window"),
    ),
    ("bce_loss", ("Tensor", "input"), ("Tensor", "label")),
    ("bernoulli", ("Tensor", "x")),
    (
        "bicubic_interp",
        ("Tensor", "x"),
        ("Tensor", "out_size"),
        ("Tensor[]", "size_tensor"),
        ("Tensor", "scale_tensor"),
        ("str", "data_format"),
        ("int", "out_d"),
        ("int", "out_h"),
        ("int", "out_w"),
        ("float[]", "scale"),
        ("str", "interp_method"),
        ("bool", "align_corners"),
        ("int", "align_mode"),
    ),
    (
        "bilinear",
        ("Tensor", "x"),
        ("Tensor", "y"),
        ("Tensor", "weight"),
        ("Tensor", "bias"),
    ),
    (
        "bilinear_interp",
        ("Tensor", "x"),
        ("Tensor", "out_size"),
        ("Tensor[]", "size_tensor"),
        ("Tensor", "scale_tensor"),
        ("str", "data_format"),
        ("int", "out_d"),
        ("int", "out_h"),
        ("int", "out_w"),
        ("float[]", "scale"),
        ("str", "interp_method"),
        ("bool", "align_corners"),
        ("int", "align_mode"),
    ),
    (
        "bincount",
        ("Tensor", "x"),
        ("Tensor", "weights"),
        ("Scalar(int)", "minlength"),
    ),
    ("binomial", ("Tensor", "count"), ("Tensor", "prob")),
    ("bitwise_and", ("Tensor", "x"), ("Tensor", "y")),
    (
        "bitwise_left_shift",
        ("Tensor", "x"),
        ("Tensor", "y"),
        ("bool", "is_arithmetic"),
    ),
    ("bitwise_not", ("Tensor", "x")),
    ("bitwise_or", ("Tensor", "x"), ("Tensor", "y")),
    (
        "bitwise_right_shift",
        ("Tensor", "x"),
        ("Tensor", "y"),
        ("bool", "is_arithmetic"),
    ),
    ("bitwise_xor", ("Tensor", "x"), ("Tensor", "y")),
    ("bmm", ("Tensor", "x"), ("Tensor", "y")),
    ("box_clip", ("Tensor", "input"), ("Tensor", "im_info")),
    (
        "box_coder",
        ("Tensor", "prior_box"),
        ("Tensor", "prior_box_var"),
        ("Tensor", "target_box"),
        ("str", "code_type"),
        ("bool", "box_normalized"),
        ("int", "axis"),
        ("float[]", "variance"),
    ),
    ("broadcast_tensors", ("Tensor[]", "input")),
    (
        "c_allgather",
        ("Tensor", "x"),
        ("int", "ring_id"),
        ("int", "nranks"),
        ("bool", "use_calc_stream"),
    ),
    (
        "c_allreduce_max",
        ("Tensor", "x"),
        ("int", "ring_id"),
        ("bool", "use_calc_stream"),
        ("bool", "use_model_parallel"),
    ),
    (
        "c_allreduce_min",
        ("Tensor", "x"),
        ("int", "ring_id"),
        ("bool", "use_calc_stream"),
        ("bool", "use_model_parallel"),
    ),
    (
        "c_allreduce_prod",
        ("Tensor", "x"),
        ("int", "ring_id"),
        ("bool", "use_calc_stream"),
        ("bool", "use_model_parallel"),
    ),
    (
        "c_allreduce_sum",
        ("Tensor", "x"),
        ("int", "ring_id"),
        ("bool", "use_calc_stream"),
        ("bool", "use_model_parallel"),
    ),
    (
        "c_broadcast",
        ("Tensor", "x"),
        ("int", "ring_id"),
        ("int", "root"),
        ("bool", "use_calc_stream"),
    ),
    (
        "c_concat",
        ("Tensor", "x"),
        ("int", "rank"),
        ("int", "nranks"),
        ("int", "ring_id"),
        ("bool", "use_calc_stream"),
        ("bool", "use_model_parallel"),
    ),
    (
        "c_identity",
        ("Tensor", "x"),
        ("int", "ring_id"),
        ("bool", "use_calc_stream"),
        ("bool", "use_model_parallel"),
    ),
    (
        "c_reduce_sum",
        ("Tensor", "x"),
        ("int", "ring_id"),
        ("int", "root_id"),
        ("bool", "use_calc_stream"),
    ),
    ("c_sync_calc_stream", ("Tensor", "x")),
    ("c_sync_comm_stream", ("Tensor", "x"), ("int", "ring_id")),
    ("cast", ("Tensor", "x"), ("DataType", "dtype")),
    ("ceil", ("Tensor", "x")),
    ("celu", ("Tensor", "x"), ("float", "alpha")),
    (
        "channel_shuffle",
        ("Tensor", "x"),
        ("int", "groups"),
        ("str", "data_format"),
    ),
    ("check_finite_and_unscale_", ("Tensor[]", "x"), ("Tensor", "scale")),
    (
        "check_numerics",
        ("Tensor", "tensor"),
        ("str", "op_type"),
        ("str", "var_name"),
        ("int", "check_nan_inf_level"),
        ("int", "stack_height_limit"),
        ("str", "output_dir"),
    ),
    ("cholesky", ("Tensor", "x"), ("bool", "upper")),
    ("cholesky_solve", ("Tensor", "x"), ("Tensor", "y"), ("bool", "upper")),
    (
        "class_center_sample",
        ("Tensor", "label"),
        ("int", "num_classes"),
        ("int", "num_samples"),
        ("int", "ring_id"),
        ("int", "rank"),
        ("int", "nranks"),
        ("bool", "fix_seed"),
        ("int", "seed"),
    ),
    (
        "clip",
        ("Tensor", "x"),
        ("Scalar(float)", "min"),
        ("Scalar(float)", "max"),
    ),
    ("clip_by_norm", ("Tensor", "x"), ("float", "max_norm")),
    (
        "coalesce_tensor",
        ("Tensor[]", "input"),
        ("DataType", "dtype"),
        ("bool", "copy_data"),
        ("bool", "set_constant"),
        ("bool", "persist_output"),
        ("float", "constant"),
        ("bool", "use_align"),
        ("int", "align_size"),
        ("int", "size_of_dtype"),
        ("int64_t[]", "concated_shapes"),
        ("int64_t[]", "concated_ranks"),
    ),
    ("complex", ("Tensor", "real"), ("Tensor", "imag")),
    ("concat", ("Tensor[]", "x"), ("Scalar", "axis")),
    ("conj", ("Tensor", "x")),
    (
        "conv2d",
        ("Tensor", "input"),
        ("Tensor", "filter"),
        ("int[]", "strides"),
        ("int[]", "paddings"),
        ("str", "padding_algorithm"),
        ("int[]", "dilations"),
        ("int", "groups"),
        ("str", "data_format"),
    ),
    (
        "conv2d_transpose",
        ("Tensor", "x"),
        ("Tensor", "filter"),
        ("int[]", "strides"),
        ("int[]", "paddings"),
        ("int[]", "output_padding"),
        ("IntArray", "output_size"),
        ("str", "padding_algorithm"),
        ("int", "groups"),
        ("int[]", "dilations"),
        ("str", "data_format"),
    ),
    (
        "conv2d_transpose_bias",
        ("Tensor", "x"),
        ("Tensor", "filter"),
        ("Tensor", "bias"),
        ("int[]", "strides"),
        ("int[]", "paddings"),
        ("int[]", "output_padding"),
        ("IntArray", "output_size"),
        ("str", "padding_algorithm"),
        ("int", "groups"),
        ("int[]", "dilations"),
        ("str", "data_format"),
    ),
    (
        "conv3d",
        ("Tensor", "input"),
        ("Tensor", "filter"),
        ("int[]", "strides"),
        ("int[]", "paddings"),
        ("str", "padding_algorithm"),
        ("int", "groups"),
        ("int[]", "dilations"),
        ("str", "data_format"),
    ),
    (
        "conv3d_transpose",
        ("Tensor", "x"),
        ("Tensor", "filter"),
        ("int[]", "strides"),
        ("int[]", "paddings"),
        ("int[]", "output_padding"),
        ("int[]", "output_size"),
        ("str", "padding_algorithm"),
        ("int", "groups"),
        ("int[]", "dilations"),
        ("str", "data_format"),
    ),
    ("copy_to", ("Tensor", "x"), ("Place", "place"), ("bool", "blocking")),
    ("copysign", ("Tensor", "x"), ("Tensor", "y")),
    (
        "correlation",
        ("Tensor", "input1"),
        ("Tensor", "input2"),
        ("int", "pad_size"),
        ("int", "kernel_size"),
        ("int", "max_displacement"),
        ("int", "stride1"),
        ("int", "stride2"),
        ("int", "corr_type_multiply"),
    ),
    ("cos", ("Tensor", "x")),
    ("cosh", ("Tensor", "x")),
    (
        "crf_decoding",
        ("Tensor", "emission"),
        ("Tensor", "transition"),
        ("Tensor", "label"),
        ("Tensor", "length"),
    ),
    ("crop", ("Tensor", "x"), ("IntArray", "shape"), ("IntArray", "offsets")),
    ("cross", ("Tensor", "x"), ("Tensor", "y"), ("int", "axis")),
    (
        "cross_entropy_with_softmax",
        ("Tensor", "input"),
        ("Tensor", "label"),
        ("bool", "soft_label"),
        ("bool", "use_softmax"),
        ("bool", "numeric_stable_mode"),
        ("int", "ignore_index"),
        ("int", "axis"),
    ),
    (
        "ctc_align",
        ("Tensor", "input"),
        ("Tensor", "input_length"),
        ("int", "blank"),
        ("bool", "merge_repeated"),
        ("int", "padding_value"),
    ),
    (
        "cudnn_lstm",
        ("Tensor", "x"),
        ("Tensor", "init_h"),
        ("Tensor", "init_c"),
        ("Tensor", "w"),
        ("Tensor[]", "weight_list"),
        ("Tensor", "sequence_length"),
        ("float", "dropout_prob"),
        ("bool", "is_bidirec"),
        ("int", "hidden_size"),
        ("int", "num_layers"),
        ("bool", "is_test"),
        ("int", "seed"),
    ),
    ("cummax", ("Tensor", "x"), ("int", "axis"), ("DataType", "dtype")),
    ("cummin", ("Tensor", "x"), ("int", "axis"), ("DataType", "dtype")),
    (
        "cumprod",
        ("Tensor", "x"),
        ("int", "dim"),
        ("bool", "exclusive"),
        ("bool", "reverse"),
    ),
    (
        "cumsum",
        ("Tensor", "x"),
        ("Scalar", "axis"),
        ("bool", "flatten"),
        ("bool", "exclusive"),
        ("bool", "reverse"),
    ),
    (
        "data",
        ("str", "name"),
        ("IntArray", "shape"),
        ("DataType", "dtype"),
        ("Place", "place"),
    ),
    (
        "decayed_adagrad",
        ("Tensor", "param"),
        ("Tensor", "grad"),
        ("Tensor", "moment"),
        ("Tensor", "learning_rate"),
        ("float", "decay"),
        ("float", "epsilon"),
    ),
    ("decode_jpeg", ("Tensor", "x"), ("str", "mode"), ("Place", "place")),
    (
        "deformable_conv",
        ("Tensor", "x"),
        ("Tensor", "offset"),
        ("Tensor", "filter"),
        ("Tensor", "mask"),
        ("int[]", "strides"),
        ("int[]", "paddings"),
        ("int[]", "dilations"),
        ("int", "deformable_groups"),
        ("int", "groups"),
        ("int", "im2col_step"),
    ),
    ("depend", ("Tensor", "x"), ("Tensor[]", "dep")),
    (
        "depthwise_conv2d",
        ("Tensor", "input"),
        ("Tensor", "filter"),
        ("int[]", "strides"),
        ("int[]", "paddings"),
        ("str", "padding_algorithm"),
        ("int", "groups"),
        ("int[]", "dilations"),
        ("str", "data_format"),
    ),
    (
        "depthwise_conv2d_transpose",
        ("Tensor", "x"),
        ("Tensor", "filter"),
        ("int[]", "strides"),
        ("int[]", "paddings"),
        ("int[]", "output_padding"),
        ("IntArray", "output_size"),
        ("str", "padding_algorithm"),
        ("int", "groups"),
        ("int[]", "dilations"),
        ("str", "data_format"),
    ),
    (
        "dequantize_abs_max",
        ("Tensor", "x"),
        ("Tensor", "scale"),
        ("float", "max_range"),
    ),
    ("dequantize_log", ("Tensor", "x"), ("Tensor", "dict")),
    ("det", ("Tensor", "x")),
    (
        "detection_map",
        ("Tensor", "detect_res"),
        ("Tensor", "label"),
        ("Tensor", "has_state"),
        ("Tensor", "pos_count"),
        ("Tensor", "true_pos"),
        ("Tensor", "false_pos"),
        ("int", "class_num"),
        ("int", "background_label"),
        ("float", "overlap_threshold"),
        ("bool", "evaluate_difficult"),
        ("str", "ap_type"),
    ),
    (
        "dgc",
        ("Tensor", "u"),
        ("Tensor", "v"),
        ("Tensor", "grad"),
        ("Tensor", "param"),
        ("Tensor", "current_step"),
        ("Tensor", "nranks"),
        ("float", "m"),
        ("bool", "use_nesterov"),
        ("float[]", "sparsity"),
        ("float", "rampup_begin_step"),
        ("float", "rampup_step"),
        ("float", "regular_coeff"),
        ("int", "regular_type"),
    ),
    (
        "dgc_momentum",
        ("Tensor", "param"),
        ("Tensor", "grad"),
        ("Tensor", "velocity"),
        ("Tensor", "learning_rate"),
        ("Tensor", "master_param"),
        ("Tensor", "current_step_tensor"),
        ("Tensor", "nranks_tensor"),
        ("float", "mu"),
        ("bool", "use_nesterov"),
        ("str", "regularization_method"),
        ("float", "regularization_coeff"),
        ("bool", "multi_precision"),
        ("float", "rescale_grad"),
        ("float", "rampup_begin_step"),
    ),
    ("diag", ("Tensor", "x"), ("int", "offset"), ("float", "padding_value")),
    (
        "diag_embed",
        ("Tensor", "input"),
        ("int", "offset"),
        ("int", "dim1"),
        ("int", "dim2"),
    ),
    (
        "diagonal",
        ("Tensor", "x"),
        ("int", "offset"),
        ("int", "axis1"),
        ("int", "axis2"),
    ),
    ("digamma", ("Tensor", "x")),
    ("dirichlet", ("Tensor", "alpha")),
    ("disable_check_model_nan_inf", ("Tensor", "x"), ("int", "flag")),
    ("dist", ("Tensor", "x"), ("Tensor", "y"), ("float", "p")),
    ("dot", ("Tensor", "x"), ("Tensor", "y")),
    (
        "dropout",
        ("Tensor", "x"),
        ("Tensor", "seed_tensor"),
        ("Scalar", "p"),
        ("bool", "is_test"),
        ("str", "mode"),
        ("int", "seed"),
        ("bool", "fix_seed"),
    ),
    (
        "edit_distance",
        ("Tensor", "hyps"),
        ("Tensor", "refs"),
        ("Tensor", "hypslength"),
        ("Tensor", "refslength"),
        ("bool", "normalized"),
    ),
    ("eig", ("Tensor", "x")),
    ("eigh", ("Tensor", "x"), ("str", "UPLO")),
    ("eigvals", ("Tensor", "x")),
    ("eigvalsh", ("Tensor", "x"), ("str", "uplo"), ("bool", "is_test")),
    ("elu", ("Tensor", "x"), ("float", "alpha")),
    ("empty", ("IntArray", "shape"), ("DataType", "dtype"), ("Place", "place")),
    ("empty_like", ("Tensor", "x"), ("DataType", "dtype"), ("Place", "place")),
    ("enable_check_model_nan_inf", ("Tensor", "x"), ("int", "flag")),
    ("equal_all", ("Tensor", "x"), ("Tensor", "y")),
    ("erf", ("Tensor", "x")),
    ("erfinv", ("Tensor", "x")),
    ("exp", ("Tensor", "x")),
    ("expand", ("Tensor", "x"), ("IntArray", "shape")),
    ("expand_as", ("Tensor", "x"), ("Tensor", "y"), ("int[]", "target_shape")),
    ("expm1", ("Tensor", "x")),
    ("exponential_", ("Tensor", "x"), ("float", "lam")),
    (
        "eye",
        ("Scalar", "num_rows"),
        ("Scalar", "num_columns"),
        ("DataType", "dtype"),
        ("Place", "place"),
    ),
    (
        "fake_channel_wise_dequantize_max_abs",
        ("Tensor", "x"),
        ("Tensor[]", "scales"),
        ("int[]", "quant_bits"),
        ("int", "quant_axis"),
        ("int", "x_num_col_dims"),
    ),
    (
        "fake_channel_wise_quantize_abs_max",
        ("Tensor", "x"),
        ("int", "bit_length"),
        ("int", "round_type"),
        ("int", "quant_axis"),
        ("bool", "is_test"),
    ),
    (
        "fake_channel_wise_quantize_dequantize_abs_max",
        ("Tensor", "x"),
        ("int", "bit_length"),
        ("int", "round_type"),
        ("int", "quant_axis"),
    ),
    (
        "fake_dequantize_max_abs",
        ("Tensor", "x"),
        ("Tensor", "scale"),
        ("float", "max_range"),
    ),
    (
        "fake_quantize_abs_max",
        ("Tensor", "x"),
        ("int", "bit_length"),
        ("int", "round_type"),
    ),
    (
        "fake_quantize_dequantize_abs_max",
        ("Tensor", "x"),
        ("int", "bit_length"),
        ("int", "round_type"),
    ),
    (
        "fake_quantize_dequantize_moving_average_abs_max",
        ("Tensor", "x"),
        ("Tensor", "in_scale"),
        ("Tensor", "in_accum"),
        ("Tensor", "in_state"),
        ("float", "moving_rate"),
        ("int", "bit_length"),
        ("bool", "is_test"),
        ("int", "round_type"),
    ),
    (
        "fake_quantize_moving_average_abs_max",
        ("Tensor", "x"),
        ("Tensor", "in_scale"),
        ("Tensor", "in_accum"),
        ("Tensor", "in_state"),
        ("float", "moving_rate"),
        ("int", "bit_length"),
        ("bool", "is_test"),
        ("int", "round_type"),
    ),
    (
        "fake_quantize_range_abs_max",
        ("Tensor", "x"),
        ("Tensor", "in_scale"),
        ("Tensor", "iter"),
        ("int", "window_size"),
        ("int", "bit_length"),
        ("bool", "is_test"),
        ("int", "round_type"),
    ),
    (
        "fft_c2c",
        ("Tensor", "x"),
        ("int64_t[]", "axes"),
        ("str", "normalization"),
        ("bool", "forward"),
    ),
    (
        "fft_c2r",
        ("Tensor", "x"),
        ("int64_t[]", "axes"),
        ("str", "normalization"),
        ("bool", "forward"),
        ("int64_t", "last_dim_size"),
    ),
    (
        "fft_r2c",
        ("Tensor", "x"),
        ("int64_t[]", "axes"),
        ("str", "normalization"),
        ("bool", "forward"),
        ("bool", "onesided"),
    ),
    ("fill", ("Tensor", "x"), ("Scalar", "value")),
    (
        "fill_diagonal",
        ("Tensor", "x"),
        ("float", "value"),
        ("int", "offset"),
        ("bool", "wrap"),
    ),
    (
        "fill_diagonal_tensor",
        ("Tensor", "x"),
        ("Tensor", "y"),
        ("int64_t", "offset"),
        ("int", "dim1"),
        ("int", "dim2"),
    ),
    (
        "flash_attn",
        ("Tensor", "q"),
        ("Tensor", "k"),
        ("Tensor", "v"),
        ("Tensor", "fixed_seed_offset"),
        ("Tensor", "attn_mask"),
        ("float", "dropout"),
        ("bool", "causal"),
        ("bool", "return_softmax"),
        ("bool", "is_test"),
        ("str", "rng_name"),
    ),
    (
        "flash_attn_qkvpacked",
        ("Tensor", "qkv"),
        ("Tensor", "fixed_seed_offset"),
        ("Tensor", "attn_mask"),
        ("float", "dropout"),
        ("bool", "causal"),
        ("bool", "return_softmax"),
        ("bool", "is_test"),
        ("str", "rng_name"),
    ),
    (
        "flash_attn_unpadded",
        ("Tensor", "q"),
        ("Tensor", "k"),
        ("Tensor", "v"),
        ("Tensor", "cu_seqlens_q"),
        ("Tensor", "cu_seqlens_k"),
        ("Tensor", "fixed_seed_offset"),
        ("Tensor", "attn_mask"),
        ("int64_t", "max_seqlen_q"),
        ("int64_t", "max_seqlen_k"),
        ("float", "scale"),
        ("float", "dropout"),
        ("bool", "causal"),
        ("bool", "return_softmax"),
        ("bool", "is_test"),
        ("str", "rng_name"),
    ),
    (
        "flash_attn_varlen_qkvpacked",
        ("Tensor", "qkv"),
        ("Tensor", "cu_seqlens_q"),
        ("Tensor", "cu_seqlens_k"),
        ("Tensor", "fixed_seed_offset"),
        ("Tensor", "attn_mask"),
        ("int64_t", "max_seqlen_q"),
        ("int64_t", "max_seqlen_k"),
        ("float", "scale"),
        ("float", "dropout"),
        ("bool", "causal"),
        ("bool", "return_softmax"),
        ("bool", "is_test"),
        ("str", "rng_name"),
        ("bool", "varlen_padded"),
    ),
    (
        "flash_attn_with_sparse_mask",
        ("Tensor", "q"),
        ("Tensor", "k"),
        ("Tensor", "v"),
        ("Tensor", "attn_mask_start_row_indices"),
        ("Tensor", "fixed_seed_offset"),
        ("float", "dropout"),
        ("bool", "causal"),
        ("int", "attn_mask_start_row"),
        ("bool", "return_softmax"),
        ("bool", "is_test"),
        ("str", "rng_name"),
    ),
    ("flatten", ("Tensor", "x"), ("int", "start_axis"), ("int", "stop_axis")),
    ("flip", ("Tensor", "x"), ("int[]", "axis")),
    ("floor", ("Tensor", "x")),
    ("fmax", ("Tensor", "x"), ("Tensor", "y")),
    ("fmin", ("Tensor", "x"), ("Tensor", "y")),
    (
        "fold",
        ("Tensor", "x"),
        ("int[]", "output_sizes"),
        ("int[]", "kernel_sizes"),
        ("int[]", "strides"),
        ("int[]", "paddings"),
        ("int[]", "dilations"),
    ),
    (
        "fractional_max_pool2d",
        ("Tensor", "x"),
        ("int[]", "output_size"),
        ("int[]", "kernel_size"),
        ("float", "random_u"),
        ("bool", "return_mask"),
    ),
    (
        "fractional_max_pool3d",
        ("Tensor", "x"),
        ("int[]", "output_size"),
        ("int[]", "kernel_size"),
        ("float", "random_u"),
        ("bool", "return_mask"),
    ),
    (
        "frame",
        ("Tensor", "x"),
        ("int", "frame_length"),
        ("int", "hop_length"),
        ("int", "axis"),
    ),
    (
        "frobenius_norm",
        ("Tensor", "x"),
        ("IntArray", "axis"),
        ("bool", "keep_dim"),
        ("bool", "reduce_all"),
    ),
    (
        "full",
        ("IntArray", "shape"),
        ("Scalar", "value"),
        ("DataType", "dtype"),
        ("Place", "place"),
    ),
    (
        "full_",
        ("Tensor", "output"),
        ("IntArray", "shape"),
        ("Scalar", "value"),
        ("DataType", "dtype"),
        ("Place", "place"),
    ),
    (
        "full_batch_size_like",
        ("Tensor", "input"),
        ("int[]", "shape"),
        ("DataType", "dtype"),
        ("Scalar", "value"),
        ("int", "input_dim_idx"),
        ("int", "output_dim_idx"),
        ("Place", "place"),
    ),
    (
        "full_int_array",
        ("int64_t[]", "value"),
        ("DataType", "dtype"),
        ("Place", "place"),
    ),
    (
        "full_like",
        ("Tensor", "x"),
        ("Scalar", "value"),
        ("DataType", "dtype"),
        ("Place", "place"),
    ),
    (
        "full_with_tensor",
        ("Tensor", "value"),
        ("IntArray", "shape"),
        ("DataType", "dtype"),
    ),
    (
        "fused_batch_norm_act",
        ("Tensor", "x"),
        ("Tensor", "scale"),
        ("Tensor", "bias"),
        ("Tensor", "mean"),
        ("Tensor", "variance"),
        ("float", "momentum"),
        ("float", "epsilon"),
        ("str", "act_type"),
    ),
    (
        "fused_bn_add_activation",
        ("Tensor", "x"),
        ("Tensor", "z"),
        ("Tensor", "scale"),
        ("Tensor", "bias"),
        ("Tensor", "mean"),
        ("Tensor", "variance"),
        ("float", "momentum"),
        ("float", "epsilon"),
        ("str", "act_type"),
    ),
    (
        "fused_multi_transformer",
        ("Tensor", "x"),
        ("Tensor[]", "ln_scales"),
        ("Tensor[]", "ln_biases"),
        ("Tensor[]", "qkv_weights"),
        ("Tensor[]", "qkv_biases"),
        ("Tensor[]", "cache_kvs"),
        ("Tensor[]", "pre_caches"),
        ("Tensor", "rotary_tensor"),
        ("Tensor", "beam_offset"),
        ("Tensor", "time_step"),
        ("Tensor", "seq_lengths"),
        ("Tensor", "src_mask"),
        ("Tensor[]", "out_linear_weights"),
        ("Tensor[]", "out_linear_biases"),
        ("Tensor[]", "ffn_ln_scales"),
        ("Tensor[]", "ffn_ln_biases"),
        ("Tensor[]", "ffn1_weights"),
        ("Tensor[]", "ffn1_biases"),
        ("Tensor[]", "ffn2_weights"),
        ("Tensor[]", "ffn2_biases"),
        ("bool", "pre_layer_norm"),
        ("float", "epsilon"),
        ("float", "residual_alpha"),
        ("float", "dropout_rate"),
        ("int", "rotary_emb_dims"),
        ("bool", "is_test"),
        ("str", "dropout_implementation"),
        ("str", "act_method"),
        ("bool", "trans_qkvw"),
        ("int", "ring_id"),
        ("str", "norm_type"),
        ("bool", "use_neox_rotary_style"),
        ("int", "gqa_group_size"),
    ),
    ("fused_softmax_mask", ("Tensor", "x"), ("Tensor", "mask")),
    ("fused_softmax_mask_upper_triangle", ("Tensor", "X")),
    ("gammaincc", ("Tensor", "x"), ("Tensor", "y")),
    ("gammaln", ("Tensor", "x")),
    ("gather", ("Tensor", "x"), ("Tensor", "index"), ("Scalar", "axis")),
    ("gather_nd", ("Tensor", "x"), ("Tensor", "index")),
    ("gather_tree", ("Tensor", "ids"), ("Tensor", "parents")),
    (
        "gaussian",
        ("IntArray", "shape"),
        ("float", "mean"),
        ("float", "std"),
        ("int", "seed"),
        ("DataType", "dtype"),
        ("Place", "place"),
    ),
    (
        "gaussian_inplace",
        ("Tensor", "x"),
        ("float", "mean"),
        ("float", "std"),
        ("int", "seed"),
    ),
    ("gelu", ("Tensor", "x"), ("bool", "approximate")),
    (
        "generate_proposals",
        ("Tensor", "scores"),
        ("Tensor", "bbox_deltas"),
        ("Tensor", "im_shape"),
        ("Tensor", "anchors"),
        ("Tensor", "variances"),
        ("int", "pre_nms_top_n"),
        ("int", "post_nms_top_n"),
        ("float", "nms_thresh"),
        ("float", "min_size"),
        ("float", "eta"),
        ("bool", "pixel_offset"),
    ),
    (
        "graph_khop_sampler",
        ("Tensor", "row"),
        ("Tensor", "colptr"),
        ("Tensor", "x"),
        ("Tensor", "eids"),
        ("int[]", "sample_sizes"),
        ("bool", "return_eids"),
    ),
    (
        "graph_sample_neighbors",
        ("Tensor", "row"),
        ("Tensor", "colptr"),
        ("Tensor", "x"),
        ("Tensor", "eids"),
        ("Tensor", "perm_buffer"),
        ("int", "sample_size"),
        ("bool", "return_eids"),
        ("bool", "flag_perm_buffer"),
    ),
    (
        "grid_sample",
        ("Tensor", "x"),
        ("Tensor", "grid"),
        ("str", "mode"),
        ("str", "padding_mode"),
        ("bool", "align_corners"),
    ),
    (
        "group_norm",
        ("Tensor", "x"),
        ("Tensor", "scale"),
        ("Tensor", "bias"),
        ("float", "epsilon"),
        ("int", "groups"),
        ("str", "data_format"),
    ),
    (
        "gru",
        ("Tensor", "input"),
        ("Tensor", "h0"),
        ("Tensor", "weight"),
        ("Tensor", "bias"),
        ("str", "activation"),
        ("str", "gate_activation"),
        ("bool", "is_reverse"),
        ("bool", "origin_mode"),
        ("bool", "is_test"),
    ),
    (
        "gru_unit",
        ("Tensor", "input"),
        ("Tensor", "hidden_prev"),
        ("Tensor", "weight"),
        ("Tensor", "bias"),
        ("int", "activation"),
        ("int", "gate_activation"),
        ("bool", "origin_mode"),
    ),
    (
        "gumbel_softmax",
        ("Tensor", "x"),
        ("float", "temperature"),
        ("bool", "hard"),
        ("int", "axis"),
    ),
    ("hardshrink", ("Tensor", "x"), ("float", "threshold")),
    ("hardsigmoid", ("Tensor", "x"), ("float", "slope"), ("float", "offset")),
    ("hardtanh", ("Tensor", "x"), ("float", "t_min"), ("float", "t_max")),
    ("heaviside", ("Tensor", "x"), ("Tensor", "y")),
    (
        "histogram",
        ("Tensor", "input"),
        ("int64_t", "bins"),
        ("int", "min"),
        ("int", "max"),
    ),
    (
        "hsigmoid_loss",
        ("Tensor", "x"),
        ("Tensor", "label"),
        ("Tensor", "w"),
        ("Tensor", "bias"),
        ("Tensor", "path"),
        ("Tensor", "code"),
        ("int", "num_classes"),
        ("bool", "is_sparse"),
    ),
    (
        "huber_loss",
        ("Tensor", "input"),
        ("Tensor", "label"),
        ("float", "delta"),
    ),
    ("i0", ("Tensor", "x")),
    ("i0e", ("Tensor", "x")),
    ("i1", ("Tensor", "x")),
    ("i1e", ("Tensor", "x")),
    ("identity_loss", ("Tensor", "x"), ("int", "reduction")),
    ("imag", ("Tensor", "x")),
    ("increment", ("Tensor", "x"), ("float", "value")),
    (
        "index_add",
        ("Tensor", "x"),
        ("Tensor", "index"),
        ("Tensor", "add_value"),
        ("int", "axis"),
    ),
    (
        "index_put",
        ("Tensor", "x"),
        ("Tensor[]", "indices"),
        ("Tensor", "value"),
        ("bool", "accumulate"),
    ),
    ("index_sample", ("Tensor", "x"), ("Tensor", "index")),
    ("index_select", ("Tensor", "x"), ("Tensor", "index"), ("int", "axis")),
    (
        "index_select_strided",
        ("Tensor", "x"),
        ("int64_t", "index"),
        ("int", "axis"),
    ),
    (
        "instance_norm",
        ("Tensor", "x"),
        ("Tensor", "scale"),
        ("Tensor", "bias"),
        ("float", "epsilon"),
    ),
    ("inverse", ("Tensor", "x")),
    ("is_empty", ("Tensor", "x")),
    (
        "isclose",
        ("Tensor", "x"),
        ("Tensor", "y"),
        ("Scalar(double)", "rtol"),
        ("Scalar(double)", "atol"),
        ("bool", "equal_nan"),
    ),
    ("isfinite", ("Tensor", "x")),
    ("isinf", ("Tensor", "x")),
    ("isnan", ("Tensor", "x")),
    (
        "kldiv_loss",
        ("Tensor", "x"),
        ("Tensor", "label"),
        ("str", "reduction"),
        ("bool", "log_target"),
    ),
    ("kron", ("Tensor", "x"), ("Tensor", "y")),
    (
        "kthvalue",
        ("Tensor", "x"),
        ("int", "k"),
        ("int", "axis"),
        ("bool", "keepdim"),
    ),
    ("l1_norm", ("Tensor", "x")),
    (
        "label_smooth",
        ("Tensor", "label"),
        ("Tensor", "prior_dist"),
        ("float", "epsilon"),
    ),
    (
        "lamb_",
        ("Tensor", "param"),
        ("Tensor", "grad"),
        ("Tensor", "learning_rate"),
        ("Tensor", "moment1"),
        ("Tensor", "moment2"),
        ("Tensor", "beta1_pow"),
        ("Tensor", "beta2_pow"),
        ("Tensor", "master_param"),
        ("Tensor", "skip_update"),
        ("float", "weight_decay"),
        ("float", "beta1"),
        ("float", "beta2"),
        ("float", "epsilon"),
        ("bool", "always_adapt"),
        ("bool", "multi_precision"),
    ),
    (
        "layer_norm",
        ("Tensor", "x"),
        ("Tensor", "scale"),
        ("Tensor", "bias"),
        ("float", "epsilon"),
        ("int", "begin_norm_axis"),
    ),
    ("leaky_relu", ("Tensor", "x"), ("float", "negative_slope")),
    ("lerp", ("Tensor", "x"), ("Tensor", "y"), ("Tensor", "weight")),
    ("lgamma", ("Tensor", "x")),
    (
        "limit_by_capacity",
        ("Tensor", "expert_count"),
        ("Tensor", "capacity"),
        ("int", "n_worker"),
    ),
    (
        "linear_interp",
        ("Tensor", "x"),
        ("Tensor", "out_size"),
        ("Tensor[]", "size_tensor"),
        ("Tensor", "scale_tensor"),
        ("str", "data_format"),
        ("int", "out_d"),
        ("int", "out_h"),
        ("int", "out_w"),
        ("float[]", "scale"),
        ("str", "interp_method"),
        ("bool", "align_corners"),
        ("int", "align_mode"),
    ),
    (
        "linspace",
        ("Tensor", "start"),
        ("Tensor", "stop"),
        ("Tensor", "number"),
        ("DataType", "dtype"),
        ("Place", "place"),
    ),
    (
        "llm_int8_linear",
        ("Tensor", "x"),
        ("Tensor", "weight"),
        ("Tensor", "bias"),
        ("Tensor", "weight_scale"),
        ("float", "threshold"),
    ),
    ("log", ("Tensor", "x")),
    ("log10", ("Tensor", "x")),
    ("log1p", ("Tensor", "x")),
    ("log2", ("Tensor", "x")),
    (
        "log_loss",
        ("Tensor", "input"),
        ("Tensor", "label"),
        ("float", "epsilon"),
    ),
    ("log_softmax", ("Tensor", "x"), ("int", "axis")),
    (
        "logcumsumexp",
        ("Tensor", "x"),
        ("int", "axis"),
        ("bool", "flatten"),
        ("bool", "exclusive"),
        ("bool", "reverse"),
    ),
    ("logical_and", ("Tensor", "x"), ("Tensor", "y")),
    ("logical_not", ("Tensor", "x")),
    ("logical_or", ("Tensor", "x"), ("Tensor", "y")),
    ("logical_xor", ("Tensor", "x"), ("Tensor", "y")),
    ("logit", ("Tensor", "x"), ("float", "eps")),
    ("logsigmoid", ("Tensor", "x")),
    (
        "logspace",
        ("Tensor", "start"),
        ("Tensor", "stop"),
        ("Tensor", "num"),
        ("Tensor", "base"),
        ("DataType", "dtype"),
        ("Place", "place"),
    ),
    (
        "logsumexp",
        ("Tensor", "x"),
        ("int64_t[]", "axis"),
        ("bool", "keepdim"),
        ("bool", "reduce_all"),
    ),
    (
        "lstm",
        ("Tensor", "input"),
        ("Tensor", "h0"),
        ("Tensor", "c0"),
        ("Tensor", "weight"),
        ("Tensor", "bias"),
        ("bool", "use_peepholes"),
        ("bool", "is_reverse"),
        ("bool", "is_test"),
        ("str", "gate_activation"),
        ("str", "cell_activation"),
        ("str", "candidate_activation"),
    ),
    (
        "lstsq",
        ("Tensor", "x"),
        ("Tensor", "y"),
        ("Scalar", "rcond"),
        ("str", "driver"),
    ),
    ("lu", ("Tensor", "x"), ("bool", "pivot")),
    (
        "lu_unpack",
        ("Tensor", "x"),
        ("Tensor", "y"),
        ("bool", "unpack_ludata"),
        ("bool", "unpack_pivots"),
    ),
    (
        "margin_cross_entropy",
        ("Tensor", "logits"),
        ("Tensor", "label"),
        ("bool", "return_softmax"),
        ("int", "ring_id"),
        ("int", "rank"),
        ("int", "nranks"),
        ("float", "margin1"),
        ("float", "margin2"),
        ("float", "margin3"),
        ("float", "scale"),
    ),
    (
        "masked_multihead_attention_",
        ("Tensor", "x"),
        ("Tensor", "cache_kv"),
        ("Tensor", "bias"),
        ("Tensor", "src_mask"),
        ("Tensor", "cum_offsets"),
        ("Tensor", "sequence_lengths"),
        ("Tensor", "rotary_tensor"),
        ("Tensor", "beam_cache_offset"),
        ("Tensor", "qkv_out_scale"),
        ("Tensor", "out_shift"),
        ("Tensor", "out_smooth"),
        ("int", "seq_len"),
        ("int", "rotary_emb_dims"),
        ("bool", "use_neox_rotary_style"),
        ("str", "compute_dtype"),
        ("float", "out_scale"),
        ("int", "quant_round_type"),
        ("float", "quant_max_bound"),
        ("float", "quant_min_bound"),
    ),
    ("masked_select", ("Tensor", "x"), ("Tensor", "mask")),
    (
        "matrix_nms",
        ("Tensor", "bboxes"),
        ("Tensor", "scores"),
        ("float", "score_threshold"),
        ("int", "nms_top_k"),
        ("int", "keep_top_k"),
        ("float", "post_threshold"),
        ("bool", "use_gaussian"),
        ("float", "gaussian_sigma"),
        ("int", "background_label"),
        ("bool", "normalized"),
    ),
    ("matrix_power", ("Tensor", "x"), ("int", "n")),
    (
        "matrix_rank",
        ("Tensor", "x"),
        ("float", "tol"),
        ("bool", "use_default_tol"),
        ("bool", "hermitian"),
    ),
    (
        "matrix_rank_tol",
        ("Tensor", "x"),
        ("Tensor", "atol_tensor"),
        ("bool", "use_default_tol"),
        ("bool", "hermitian"),
    ),
    ("max", ("Tensor", "x"), ("IntArray", "axis"), ("bool", "keepdim")),
    (
        "max_pool2d_with_index",
        ("Tensor", "x"),
        ("int[]", "kernel_size"),
        ("int[]", "strides"),
        ("int[]", "paddings"),
        ("bool", "global_pooling"),
        ("bool", "adaptive"),
        ("bool", "ceil_mode"),
    ),
    (
        "max_pool3d_with_index",
        ("Tensor", "x"),
        ("int[]", "kernel_size"),
        ("int[]", "strides"),
        ("int[]", "paddings"),
        ("bool", "global_pooling"),
        ("bool", "adaptive"),
        ("bool", "ceil_mode"),
    ),
    ("maxout", ("Tensor", "x"), ("int", "groups"), ("int", "axis")),
    ("mean", ("Tensor", "x"), ("IntArray", "axis"), ("bool", "keepdim")),
    ("mean_all", ("Tensor", "x")),
    ("memcpy_d2h", ("Tensor", "x"), ("int", "dst_place_type")),
    ("memcpy_h2d", ("Tensor", "x"), ("int", "dst_place_type")),
    (
        "memory_efficient_attention",
        ("Tensor", "query"),
        ("Tensor", "key"),
        ("Tensor", "value"),
        ("Tensor", "bias"),
        ("Tensor", "cu_seqlens_q"),
        ("Tensor", "cu_seqlens_k"),
        ("Tensor", "causal_diagonal"),
        ("Tensor", "seqlen_k"),
        ("Scalar", "max_seqlen_q"),
        ("Scalar", "max_seqlen_k"),
        ("bool", "causal"),
        ("double", "dropout_p"),
        ("float", "scale"),
        ("bool", "is_test"),
    ),
    ("merge_selected_rows", ("Tensor", "x")),
    (
        "merged_adam_",
        ("Tensor[]", "param"),
        ("Tensor[]", "grad"),
        ("Tensor[]", "learning_rate"),
        ("Tensor[]", "moment1"),
        ("Tensor[]", "moment2"),
        ("Tensor[]", "beta1_pow"),
        ("Tensor[]", "beta2_pow"),
        ("Tensor[]", "master_param"),
        ("Scalar", "beta1"),
        ("Scalar", "beta2"),
        ("Scalar", "epsilon"),
        ("bool", "multi_precision"),
        ("bool", "use_global_beta_pow"),
    ),
    (
        "merged_momentum_",
        ("Tensor[]", "param"),
        ("Tensor[]", "grad"),
        ("Tensor[]", "velocity"),
        ("Tensor[]", "learning_rate"),
        ("Tensor[]", "master_param"),
        ("float", "mu"),
        ("bool", "use_nesterov"),
        ("str[]", "regularization_method"),
        ("float[]", "regularization_coeff"),
        ("bool", "multi_precision"),
        ("float", "rescale_grad"),
    ),
    ("meshgrid", ("Tensor[]", "inputs")),
    ("mish", ("Tensor", "x"), ("float", "lambda")),
    ("mode", ("Tensor", "x"), ("int", "axis"), ("bool", "keepdim")),
    (
        "momentum_",
        ("Tensor", "param"),
        ("Tensor", "grad"),
        ("Tensor", "velocity"),
        ("Tensor", "learning_rate"),
        ("Tensor", "master_param"),
        ("float", "mu"),
        ("bool", "use_nesterov"),
        ("str", "regularization_method"),
        ("float", "regularization_coeff"),
        ("bool", "multi_precision"),
        ("float", "rescale_grad"),
    ),
    ("multi_dot", ("Tensor[]", "x")),
    (
        "multiclass_nms3",
        ("Tensor", "bboxes"),
        ("Tensor", "scores"),
        ("Tensor", "rois_num"),
        ("float", "score_threshold"),
        ("int", "nms_top_k"),
        ("int", "keep_top_k"),
        ("float", "nms_threshold"),
        ("bool", "normalized"),
        ("float", "nms_eta"),
        ("int", "background_label"),
    ),
    (
        "multinomial",
        ("Tensor", "x"),
        ("Scalar(int)", "num_samples"),
        ("bool", "replacement"),
    ),
    ("multiplex", ("Tensor[]", "inputs"), ("Tensor", "index")),
    ("mv", ("Tensor", "x"), ("Tensor", "vec")),
    (
        "nadam_",
        ("Tensor", "param"),
        ("Tensor", "grad"),
        ("Tensor", "learning_rate"),
        ("Tensor", "momentum_decay_pow"),
        ("Tensor", "beta2_pow"),
        ("Tensor", "mu_product"),
        ("Tensor", "moment1"),
        ("Tensor", "moment2"),
        ("Tensor", "master_param"),
        ("float", "beta1"),
        ("float", "beta2"),
        ("float", "epsilon"),
        ("float", "momentum_decay"),
        ("bool", "multi_precision"),
    ),
    (
        "nanmedian",
        ("Tensor", "x"),
        ("IntArray", "axis"),
        ("bool", "keepdim"),
        ("str", "mode"),
    ),
    (
        "nearest_interp",
        ("Tensor", "x"),
        ("Tensor", "out_size"),
        ("Tensor[]", "size_tensor"),
        ("Tensor", "scale_tensor"),
        ("str", "data_format"),
        ("int", "out_d"),
        ("int", "out_h"),
        ("int", "out_w"),
        ("float[]", "scale"),
        ("str", "interp_method"),
        ("bool", "align_corners"),
        ("int", "align_mode"),
    ),
    ("nextafter", ("Tensor", "x"), ("Tensor", "y")),
    (
        "nll_loss",
        ("Tensor", "input"),
        ("Tensor", "label"),
        ("Tensor", "weight"),
        ("int64_t", "ignore_index"),
        ("str", "reduction"),
    ),
    ("nms", ("Tensor", "x"), ("float", "threshold")),
    ("nonzero", ("Tensor", "condition")),
    (
        "norm",
        ("Tensor", "x"),
        ("int", "axis"),
        ("float", "epsilon"),
        ("bool", "is_test"),
    ),
    ("npu_identity", ("Tensor", "x"), ("int", "format")),
    ("numel", ("Tensor", "x")),
    ("one_hot", ("Tensor", "x"), ("Scalar(int)", "num_classes")),
    ("ones", ("IntArray", "shape"), ("DataType", "dtype"), ("Place", "place")),
    ("ones_like", ("Tensor", "x"), ("DataType", "dtype"), ("Place", "place")),
    ("overlap_add", ("Tensor", "x"), ("int", "hop_length"), ("int", "axis")),
    (
        "p_norm",
        ("Tensor", "x"),
        ("float", "porder"),
        ("int", "axis"),
        ("float", "epsilon"),
        ("bool", "keepdim"),
        ("bool", "asvector"),
    ),
    ("pad", ("Tensor", "x"), ("int[]", "paddings"), ("Scalar", "pad_value")),
    (
        "pad3d",
        ("Tensor", "x"),
        ("IntArray", "paddings"),
        ("str", "mode"),
        ("float", "pad_value"),
        ("str", "data_format"),
    ),
    (
        "partial_concat",
        ("Tensor[]", "x"),
        ("int", "start_index"),
        ("int", "length"),
    ),
    (
        "partial_sum",
        ("Tensor[]", "x"),
        ("int", "start_index"),
        ("int", "length"),
    ),
    (
        "pixel_shuffle",
        ("Tensor", "x"),
        ("int", "upscale_factor"),
        ("str", "data_format"),
    ),
    (
        "pixel_unshuffle",
        ("Tensor", "x"),
        ("int", "downscale_factor"),
        ("str", "data_format"),
    ),
    ("poisson", ("Tensor", "x")),
    ("polygamma", ("Tensor", "x"), ("int", "n")),
    (
        "pool2d",
        ("Tensor", "x"),
        ("IntArray", "kernel_size"),
        ("int[]", "strides"),
        ("int[]", "paddings"),
        ("bool", "ceil_mode"),
        ("bool", "exclusive"),
        ("str", "data_format"),
        ("str", "pooling_type"),
        ("bool", "global_pooling"),
        ("bool", "adaptive"),
        ("str", "padding_algorithm"),
    ),
    (
        "pool3d",
        ("Tensor", "x"),
        ("int[]", "kernel_size"),
        ("int[]", "strides"),
        ("int[]", "paddings"),
        ("bool", "ceil_mode"),
        ("bool", "exclusive"),
        ("str", "data_format"),
        ("str", "pooling_type"),
        ("bool", "global_pooling"),
        ("bool", "adaptive"),
        ("str", "padding_algorithm"),
    ),
    ("pow", ("Tensor", "x"), ("Scalar", "y")),
    (
        "prelu",
        ("Tensor", "x"),
        ("Tensor", "alpha"),
        ("str", "data_format"),
        ("str", "mode"),
    ),
    (
        "prior_box",
        ("Tensor", "input"),
        ("Tensor", "image"),
        ("float[]", "min_sizes"),
        ("float[]", "max_sizes"),
        ("float[]", "aspect_ratios"),
        ("float[]", "variances"),
        ("bool", "flip"),
        ("bool", "clip"),
        ("float", "step_w"),
        ("float", "step_h"),
        ("float", "offset"),
        ("bool", "min_max_aspect_ratios_order"),
    ),
    (
        "prod",
        ("Tensor", "x"),
        ("IntArray", "dims"),
        ("bool", "keepdim"),
        ("bool", "reduce_all"),
    ),
    (
        "prune_gate_by_capacity",
        ("Tensor", "gate_idx"),
        ("Tensor", "expert_count"),
        ("int64_t", "n_expert"),
        ("int64_t", "n_worker"),
    ),
    (
        "psroi_pool",
        ("Tensor", "x"),
        ("Tensor", "boxes"),
        ("Tensor", "boxes_num"),
        ("int", "pooled_height"),
        ("int", "pooled_width"),
        ("int", "output_channels"),
        ("float", "spatial_scale"),
    ),
    (
        "put_along_axis",
        ("Tensor", "arr"),
        ("Tensor", "indices"),
        ("Tensor", "values"),
        ("int", "axis"),
        ("str", "reduce"),
        ("bool", "include_self"),
    ),
    (
        "pyramid_hash",
        ("Tensor", "x"),
        ("Tensor", "w"),
        ("Tensor", "white_list"),
        ("Tensor", "black_list"),
        ("int", "num_emb"),
        ("int", "space_len"),
        ("int", "pyramid_layer"),
        ("int", "rand_len"),
        ("float", "drop_out_percent"),
        ("int", "is_training"),
        ("bool", "use_filter"),
        ("int", "white_list_len"),
        ("int", "black_list_len"),
        ("int", "seed"),
        ("float", "lr"),
        ("str", "distribute_update_vars"),
    ),
    ("qr", ("Tensor", "x"), ("str", "mode")),
    (
        "radam_",
        ("Tensor", "param"),
        ("Tensor", "grad"),
        ("Tensor", "learning_rate"),
        ("Tensor", "beta1_pow"),
        ("Tensor", "beta2_pow"),
        ("Tensor", "rho"),
        ("Tensor", "moment1"),
        ("Tensor", "moment2"),
        ("Tensor", "master_param"),
        ("float", "beta1"),
        ("float", "beta2"),
        ("float", "epsilon"),
        ("bool", "multi_precision"),
    ),
    (
        "randint",
        ("int", "low"),
        ("int", "high"),
        ("IntArray", "shape"),
        ("DataType", "dtype"),
        ("Place", "place"),
    ),
    (
        "random_routing",
        ("Tensor", "prob"),
        ("Tensor", "topk_value"),
        ("Tensor", "topk_idx"),
    ),
    ("randperm", ("int", "n"), ("DataType", "dtype"), ("Place", "place")),
    (
        "rank_attention",
        ("Tensor", "x"),
        ("Tensor", "rank_offset"),
        ("Tensor", "rank_param"),
        ("int", "max_rank"),
        ("int", "max_size"),
    ),
    (
        "read_file",
        ("str", "filename"),
        ("DataType", "dtype"),
        ("Place", "place"),
    ),
    ("real", ("Tensor", "x")),
    ("reciprocal", ("Tensor", "x")),
    ("reduce_as", ("Tensor", "x"), ("Tensor", "target")),
    (
        "reindex_graph",
        ("Tensor", "x"),
        ("Tensor", "neighbors"),
        ("Tensor", "count"),
        ("Tensor", "hashtable_value"),
        ("Tensor", "hashtable_index"),
    ),
    ("relu", ("Tensor", "x")),
    ("relu6", ("Tensor", "x")),
    (
        "renorm",
        ("Tensor", "x"),
        ("float", "p"),
        ("int", "axis"),
        ("float", "max_norm"),
    ),
    ("repeat_interleave", ("Tensor", "x"), ("int", "repeats"), ("int", "axis")),
    (
        "repeat_interleave_with_tensor_index",
        ("Tensor", "x"),
        ("Tensor", "repeats"),
        ("int", "axis"),
    ),
    ("reverse", ("Tensor", "x"), ("IntArray", "axis")),
    (
        "rms_norm",
        ("Tensor", "x"),
        ("Tensor", "bias"),
        ("Tensor", "residual"),
        ("Tensor", "norm_weight"),
        ("Tensor", "norm_bias"),
        ("float", "epsilon"),
        ("int", "begin_norm_axis"),
        ("float", "quant_scale"),
        ("int", "quant_round_type"),
        ("float", "quant_max_bound"),
        ("float", "quant_min_bound"),
    ),
    (
        "rmsprop_",
        ("Tensor", "param"),
        ("Tensor", "mean_square"),
        ("Tensor", "grad"),
        ("Tensor", "moment"),
        ("Tensor", "learning_rate"),
        ("Tensor", "mean_grad"),
        ("Tensor", "master_param"),
        ("float", "epsilon"),
        ("float", "decay"),
        ("float", "momentum"),
        ("bool", "centered"),
        ("bool", "multi_precision"),
    ),
    (
        "rnn",
        ("Tensor", "x"),
        ("Tensor[]", "pre_state"),
        ("Tensor[]", "weight_list"),
        ("Tensor", "sequence_length"),
        ("Tensor", "dropout_state_in"),
        ("float", "dropout_prob"),
        ("bool", "is_bidirec"),
        ("int", "input_size"),
        ("int", "hidden_size"),
        ("int", "num_layers"),
        ("str", "mode"),
        ("int", "seed"),
        ("bool", "is_test"),
    ),
    (
        "roi_align",
        ("Tensor", "x"),
        ("Tensor", "boxes"),
        ("Tensor", "boxes_num"),
        ("int", "pooled_height"),
        ("int", "pooled_width"),
        ("float", "spatial_scale"),
        ("int", "sampling_ratio"),
        ("bool", "aligned"),
    ),
    (
        "roi_pool",
        ("Tensor", "x"),
        ("Tensor", "boxes"),
        ("Tensor", "boxes_num"),
        ("int", "pooled_height"),
        ("int", "pooled_width"),
        ("float", "spatial_scale"),
    ),
    ("roll", ("Tensor", "x"), ("IntArray", "shifts"), ("int64_t[]", "axis")),
    ("round", ("Tensor", "x")),
    (
        "rprop_",
        ("Tensor", "param"),
        ("Tensor", "grad"),
        ("Tensor", "prev"),
        ("Tensor", "learning_rate"),
        ("Tensor", "master_param"),
        ("Tensor", "learning_rate_range"),
        ("Tensor", "etas"),
        ("bool", "multi_precision"),
    ),
    (
        "rrelu",
        ("Tensor", "x"),
        ("float", "lower"),
        ("float", "upper"),
        ("bool", "is_test"),
    ),
    ("rsqrt", ("Tensor", "x")),
    (
        "scale",
        ("Tensor", "x"),
        ("Scalar", "scale"),
        ("Scalar", "bias"),
        ("bool", "bias_after_scale"),
    ),
    (
        "scatter",
        ("Tensor", "x"),
        ("Tensor", "index"),
        ("Tensor", "updates"),
        ("bool", "overwrite"),
    ),
    (
        "scatter_nd_add",
        ("Tensor", "x"),
        ("Tensor", "index"),
        ("Tensor", "updates"),
    ),
    (
        "searchsorted",
        ("Tensor", "sorted_sequence"),
        ("Tensor", "values"),
        ("bool", "out_int32"),
        ("bool", "right"),
    ),
    (
        "segment_pool",
        ("Tensor", "x"),
        ("Tensor", "segment_ids"),
        ("str", "pooltype"),
    ),
    ("selu", ("Tensor", "x"), ("float", "scale"), ("float", "alpha")),
    (
        "send_u_recv",
        ("Tensor", "x"),
        ("Tensor", "src_index"),
        ("Tensor", "dst_index"),
        ("str", "reduce_op"),
        ("IntArray", "out_size"),
    ),
    (
        "send_ue_recv",
        ("Tensor", "x"),
        ("Tensor", "y"),
        ("Tensor", "src_index"),
        ("Tensor", "dst_index"),
        ("str", "message_op"),
        ("str", "reduce_op"),
        ("IntArray", "out_size"),
    ),
    (
        "send_uv",
        ("Tensor", "x"),
        ("Tensor", "y"),
        ("Tensor", "src_index"),
        ("Tensor", "dst_index"),
        ("str", "message_op"),
    ),
    (
        "sequence_conv",
        ("Tensor", "x"),
        ("Tensor", "padding_data"),
        ("Tensor", "filter"),
        ("int", "context_length"),
        ("bool", "padding_trainable"),
        ("int", "context_start"),
        ("int", "context_stride"),
    ),
    (
        "sequence_mask",
        ("Tensor", "x"),
        ("Scalar(int)", "max_len"),
        ("DataType", "out_dtype"),
    ),
    (
        "set_value_with_tensor",
        ("Tensor", "x"),
        ("Tensor", "values"),
        ("IntArray", "starts"),
        ("IntArray", "ends"),
        ("IntArray", "steps"),
        ("int64_t[]", "axes"),
        ("int64_t[]", "decrease_axes"),
        ("int64_t[]", "none_axes"),
    ),
    (
        "sgd_",
        ("Tensor", "param"),
        ("Tensor", "learning_rate"),
        ("Tensor", "grad"),
        ("Tensor", "master_param"),
        ("bool", "multi_precision"),
    ),
    ("shape", ("Tensor", "input")),
    ("shape64", ("Tensor", "input")),
    (
        "shard_index",
        ("Tensor", "input"),
        ("int", "index_num"),
        ("int", "nshards"),
        ("int", "shard_id"),
        ("int", "ignore_value"),
    ),
    (
        "shuffle_batch",
        ("Tensor", "x"),
        ("Tensor", "seed"),
        ("int", "startup_seed"),
    ),
    ("shuffle_channel", ("Tensor", "x"), ("int", "group")),
    ("sigmoid", ("Tensor", "x")),
    (
        "sigmoid_cross_entropy_with_logits",
        ("Tensor", "x"),
        ("Tensor", "label"),
        ("Tensor", "pos_weight"),
        ("bool", "normalize"),
        ("int", "ignore_index"),
    ),
    ("sign", ("Tensor", "x")),
    ("silu", ("Tensor", "x")),
    ("sin", ("Tensor", "x")),
    ("sinh", ("Tensor", "x")),
    (
        "slice",
        ("Tensor", "input"),
        ("int64_t[]", "axes"),
        ("IntArray", "starts"),
        ("IntArray", "ends"),
        ("int64_t[]", "infer_flags"),
        ("int64_t[]", "decrease_axis"),
    ),
    ("slogdet", ("Tensor", "x")),
    ("softplus", ("Tensor", "x"), ("float", "beta"), ("float", "threshold")),
    ("softshrink", ("Tensor", "x"), ("float", "threshold")),
    ("softsign", ("Tensor", "x")),
    ("solve", ("Tensor", "x"), ("Tensor", "y")),
    (
        "sparse_attention",
        ("Tensor", "q"),
        ("Tensor", "k"),
        ("Tensor", "v"),
        ("Tensor", "offset"),
        ("Tensor", "columns"),
        ("Tensor", "key_padding_mask"),
        ("Tensor", "attn_mask"),
    ),
    (
        "spectral_norm",
        ("Tensor", "weight"),
        ("Tensor", "u"),
        ("Tensor", "v"),
        ("int", "dim"),
        ("int", "power_iters"),
        ("float", "eps"),
    ),
    (
        "split",
        ("Tensor", "x"),
        ("IntArray", "sections"),
        ("Scalar(int)", "axis"),
    ),
    (
        "split_with_num",
        ("Tensor", "x"),
        ("int", "num"),
        ("Scalar(int)", "axis"),
    ),
    ("sqrt", ("Tensor", "x")),
    ("square", ("Tensor", "x")),
    ("squared_l2_norm", ("Tensor", "x")),
    ("squeeze", ("Tensor", "x"), ("IntArray", "axis")),
    ("stack", ("Tensor[]", "x"), ("int", "axis")),
    ("standard_gamma", ("Tensor", "x")),
    ("stanh", ("Tensor", "x"), ("float", "scale_a"), ("float", "scale_b")),
    (
        "stft",
        ("Tensor", "x"),
        ("Tensor", "window"),
        ("int", "n_fft"),
        ("int", "hop_length"),
        ("bool", "normalized"),
        ("bool", "onesided"),
    ),
    (
        "strided_slice",
        ("Tensor", "x"),
        ("int[]", "axes"),
        ("IntArray", "starts"),
        ("IntArray", "ends"),
        ("IntArray", "strides"),
    ),
    (
        "sum",
        ("Tensor", "x"),
        ("IntArray", "axis"),
        ("DataType", "dtype"),
        ("bool", "keepdim"),
    ),
    ("svd", ("Tensor", "x"), ("bool", "full_matrices")),
    ("swiglu", ("Tensor", "x"), ("Tensor", "y")),
    ("swish", ("Tensor", "x")),
    (
        "sync_batch_norm_",
        ("Tensor", "x"),
        ("Tensor", "mean"),
        ("Tensor", "variance"),
        ("Tensor", "scale"),
        ("Tensor", "bias"),
        ("bool", "is_test"),
        ("float", "momentum"),
        ("float", "epsilon"),
        ("str", "data_format"),
        ("bool", "use_global_stats"),
        ("bool", "trainable_statistics"),
    ),
    (
        "take_along_axis",
        ("Tensor", "arr"),
        ("Tensor", "indices"),
        ("int", "axis"),
    ),
    ("tan", ("Tensor", "x")),
    ("tanh", ("Tensor", "x")),
    ("tanh_shrink", ("Tensor", "x")),
    (
        "tdm_child",
        ("Tensor", "x"),
        ("Tensor", "tree_info"),
        ("int", "child_nums"),
        ("DataType", "dtype"),
    ),
    (
        "tdm_sampler",
        ("Tensor", "x"),
        ("Tensor", "travel"),
        ("Tensor", "layer"),
        ("bool", "output_positive"),
        ("int[]", "neg_samples_num_list"),
        ("int[]", "layer_offset_lod"),
        ("int", "seed"),
        ("int", "dtype"),
    ),
    (
        "temporal_shift",
        ("Tensor", "x"),
        ("int", "seg_num"),
        ("float", "shift_ratio"),
        ("str", "data_format"),
    ),
    (
        "tensor_unfold",
        ("Tensor", "input"),
        ("int64_t", "axis"),
        ("int64_t", "size"),
        ("int64_t", "step"),
    ),
    ("thresholded_relu", ("Tensor", "x"), ("float", "threshold")),
    (
        "top_p_sampling",
        ("Tensor", "x"),
        ("Tensor", "ps"),
        ("Tensor", "threshold"),
        ("int", "seed"),
    ),
    (
        "topk",
        ("Tensor", "x"),
        ("Scalar(int)", "k"),
        ("int", "axis"),
        ("bool", "largest"),
        ("bool", "sorted"),
    ),
    (
        "trace",
        ("Tensor", "x"),
        ("int", "offset"),
        ("int", "axis1"),
        ("int", "axis2"),
    ),
    ("trans_layout", ("Tensor", "x"), ("int[]", "perm")),
    ("transpose", ("Tensor", "x"), ("int[]", "perm")),
    (
        "triangular_solve",
        ("Tensor", "x"),
        ("Tensor", "y"),
        ("bool", "upper"),
        ("bool", "transpose"),
        ("bool", "unitriangular"),
    ),
    ("tril", ("Tensor", "x"), ("int", "diagonal")),
    (
        "tril_indices",
        ("int", "rows"),
        ("int", "cols"),
        ("int", "offset"),
        ("DataType", "dtype"),
        ("Place", "place"),
    ),
    (
        "trilinear_interp",
        ("Tensor", "x"),
        ("Tensor", "out_size"),
        ("Tensor[]", "size_tensor"),
        ("Tensor", "scale_tensor"),
        ("str", "data_format"),
        ("int", "out_d"),
        ("int", "out_h"),
        ("int", "out_w"),
        ("float[]", "scale"),
        ("str", "interp_method"),
        ("bool", "align_corners"),
        ("int", "align_mode"),
    ),
    ("triu", ("Tensor", "x"), ("int", "diagonal")),
    (
        "triu_indices",
        ("int", "row"),
        ("int", "col"),
        ("int", "offset"),
        ("DataType", "dtype"),
        ("Place", "place"),
    ),
    ("trunc", ("Tensor", "input")),
    (
        "truncated_gaussian_random",
        ("int[]", "shape"),
        ("float", "mean"),
        ("float", "std"),
        ("int", "seed"),
        ("float", "a"),
        ("float", "b"),
        ("DataType", "dtype"),
        ("Place", "place"),
    ),
    ("unbind", ("Tensor", "input"), ("int", "axis")),
    (
        "unfold",
        ("Tensor", "x"),
        ("int[]", "kernel_sizes"),
        ("int[]", "strides"),
        ("int[]", "paddings"),
        ("int[]", "dilations"),
    ),
    (
        "uniform",
        ("IntArray", "shape"),
        ("DataType", "dtype"),
        ("Scalar", "min"),
        ("Scalar", "max"),
        ("int", "seed"),
        ("Place", "place"),
    ),
    (
        "uniform_inplace",
        ("Tensor", "x"),
        ("float", "min"),
        ("float", "max"),
        ("int", "seed"),
        ("int", "diag_num"),
        ("int", "diag_step"),
        ("float", "diag_val"),
    ),
    (
        "uniform_random_batch_size_like",
        ("Tensor", "input"),
        ("int[]", "shape"),
        ("int", "input_dim_idx"),
        ("int", "output_dim_idx"),
        ("float", "min"),
        ("float", "max"),
        ("int", "seed"),
        ("int", "diag_num"),
        ("int", "diag_step"),
        ("float", "diag_val"),
        ("DataType", "dtype"),
    ),
    (
        "unique_consecutive",
        ("Tensor", "x"),
        ("bool", "return_inverse"),
        ("bool", "return_counts"),
        ("int[]", "axis"),
        ("DataType", "dtype"),
    ),
    (
        "unpool",
        ("Tensor", "x"),
        ("Tensor", "indices"),
        ("int[]", "ksize"),
        ("int[]", "strides"),
        ("int[]", "padding"),
        ("IntArray", "output_size"),
        ("str", "data_format"),
    ),
    (
        "unpool3d",
        ("Tensor", "x"),
        ("Tensor", "indices"),
        ("int[]", "ksize"),
        ("int[]", "strides"),
        ("int[]", "paddings"),
        ("int[]", "output_size"),
        ("str", "data_format"),
    ),
    ("unsqueeze", ("Tensor", "x"), ("IntArray", "axis")),
    ("unstack", ("Tensor", "x"), ("int", "axis"), ("int", "num")),
    (
        "update_loss_scaling_",
        ("Tensor[]", "x"),
        ("Tensor", "found_infinite"),
        ("Tensor", "prev_loss_scaling"),
        ("Tensor", "in_good_steps"),
        ("Tensor", "in_bad_steps"),
        ("int", "incr_every_n_steps"),
        ("int", "decr_every_n_nan_or_inf"),
        ("float", "incr_ratio"),
        ("float", "decr_ratio"),
        ("Scalar", "stop_update"),
    ),
    ("view_dtype", ("Tensor", "input"), ("DataType", "dtype")),
    ("view_shape", ("Tensor", "input"), ("int64_t[]", "dims")),
    (
        "viterbi_decode",
        ("Tensor", "potentials"),
        ("Tensor", "transition_params"),
        ("Tensor", "lengths"),
        ("bool", "include_bos_eos_tag"),
    ),
    (
        "warpctc",
        ("Tensor", "logits"),
        ("Tensor", "label"),
        ("Tensor", "logits_length"),
        ("Tensor", "labels_length"),
        ("int", "blank"),
        ("bool", "norm_by_times"),
    ),
    (
        "warprnnt",
        ("Tensor", "input"),
        ("Tensor", "label"),
        ("Tensor", "input_lengths"),
        ("Tensor", "label_lengths"),
        ("int", "blank"),
        ("float", "fastemit_lambda"),
    ),
    (
        "weight_dequantize",
        ("Tensor", "x"),
        ("Tensor", "scale"),
        ("str", "algo"),
        ("DataType", "out_dtype"),
        ("int", "group_size"),
    ),
    (
        "weight_only_linear",
        ("Tensor", "x"),
        ("Tensor", "weight"),
        ("Tensor", "bias"),
        ("Tensor", "weight_scale"),
        ("str", "weight_dtype"),
        ("int", "arch"),
        ("int", "group_size"),
    ),
    (
        "weight_quantize",
        ("Tensor", "x"),
        ("str", "algo"),
        ("int", "arch"),
        ("int", "group_size"),
    ),
    (
        "weighted_sample_neighbors",
        ("Tensor", "row"),
        ("Tensor", "colptr"),
        ("Tensor", "edge_weight"),
        ("Tensor", "input_nodes"),
        ("Tensor", "eids"),
        ("int", "sample_size"),
        ("bool", "return_eids"),
    ),
    ("where", ("Tensor", "condition"), ("Tensor", "x"), ("Tensor", "y")),
    (
        "yolo_box",
        ("Tensor", "x"),
        ("Tensor", "img_size"),
        ("int[]", "anchors"),
        ("int", "class_num"),
        ("float", "conf_thresh"),
        ("int", "downsample_ratio"),
        ("bool", "clip_bbox"),
        ("float", "scale_x_y"),
        ("bool", "iou_aware"),
        ("float", "iou_aware_factor"),
    ),
    (
        "yolo_box_head",
        ("Tensor", "x"),
        ("int[]", "anchors"),
        ("int", "class_num"),
    ),
    (
        "yolo_box_post",
        ("Tensor", "boxes0"),
        ("Tensor", "boxes1"),
        ("Tensor", "boxes2"),
        ("Tensor", "image_shape"),
        ("Tensor", "image_scale"),
        ("int[]", "anchors0"),
        ("int[]", "anchors1"),
        ("int[]", "anchors2"),
        ("int", "class_num"),
        ("float", "conf_thresh"),
        ("int", "downsample_ratio0"),
        ("int", "downsample_ratio1"),
        ("int", "downsample_ratio2"),
        ("bool", "clip_bbox"),
        ("float", "scale_x_y"),
        ("float", "nms_threshold"),
    ),
    (
        "yolo_loss",
        ("Tensor", "x"),
        ("Tensor", "gt_box"),
        ("Tensor", "gt_label"),
        ("Tensor", "gt_score"),
        ("int[]", "anchors"),
        ("int[]", "anchor_mask"),
        ("int", "class_num"),
        ("float", "ignore_thresh"),
        ("int", "downsample_ratio"),
        ("bool", "use_label_smooth"),
        ("float", "scale_x_y"),
    ),
    ("zeros", ("IntArray", "shape"), ("DataType", "dtype"), ("Place", "place")),
    ("zeros_like", ("Tensor", "x"), ("DataType", "dtype"), ("Place", "place")),
    (
        "chunk_eval",
        ("Tensor", "inference"),
        ("Tensor", "label"),
        ("Tensor", "seq_length"),
        ("int", "num_chunk_types"),
        ("str", "chunk_scheme"),
        ("int[]", "excluded_chunk_types"),
    ),
    (
        "moe",
        ("Tensor", "x"),
        ("Tensor", "gate"),
        ("Tensor", "bmm0"),
        ("Tensor", "bias0"),
        ("Tensor", "bmm1"),
        ("Tensor", "bias1"),
        ("str", "act_type"),
    ),
    ("number_count", ("Tensor", "numbers"), ("int", "upper_range")),
]

op_name_x_arg_names = phi_ops_yaml_legacy_static_ops + phi_ops_yaml_ops
