# Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# =====================================
# VjpInterface gen op list
# =====================================
# we don't support vjp function code
# gen now, so we use a whitelist to
# control the generation of Vjp methods.
# TODO(wanghao107)
# remove this file and support Vjp methods
# code gen.


vjp_interface_declare_gen_op_list = [
    'where',
    "tanh",
    "mean",
    "divide",
    "sum",
    "add",
    "concat",
    "split",
    "split_with_num",
    "gelu",
    "matmul",
    "erf",
    "multiply",
    "pow",
    "rsqrt",
    "subtract",
    "square",
    "dropout",
    'exp',
    'expm1',
    'expand',
    'layer_norm',
    'reshape',
    'cast',
    "scale",
    'softmax',
    'silu',
    'elementwise_pow',
    'embedding',
    'fused_softmax_mask_upper_triangle',
    'slice',
    'transpose',
    'slice_grad',
    'gather_nd',
    'stack',
    'poisson',
    'gumbel_softmax',
    'pad',
    'pad3d',
    'squeeze',
    'unsqueeze',
    'tril',
    'triu',
    'squeeze',
    'unsqueeze',
    'conv2d',
    'depthwise_conv2d',
    'sqrt',
    'flatten',
    'relu',
    'abs',
    'log',
    'clip',
    'ceil',
    'p_norm',
    'maximum',
    'argsort',
    'min',
    'batch_norm',
    'max_pool2d_with_index',
    'pool2d',
    'minimum',
    'prod',
    'round',
    'sin',
    'cos',
    'dot',
    'floor',
    'topk',
    'square',
    'gather',
    'label_smooth',
    'cross_entropy_with_softmax',
    'mean_all',
    'cumsum',
    'linear_interp',
    'bilinear_interp',
    'trilinear_interp',
    'nearest_interp',
    'bicubic_interp',
    'assign',
    'assign_out_',
    'real',
    'flip',
    'softmax',
    'expand',
    'conv2d_transpose',
    'depthwise_conv2d_transpose',
    'sigmoid',
    'pad',
    'pad3d',
    'einsum',
    'leaky_relu',
    'log10',
    'conv3d',
    'solve',
    'diag',
    'trace',
    'tile',
]
vjp_interface_implementation_gen_op_list = [
    'where',
    "tanh",
    "mean",
    "divide",
    "sum",
    "add",
    "concat",
    "split",
    "split_with_num",
    "gelu",
    "matmul",
    "erf",
    "multiply",
    "subtract",
    "pow",
    "rsqrt",
    "square",
    "dropout",
    'exp',
    'expm1',
    'expand',
    'layer_norm',
    'reshape',
    'cast',
    "scale",
    'softmax',
    'silu',
    'elementwise_pow',
    'embedding',
    'fused_softmax_mask_upper_triangle',
    'slice',
    'transpose',
    'slice_grad',
    'gather_nd',
    'stack',
    'poisson',
    'gumbel_softmax',
    'pad',
    'pad3d',
    'squeeze',
    'unsqueeze',
    'tril',
    'triu',
    'squeeze',
    'unsqueeze',
    'conv2d',
    'depthwise_conv2d',
    'sqrt',
    'flatten',
    'relu',
    'abs',
    'log',
    'clip',
    'ceil',
    'p_norm',
    'maximum',
    'argsort',
    'min',
    'batch_norm',
    'max_pool2d_with_index',
    'pool2d',
    'minimum',
    'prod',
    'round',
    'sin',
    'cos',
    'dot',
    'floor',
    'topk',
    'square',
    'gather',
    'label_smooth',
    'cross_entropy_with_softmax',
    'mean_all',
    'cumsum',
    'linear_interp',
    'bilinear_interp',
    'trilinear_interp',
    'nearest_interp',
    'bicubic_interp',
    'assign',
    'assign_out_',
    'real',
    'flip',
    'softmax',
    'expand',
    'conv2d_transpose',
    'depthwise_conv2d_transpose',
    'sigmoid',
    'pad',
    'pad3d',
    'einsum',
    'leaky_relu',
    'log10',
    'conv3d',
    'solve',
    'diag',
    'trace',
    'tile',
]
