register_unity_group(cc
    reshape_p_op.cc
    broadcast_p_op.cc
    reduce_p_op.cc
    transpose_p_op.cc
    split_p_op.cc
    concat_p_op.cc
    slice_select_p_op.cc
    slice_assign_p_op.cc
    gather_p_op.cc
    scatter_add_p_op.cc
    add_p_op.cc
    sub_p_op.cc
    mul_p_op.cc
    div_p_op.cc
    sqrt_p_op.cc
    tanh_p_op.cc
    matmul_p_op.cc
    fill_constant_p_op.cc
    )
