# A image for building paddle binaries
# Use cuda devel base image for both cpu and gpu environment
# When you modify it, please be aware of cudnn-runtime version
ARG CUDA_VERSION=13.2
ARG BASE_TARGET=cuda${CUDA_VERSION}

FROM nvcr.io/nvidia/cuda:13.2.0-cudnn-devel-ubuntu24.04 as base
MAINTAINER PaddlePaddle Authors <paddle-dev@baidu.com>


# ENV variables
ARG WITH_GPU
ARG WITH_AVX
ARG PYTHON_VERSION=3.12
ARG TARGETARCH

ENV WITH_GPU=${WITH_GPU:-ON}
ENV WITH_AVX=${WITH_AVX:-ON}
ENV DEBIAN_FRONTEND=noninteractive
ENV LD_LIBRARY_PATH=/usr/local/cuda-13.2/compat:/usr/local/cuda-13.2/targets/x86_64-linux/lib:/usr/local/cuda-13.2/targets/sbsa-linux/lib:/usr/local/cuda-13.2/targets/aarch64-linux/lib:/usr/local/cuda-13.2/lib64:$LD_LIBRARY_PATH

ENV HOME /root

RUN apt-get update --allow-unauthenticated && \
    apt-get install -y --no-install-recommends \
      git \
      vim \
      curl \
      wget \
      make \
      libgl1 \
      libglib2.0-0 \
      libssl-dev \
      autoconf \
      automake \
      libtool \
      libmlx5-1 \
      libibverbs-dev \
      ccache \
      python${PYTHON_VERSION} \
      python${PYTHON_VERSION}-dev \
      python3-pip \
      libnccl2=2.29.7-1+cuda13.2 \
      libnccl-dev=2.29.7-1+cuda13.2 && \
    ln -sf /usr/bin/python3 /usr/bin/python && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /home
RUN set -eux; \
        if [ "${TARGETARCH:-}" = "amd64" ] || [ "$(uname -m)" = "x86_64" ]; then \
            CMAKE_ARCH="x86_64"; \
        elif [ "${TARGETARCH:-}" = "arm64" ] || [ "$(uname -m)" = "aarch64" ]; then \
            CMAKE_ARCH="aarch64"; \
        else \
            echo "Unsupported architecture: TARGETARCH=${TARGETARCH:-unknown}, uname -m=$(uname -m)"; \
            exit 1; \
        fi; \
        CMAKE_PKG="cmake-3.31.0-linux-${CMAKE_ARCH}.tar.gz"; \
        wget -q "https://cmake.org/files/v3.31/${CMAKE_PKG}"; \
        tar -zxf "${CMAKE_PKG}"; \
        rm "${CMAKE_PKG}"; \
        mv "/home/cmake-3.31.0-linux-${CMAKE_ARCH}" /home/cmake-3.31.0; \
        rm -rf /home/cmake-3.31.0/doc /home/cmake-3.31.0/man

ENV PATH=/home/cmake-3.31.0/bin:$PATH


ARG TMP_DIR=patchelf_tmp
RUN rm -rf "$TMP_DIR" && git clone --depth 1 --branch 0.15.0 https://github.com/NixOS/patchelf "$TMP_DIR" && \
    cd "$TMP_DIR" && ./bootstrap.sh && \
    ./configure && make && make install && \
    cd .. && rm -rf "$TMP_DIR"


COPY paddle/scripts/compile_requirements.txt /root
COPY python/requirements.txt /root
RUN pip config set global.break-system-packages true && \
    pip install --break-system-packages -r /root/requirements.txt && \
    pip install --break-system-packages -r /root/compile_requirements.txt && \
    rm -rf /root/compile_requirements.txt /root/requirements.txt
