// Header file generated by paddle/phi/CMakeLists.txt for external users,
// DO NOT edit or include it within paddle.

#pragma once

#include "paddle/phi/config.h"

#include "paddle/phi/include/backends.h"
#include "paddle/phi/include/core.h"
#include "paddle/phi/include/infermeta.h"
#include "paddle/phi/include/kernels.h"
