apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: vgg16job-pserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        tf-job-pserver: vgg16job
    spec:
      hostNetwork: true
      imagePullSecrets:
      #- name: job-registry-secret
      - name: gongweibaobaidusecret
      containers:
      - name: pserver
        image: "registry.baidu.com/gongweibao/test/fluid_benchmark:vgg16"
        imagePullPolicy: Always
        command: ["tf_k8s", "start_tf"]
        ports:
        - name: jobport-30236
          containerPort: 30236
        env:
        - name: PORT
          value: "32036"
        - name: ENTRY
          value: "python vgg16_tf.py"
        - name: JOB_NAME
          value: vgg16job
        - name: PSERVERS_NUM
          value: "1"
        - name: TRAINING_ROLE
          value: "PSERVER"
        - name: TRAINERS_NUM
          value: "1"
        - name: BATCH_SIZE
          value: "128"
        - name: TRAINER_PACKAGE
          value: "/workspace"
        - name: NUM_PASSES
          value: "1"
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: "status.podIP"
        resources:
          requests:
            memory: 10Gi
            cpu: 4
          limits:
            memory: 10Gi
            cpu: 4
