// Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include "paddle/fluid/translator/op_compat_info.h"

namespace paddle {
namespace translator {

OpNameNormalizer::OpNameNormalizer() {
  op_name_mappings = {
      {"elementwise_add", "add"},
      {"elementwise_add_grad", "add_grad"},
      {"sum", "add_n"},
      {"reduce_all", "all"},
      {"reduce_amax", "amax"},
      {"reduce_amax_grad", "amax_grad"},
      {"reduce_amin", "amin"},
      {"reduce_amin_grad", "amin_grad"},
      {"reduce_any", "any"},
      {"range", "arange"},
      {"arg_max", "argmax"},
      {"arg_min", "argmin"},
      {"bicubic_interp_v2", "bicubic_interp"},
      {"bicubic_interp_v2_grad", "bicubic_interp_grad"},
      {"bilinear_tensor_product", "bilinear"},
      {"bilinear_interp_v2", "bilinear_interp"},
      {"bilinear_interp_v2_grad", "bilinear_interp_grad"},
      {"celu_grad_grad", "celu_grad, celu_double_grad"},
      {"conv3d_grad_grad", "conv3d_grad, conv3d_double_grad"},
      {"crop_tensor", "crop"},
      {"crop_tensor_grad", "crop_grad"},
      {"softmax_with_cross_entropy", "cross_entropy_with_softmax"},
      {"softmax_with_cross_entropy_grad", "cross_entropy_with_softmax_grad"},
      {"depthwise_conv2d_grad_grad",
       "depthwise_conv2d_grad, depthwise_conv2d_double_grad"},
      {"determinant", "det"},
      {"determinant_grad", "det_grad"},
      {"diag_v2", "diag"},
      {"diag_v2_grad", "diag_grad"},
      {"elementwise_div", "divide_grad"},
      {"elu_grad_grad", "elu_grad, elu_double_grad"},
      {"lookup_table_v2", "embedding"},
      {"lookup_table_v2_grad", "embedding_grad"},
      {"expand_v2", "expand"},
      {"expand_v2_grad", "expand_grad"},
      {"expand_as_v2", "expand_as"},
      {"expand_as_v2_grad", "expand_as_grad"},
      {"flatten_contiguous_range", "flatten"},
      {"flatten_contiguous_range_grad", "flatten_grad"},
      {"elementwise_floordiv", "floor_divide"},
      {"elementwise_fmax", "fmax"},
      {"elementwise_fmax_grad", "fmax_grad"},
      {"elementwise_fmin", "fmin"},
      {"elementwise_fmin_grad", "fmin_grad"},
      {"fill_constant", "full"},
      {"fill_any_like", "full_like"},
      {"gaussian_random", "gaussian"},
      {"generate_proposals_v2", "generate_proposals"},
      {"grid_sampler", "grid_sample"},
      {"grid_sampler_grad", "grid_sample_grad"},
      {"hard_shrink", "hardshrink"},
      {"hard_shrink_grad", "hardshrink_grad"},
      {"hard_sigmoid", "hardsigmoid"},
      {"hard_sigmoid_grad", "hardsigmoid_grad"},
      {"hard_swish", "hardswish"},
      {"hard_swish_grad", "hardswish_grad"},
      {"brelu", "hardtanh"},
      {"brelu_grad", "hardtanh_grad"},
      {"elementwise_heaviside", "heaviside"},
      {"elementwise_heaviside_grad", "heaviside_grad"},
      {"isfinite_v2", "isfinite"},
      {"isinf_v2", "isinf"},
      {"isnan_v2", "isnan"},
      {"leaky_relu_grad_grad", "leaky_relu_grad, leaky_relu_double_grad"},
      {"linear_interp_v2", "linear_interp"},
      {"linear_interp_v2_grad", "linear_interp_grad"},
      {"log_grad_grad", "log_grad, log_double_grad"},
      {"matmul_v2", "matmul"},
      {"matmul_v2_grad", "matmul_grad"},
      {"mul", "matmul_with_flatten"},
      {"mul_grad", "matmul_with_flatten_grad"},
      {"reduce_max", "max"},
      {"reduce_max_grad", "max_grad"},
      {"elementwise_max", "maximum"},
      {"elementwise_max_grad", "maximum_grad"},
      {"reduce_mean", "mean"},
      {"reduce_mean_grad", "mean_grad"},
      {"mean", "mean_all"},
      {"mean_grad", "mean_all_grad"},
      {"elementwise_min", "minimum"},
      {"elementwise_min_grad", "minimum_grad"},
      {"elementwise_mul", "multiply"},
      {"elementwise_mul_grad", "multiply_grad"},
      {"nearest_interp_v2", "nearest_interp"},
      {"nearest_interp_v2_grad", "nearest_interp_grad"},
      {"where_index", "nonzero"},
      {"size", "numel"},
      {"one_hot_v2", "one_hot"},
      {"reduce_prod", "prod"},
      {"reduce_prod_grad", "prod_grad"},
      {"relu_grad_grad", "relu_grad, relu_double_grad"},
      {"elementwise_mod", "remainder"},
      {"reshape2", "reshape"},
      {"reshape2_grad", "reshape_grad"},
      {"rsqrt_grad_grad", "rsqrt_grad, rsqrt_double_grad"},
      {"graph_send_recv", "send_u_recv"},
      {"graph_send_recv_grad", "send_u_recv_grad"},
      {"graph_send_ue_recv", "send_ue_recv"},
      {"graph_send_ue_recv_grad", "send_ue_recv_grad"},
      {"graph_send_uv", "send_uv"},
      {"graph_send_uv_grad", "send_uv_grad"},
      {"sigmoid_grad_grad", "sigmoid_grad, sigmoid_double_grad"},
      {"slogdeterminant", "slogdet"},
      {"slogdeterminant_grad", "slogdet_grad"},
      {"sqrt_grad_grad", "sqrt_grad, sqrt_double_grad"},
      {"square_grad_grad", "square_grad, square_double_grad"},
      {"squeeze2", "squeeze"},
      {"squeeze2_grad", "squeeze_grad"},
      {"elementwise_sub", "subtract"},
      {"elementwise_sub_grad", "subtract_grad"},
      {"reduce_sum", "sum"},
      {"sum_grad", ""},
      {"tanh_grad_grad", "tanh_grad, tanh_double_grad"},
      {"top_k_v2", "topk"},
      {"top_k_v2_grad", "topk_grad"},
      {"transpose2", "transpose"},
      {"transpose2_grad", "transpose_grad"},
      {"trilinear_interp_v2", "trilinear_interp"},
      {"trilinear_interp_v2_grad", "trilinear_interp_grad"},
      {"uniform_random", "uniform"},
      {"uniform_random_inplace", "uniform_inplace"},
      {"uniform_random_inplace_grad", "uniform_inplace_grad"},
      {"unsqueeze2", "unsqueeze"},
      {"unsqueeze2_grad", "unsqueeze_grad"},
      {"yolov3_loss", "yolo_loss"},
      {"yolov3_loss_grad", "yolo_loss_grad"},
      {"graph_reindex", "reindex_graph"},
  };
}

}  // namespace translator
}  // namespace paddle
