version: 1.0
pruners:
    pruner_1:
        class: 'StructurePruner'
        pruning_axis:
            '*': 0
        criterions:
            '*': 'l1_norm'
strategies:
    strategy_1:
        class: 'SensitivePruneStrategy'
        pruner: 'pruner_1'
        start_epoch: 0
        end_epoch: 1
        delta_rate: 0.2
        target_ratio: 0.2
        pruned_params: 'conv2d_.*.w_.*'
        sensitivities_file: 'sensitivities.data'
        metric_name: 'acc'
compress_pass:
    epoch: 100
    strategies:
        - strategy_1
