version: 1.0
include: ["./unitest/configs/pruners.yaml", "./unitest/configs/pruners_0.yaml", "./unitest/configs/quantizers.yaml"]
pruners:
    pruner_1:
        class: 'RatioPruner'
        ratios:
            'conv1_1.w': 0.3
            'conv1_2.w': 0.4
            '*': 0.9
        group_dims:
            '*': [1, 2, 3]
        criterions:
            '*': 'l1-norm'
strategies:
    strategy_1:
        class: 'SensitivePruneStrategy'
        pruner: 'pruner_2'
        start_epoch: 0
        end_epoch: 10
        delta_rate: 0.20
        acc_loss_threshold: 0.2
        sensitivities:
            'conv1_1.w': 0.4
    strategy_2:
        class: 'QuantizationStrategy'
        quantizer: 'quantizer_2'
        start_epoch: 0
        end_epoch: 10
        dirname: None
        target_device: 'mobile'
        save_as_int8: False

compress_pass:
    class: 'CompressPass'
    epoch: 100
    strategies:
        - strategy_1
        - strategy_2
