version: 1.0
pruners:
    pruner_2:
        class: 'RatioPruner'
        ratios:
            'conv1_1.w': 0.5
            'conv1_2.w': 0.2
            '*': 0.7
        group_dims:
            '*': [1, 2, 3]
        criterions:
            '*': 'l1-norm'
