from __future__ import annotations

class CPUPlace: ...

class CUDAPlace:
    def __init__(self, name: int, /) -> None: ...

class CUDAPinnedPlace: ...

class NPUPlace:
    def __init__(self, name: int, /) -> None: ...

class IPUPlace: ...

class CustomPlace:
    def __init__(self, name: str, id: int, /) -> None: ...

class MLUPlace:
    def __init__(self, id: int, /) -> None: ...

class XPUPlace:
    def __init__(self, id: int, /) -> None: ...
