type: "conv3d"
def {
  inputs {
    name: "Input"
  }
  inputs {
    name: "Filter"
  }
  inputs {
    name: "ResidualData"
  }
  outputs {
    name: "Output"
  }
  attrs {
    name: "strides"
    type: INTS
  }
  attrs {
    name: "paddings"
    type: INTS
  }
  attrs {
    name: "padding_algorithm"
    type: STRING
  }
  attrs {
    name: "groups"
    type: INT
  }
  attrs {
    name: "dilations"
    type: INTS
  }
  attrs {
    name: "data_format"
    type: STRING
  }
}
extra {
  attrs {
    name: "fuse_relu_before_depthwise_conv"
    type: BOOLEAN
  }
  attrs {
    name: "fuse_relu"
    type: BOOLEAN
  }
  attrs {
    name: "fuse_activation"
    type: STRING
  }
  attrs {
    name: "fuse_alpha"
    type: FLOAT
  }
  attrs {
    name: "fuse_beta"
    type: FLOAT
  }
  attrs {
    name: "use_addto"
    type: BOOLEAN
  }
  attrs {
    name: "fuse_residual_connection"
    type: BOOLEAN
  }
  attrs {
    name: "force_fp32_output"
    type: BOOLEAN
  }
  attrs {
    name: "workspace_size_MB"
    type: INT
  }
  attrs {
    name: "exhaustive_search"
    type: BOOLEAN
  }
}

