type: "depthwise_conv2d"
def {
  inputs {
    name: "Input"
  }
  inputs {
    name: "Filter"
  }
  outputs {
    name: "Output"
  }
  attrs {
    name: "strides"
    type: INTS
  }
  attrs {
    name: "paddings"
    type: INTS
  }
  attrs {
    name: "padding_algorithm"
    type: STRING
  }
  attrs {
    name: "groups"
    type: INT
  }
  attrs {
    name: "dilations"
    type: INTS
  }
  attrs {
    name: "data_format"
    type: STRING
  }
}
extra {
  attrs {
    name: "Input_scale"
    type: FLOAT
  }
  attrs {
    name: "quantization_type"
    type: STRING
  }
  attrs {
    name: "bit_length"
    type: INT
  }
  attrs {
    name: "out_threshold"
    type: FLOAT
  }
  attrs {
    name: "skip_quant"
    type: BOOLEAN
  }
  attrs {
    name: "fuse_relu_before_depthwise_conv"
    type: BOOLEAN
  }
  attrs {
    name: "use_addto"
    type: BOOLEAN
  }
  attrs {
    name: "workspace_size_MB"
    type: INT
  }
  attrs {
    name: "exhaustive_search"
    type: BOOLEAN
  }
}
