type: "elementwise_pow"
def {
  inputs {
    name: "X"
  }
  inputs {
    name: "Y"
  }
  outputs {
    name: "Out"
  }
  attrs {
    name: "axis"
    type: INT
  }
}
extra {
  attrs {
    name: "x_data_format"
    type: STRING
  }
  attrs {
    name: "y_data_format"
    type: STRING
  }
  attrs {
    name: "Scale_x"
    type: FLOAT
  }
  attrs {
    name: "Scale_y"
    type: FLOAT
  }
  attrs {
    name: "Scale_out"
    type: FLOAT
  }
  attrs {
    name: "act"
    type: STRING
  }
}
