type: "fake_channel_wise_quantize_abs_max"
def {
  inputs {
    name: "X"
  }
  outputs {
    name: "Out"
  }
  outputs {
    name: "OutScale"
  }
  attrs {
    name: "quant_axis"
    type: INT
  }
  attrs {
    name: "bit_length"
    type: INT
  }
}
