type: "fused_transpose"
def {
  inputs {
    name: "X"
  }
  outputs {
    name: "Out"
  }
  outputs {
    name: "XShape"
  }
  attrs {
    name: "axis"
    type: INTS
  }
}
extra {
  attrs{
    name: "fused_squeeze2_axes"
    type: INTS
  }
  attrs{
    name: "fused_unsqueeze2_axes"
    type: INTS
  }
  attrs{
    name: "fused_reshape2_shape"
    type: INTS
  }
  attrs{
    name: "scale"
    type: FLOAT
  }
  attrs{
    name: "shift"
    type: FLOAT
  }
  attrs{
    name: "output_data_type"
    type: STRING
  }
}
