type: "fused_softplus"
def {
  inputs {
    name: "X"
  }
  outputs {
    name: "Out"
  }
  attrs {
    name: "beta"
    type: FLOAT
  }
  attrs {
    name: "threshold"
    type: FLOAT
  }
}
extra {
  attrs {
    name: "fuse_activation"
    type: STRING
  }
  attrs {
    name: "fuse_alpha"
    type: FLOAT
  }
  attrs {
    name: "fuse_beta"
    type: FLOAT
  }
}
