type: "fused_fc"
def {
  inputs {
    name: "Input"
  }
  inputs {
    name: "W"
  }
  inputs {
    name: "Bias"
  }
  inputs {
    name: "ResidualData"
  }
  outputs {
    name: "Out"
  }
  attrs {
    name: "in_num_col_dims"
    type: INT
  }
  attrs {
    name: "activation_type"
    type: STRING
  }
}
extra {
  attrs {
    name: "padding_weights"
    type: BOOLEAN
  }
  attrs {
    name: "use_mkldnn"
    type: BOOLEAN
  }
  attrs {
    name: "mkldnn_data_type"
    type: STRING
  }
  attrs {
    name: "fuse_activation"
    type: STRING
  }
  attrs {
    name: "fuse_alpha"
    type: FLOAT
  }
  attrs {
    name: "fuse_beta"
    type: FLOAT
  }
  attrs {
    name: "fused_output_scale"
    type: FLOAT
  }
  attrs {
    name: "fused_reshape2_shape"
    type: INTS
  }
  attrs {
    name: "@ALL_KERNELS_MUST_COMPUTE_RUNTIME_SHAPE@"
    type: BOOLEAN
  }
  attrs {
    name: "Scale_in"
    type: FLOAT
  }
  attrs {
    name: "Scale_weights"
    type: FLOATS
  }
  attrs {
    name: "Bias_scales"
    type: FLOAT
  }
  attrs {
    name: "Scale_in_eltwise"
    type: FLOAT
  }
  attrs {
    name: "Scale_out"
    type: FLOAT
  }
  attrs {
    name: "force_fp32_output"
    type: BOOLEAN
  }
}
