type: "leaky_relu"
def {
  inputs {
    name: "X"
  }
  outputs {
    name: "Out"
  }
  attrs {
    name: "alpha"
    type: FLOAT
  }
}
extra {
  attrs {
    name: "use_mkldnn"
    type: BOOLEAN
  }
  attrs {
    name: "name"
    type: STRING
  }
  attrs {
    name: "@ENABLE_CACHE_RUNTIME_CONTEXT@"
    type: BOOLEAN
  }
  attrs {
    name: "is_test"
    type: BOOLEAN
  }
  attrs {
    name: "op_role"
    type: INT
  }
  attrs {
    name: "op_role_var"
    type: STRINGS
  }
  attrs {
    name: "op_namescope"
    type: STRING
  }
  attrs {
    name: "op_callstack"
    type: STRINGS
  }
  attrs {
    name: "op_device"
    type: STRING
  }
}

