type: "relu"
def {
  inputs {
    name: "X"
  }
  outputs {
    name: "Out"
  }
}
extra {
  attrs {
    name: "X0_threshold"
    type: FLOAT
  }
  attrs {
    name: "X0_threshold"
    type: FLOAT
  }
  attrs {
    name: "out_threshold"
    type: FLOAT
  }
  attrs {
    name: "Out0_threshold"
    type: FLOAT
  }
}
