type: "scale"
def {
  inputs {
    name: "X"
  }
  outputs {
    name: "Out"
  }
  attrs {
    name: "bias"
    type: FLOAT
  }
  attrs {
    name: "scale"
    type: FLOAT
  }
  attrs {
    name: "bias_after_scale"
    type: BOOLEAN
  }
}
extra {
  attrs {
    name: "name"
    type: STRING
  }
  attrs {
    name: "use_mkldnn"
    type: BOOLEAN
  }
  attrs {
    name: "op_role"
    type: INT
  }
  attrs {
    name: "op_role_var"
    type: STRINGS
  }
  attrs {
    name: "op_namescope"
    type: STRING
  }
  attrs {
    name: "op_callstack"
    type: STRINGS
  }
  attrs {
    name: "op_device"
    type: STRING
  }
}
