type: "sequence_conv"
def {
  inputs {
    name: "X"
  }
  inputs {
    name: "Filter"
  }
  outputs {
    name: "Out"
  }
}
extra {
  inputs {
    name: "PaddingData"
  }
  attrs {
    name: "paddingTrainable"
    type: BOOLEAN
  }
   attrs {
    name: "contextLength"
    type: INT
   }
   attrs {
    name: "contextStart"
    type: INT
   }
   attrs {
    name: "contextStride"
    type: INT
   }
   
}
