type: "sequence_conv"
def {
  inputs {
    name: "X"
  }
  inputs {
    name: "Filter"
  }
  inputs {
    name: "PaddingData"
  }
  outputs {
    name: "Out"
  }
  attrs {
    name: "contextLength"
    type: INT
   }
  attrs {
    name: "contextStart"
    type: INT
   }
  attrs {
    name: "contextStride"
    type: INT
   }
}
extra {
  attrs {
    name: "paddingTrainable"
    type: BOOLEAN
  }
  attrs {
    name: "op_role"
    type: INT
  }
  attrs {
    name: "op_role_var"
    type: STRINGS
  }
  attrs {
    name: "op_namescope"
    type: STRING
  }
  attrs {
    name: "op_callstack"
    type: STRINGS
  }
  attrs {
    name: "op_device"
    type: STRING
  }
}
