name: Model-benchmark

on:
  workflow_call:
    inputs:
      docker_doc_image:
        type: string
        required: true
      can-skip:
        type: string
        required: false

env:
  PR_ID: ${{ github.event.pull_request.number }}
  COMMIT_ID: ${{ github.event.pull_request.head.sha }}
  ci_scripts: /workspace/paddle/ci
  BRANCH: ${{ github.event.pull_request.base.ref }}
  TASK: paddle-CI-${{ github.event.pull_request.number }}-Doc-Preview
  CI_name: Doc-Preview
  no_proxy: "bcebos.com,apiin.im.baidu.com,gitee.com,aliyun.com,.baidu.com,.tuna.tsinghua.edu.cn"

defaults:
  run:
    shell: bash

jobs:
  check-bypass:
    name: Check bypass for Doc-Preview
    uses: ./.github/workflows/check-bypass.yml
    with:
      workflow-name: 'Doc-Preview'
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  check-doc:
    name: Check doc
    runs-on:
      group: GZ_BD-CPU
    steps:
      - name: Check docker image  and run container
        env:
          WITH_SHARED_PHI: "ON"
          WITH_MKL: "OFF"
          WITH_TESTING: "ON"
          COVERALLS_UPLOAD: "OFF"
          GIT_PR_ID: ${{ github.event.pull_request.number }}
          PADDLE_VERSION: 0.0.0
          WITH_DISTRIBUTE: "ON"
          PREC_SUFFIX: .py3
          WITH_UNITY_BUILD: "ON"
          PY_VERSION: 3.9
          PROC_RUN: 12
          FLAGS_enable_eager_mode: 1
          WITH_TENSORRT: "OFF"
          GENERATOR: "Ninja"
          CCACHE_MAXSIZE: 150G
          CCACHE_LIMIT_MULTIPLE: 0.8
          WITH_AVX: "OFF"
          CACHE_DIR: "/root/.cache/cpu"
          CCACHE_DIR: "/root/.ccache/cpu"
        run: |
          container_name=${TASK}-$(date +%Y%m%d-%H%M%S)
          echo "container_name=${container_name}" >> ${{ github.env }}
          docker_image=${{ inputs.docker_doc_image }}
          docker run -d -t --name ${container_name} \
            -v "/home/data/cfs:/home/data/cfs" \
            -v "/home/data/cfs/.cache/doc:/root/.cache" \
            -v "/home/data/cfs/.ccache:/root/.ccache" \
            -v "/dev/shm:/dev/shm"  \
            -v ${{ github.workspace }}/../../..:${{ github.workspace }}/../../.. \
            -v ${{ github.workspace }}:/paddle \
            -e BRANCH \
            -e PR_ID \
            -e COMMIT_ID \
            -e work_dir \
            -e PADDLE_ROOT \
            -e WITH_SHARED_PHI \
            -e WITH_MKL \
            -e WITH_TESTING \
            -e COVERALLS_UPLOAD \
            -e GIT_PR_ID \
            -e PADDLE_VERSION \
            -e WITH_DISTRIBUTE \
            -e PREC_SUFFIX \
            -e WITH_UNITY_BUILD \
            -e PY_VERSION \
            -e PROC_RUN \
            -e FLAGS_enable_eager_mode \
            -e WITH_TENSORRT \
            -e GENERATOR \
            -e CCACHE_MAXSIZE \
            -e CCACHE_LIMIT_MULTIPLE \
            -e GITHUB_ENV \
            -e ci_scripts \
            -e WITH_AVX \
            -e CACHE_DIR \
            -e CCACHE_DIR \
            -e CI_name \
            -e no_proxy \
            -w /paddle --network host ${docker_image}

      - name: Check doc preview
        env:
          AGILE_PULL_ID: ${{ github.event.pull_request.number }}
          AGILE_REVISION: ${{ github.event.pull_request.head.sha }}
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -c '
          rm -rf  * .[^.]*
          wget -q --no-proxy https://xly-devops.bj.bcebos.com/PR/build_whl/${AGILE_PULL_ID}/${AGILE_REVISION}/build.tar.gz --no-check-certificate
          tar --use-compress-program="pigz -1" -xpf build.tar.gz
          cd ./paddle
          api_doc_spec_diff=$(python tools/diff_api.py  paddle/fluid/API_DEV.spec.doc paddle/fluid/API_PR.spec.doc)
          if [ "$api_doc_spec_diff" == "" ]; then
            echo "API documents no change."
            mkdir -p /home/data/cfs/api_doc/${AGILE_PULL_ID}/${AGILE_REVISION}
            cd  /home/data/cfs/api_doc/${AGILE_PULL_ID}/${AGILE_REVISION}
            touch api_doc_break.flag
          fi
          '

  build-doc:
    name: Build doc
    runs-on:
      group: BD_BJ-V100
    steps:
      - name: Check docker image  and run container
        env:
          AGILE_PULL_ID: ${{ github.event.pull_request.number }}
          AGILE_REVISION: ${{ github.event.pull_request.head.sha }}
          BUILD_DOC: "true"
          UPLOAD_DOC: "true"
          BOSBUCKET: "paddle-site-web-dev"
          PREVIEW_SITE: "paddle-docs-preview.paddlepaddle.org.cn"
        run: |
          container_name=${TASK}-$(date +%Y%m%d-%H%M%S)
          echo "container_name=${container_name}" >> ${{ github.env }}
          docker_image=${{ inputs.docker_doc_image }}
          docker run -d -t --name ${container_name} \
            -v "/home/data/cfs:/home/data/cfs" \
            -v "/home/data/cfs/.cache/python35-cpu:/root/.cache" \
            -v "/home/data/cfs/.ccache:/root/.ccache" \
            -v "/dev/shm:/dev/shm"  \
            -v ${{ github.workspace }}/../../..:${{ github.workspace }}/../../.. \
            -v ${{ github.workspace }}:/paddle \
            -e AGILE_PULL_ID \
            -e AGILE_REVISION
            -e BUILD_DOC \
            -e UPLOAD_DOC \
            -e BOSBUCKET \
            -e PREVIEW_SITE \
            -e no_proxy \
            -w /paddle --network host ${docker_image}

      - name: Check doc build
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -c '
          rm -rf  * .[^.]*
          if [ -f "/home/data/cfs/api_doc/${AGILE_PULL_ID}/${AGILE_REVISION}/api_doc_break.flag"  ];then
            echo "API documents no change, skip doc build."
            exit 0
          fi
          curl -sS -o /tmp/entrypoint.sh https://paddle-dev-tools-open.bj.bcebos.com/fluiddoc-preview/entrypoint-paddle-docs-review.sh
          cd /
          bash "/tmp/entrypoint.sh"
          '
