name: PR-CI-SOT

on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  check-docker:
    name: Check Docker Image
    runs-on:
      group: Docker-build

    run: |
      bash ./tools/dockerfile/ci_dockerfile.sh
      DOCKER_IMAGE=md5sum ${docker-image-file}
