name: Linux-build

on:
  workflow_call:
    inputs:
      docker_build_image:
        type: string
        required: true
      is_pr:
        type: string
        required: false
        default: 'true'
    outputs:
      can-skip:
        description: "Whether to skip the job"
        value: ${{ jobs.build.outputs.can-skip }}

env:
  PR_ID: ${{ github.event.pull_request.number || '0' }}
  COMMIT_ID: ${{ github.event.pull_request.head.sha || github.sha }}
  work_dir: /paddle
  PADDLE_ROOT: /paddle
  TASK: paddle-CI-${{ github.event.pull_request.number }}-build
  ci_scripts: /paddle/ci
  BRANCH: ${{ github.event.pull_request.base.ref || github.ref_name }}
  CI_name: build
  CFS_DIR: /home/data/cfs
  is_pr: ${{ inputs.is_pr }}
  no_proxy: "bcebos.com,apiin.im.baidu.com,gitee.com,aliyun.com,.baidu.com,.tuna.tsinghua.edu.cn"

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    outputs:
      can-skip: ${{ steps.check-bypass.outputs.can-skip }}
    runs-on:
      group: GZ_BD-CPU

    steps:
      - name: Check docker image and run container
        run: echo "skip ci"
