name: PR-CI-NPU-910B-Paddle

on:
  workflow_call:

env:
  dockerfile: dockerfile
  docker_image: 885123926a90
  PR_ID: ${{ github.event.pull_request.number }}
  COMMIT_ID: ${{ github.event.pull_request.head.sha }}
  ci_scripts: /paddle/ci
  ci_scripts_runner: ${{ github.workspace }}/ci
  work_dir: /paddle
  PADDLE_ROOT: /paddle
  BRANCH: ${{ github.event.pull_request.base.ref }}
  CI_name: npu

jobs:
  test:
    name: Test
    runs-on:
      group: NPU

    steps:
      - name: Download paddle.tar.gz and update test branch
        run: |
          rm -rf  * .[^.]*
          set -e
          echo "Downloading Paddle.tar.gz"
          wget -q --no-proxy https://paddle-github-action.bj.bcebos.com/PR/Paddle/${PR_ID}/${COMMIT_ID}/Paddle.tar.gz --no-check-certificate
          echo "Extracting Paddle.tar.gz"
          tar xf Paddle.tar.gz
          rm Paddle.tar.gz
          git remote add upstream https://github.com/PaddlePaddle/Paddle.git
          git config pull.rebase false
          git checkout test
          echo "Pull upstream develop"
          source ${{ github.workspace }}/../../../proxy
          git pull upstream develop --no-edit

      - name:  Determine the runner
        run: |
          runner_name=`(echo $PWD|awk -F '/' '{print $3}')`
          echo $runner_name
          source ${{ github.workspace }}/Paddle/utils.sh
          determine_npu_runner ${runner_name}
          echo ${ASCEND_RT_VISIBLE_DEVICES}
          echo no_proxy="localhost,127.0.0.1,localaddress,.bj.bcebos.com,.localdomain.com,.cdn.bcebos.com,.baidu.com,.bcebos.com" >> ${{ github.env }}

      - name: Download PaddleCustomDevice repository
        run: |
          git clone --depth=1000 -b ${BRANCH} https://github.com/PaddlePaddle/PaddleCustomDevice.git
          cd PaddleCustomDevice
          cp -r ../Paddle .
