name: Windows-GPU

on:
  workflow_call:

permissions: read-all

env:
  PR_ID: ${{ github.event.pull_request.number }}
  COMMIT_ID: ${{ github.event.pull_request.head.sha }}
  BRANCH: ${{ github.base_ref }}
  ci_scripts: ${{ github.workspace }}\ci\windows
  WORK_DIR: ${{ github.workspace }}\..
  cache_dir: ${{ github.workspace }}\..\cache
  no_proxy: "bcebos.com,apiin.im.baidu.com,gitee.com,aliyun.com,.baidu.com,.tuna.tsinghua.edu.cn"

defaults:
  run:
    shell: cmd

jobs:
  build:
    name: Build
    runs-on:
      group: win-gpu
    steps:
      - name: Configure environment
        run: |
          cd %WORK_DIR%
          rmdir /s/q %WORK_DIR%\Paddle 2>NUL
          echo "path=%path%;C:\Program Files\NVIDIA Corporation\NVSMI" >> %GITHUB_ENV%
          python -m pip install wget
          python -c "import wget;wget.download('https://paddle-github-action.bj.bcebos.com/PR/windows/%PR_ID%/%COMMIT_ID%/Paddle.tar.gz')"
          tar xf Paddle.tar.gz
          del Paddle.tar.gz
          cd Paddle
          call %ci_scripts%\config_env.bat

      - name: Download paddle
        run: |
          echo %path%
