name: ipu_build_use_ipumodel_sdk_2.5.0

on:
  pull_request:

jobs:
  build_py_wheel:
    runs-on: sdk_2.5.0

    steps:
      - name: clean space
        run: |
          docker run \
            -v $PWD:/checkout \
            --rm \
            paddle_ipu_ci:2.5.0 \
            bash -c "cd /checkout && pwd && ls -a /checkout && rm -rf ..?* .[!.]* *"

      - uses: actions/checkout@v2

      - name: build
        run: |
          docker run --ulimit memlock=-1:-1 --net=host --cap-add=IPC_LOCK \
            --device=/dev/infiniband/ --ipc=host \
            -v /tmp:/host_tmp \
            -v $PWD:/checkout \
            -v paddle_sdk:/sdk \
            -v paddle_ccahe:/paddle_ccahe \
            -e CCACHE_DIR=/paddle_ccahe \
            -e CCACHE_MAXSIZE=20G \
            -v paddle_ipuof:/ipuof \
            -e GITHUB_SHA=${GITHUB_SHA} \
            -v paddle_wheels:/paddle_wheels \
            -e IPUOF_CONFIG_PATH=/ipuof/ipu.conf \
            -e POPLAR_IPUMODEL=1 \
            --workdir /checkout \
            --rm \
            paddle_ipu_ci:2.5.0 \
            bash /checkout/paddle/scripts/ipu/github_action/action_build_and_test.sh
