name: CI

on:
  pull_request:
    types: [opened, synchronize]

permissions: read-all

concurrency:
  group: ${{ github.event.pull_request.number }}
  cancel-in-progress: true

env:
  PR_ID: ${{ github.event.pull_request.number }}
  COMMIT_ID: ${{ github.event.pull_request.head.sha }}

jobs:
  clone:
    name: Clone-linux
    uses: ./.github/workflows/_Clone-linux.yml

  check-bypass:
    name: Check bypass for all
    needs: clone
    uses: ./.github/workflows/check-bypass.yml
    with:
      workflow-name: 'all'
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  sot:
    name: PR-CI-SOT
    if: ${{ needs.check-bypass.outputs.bypass != 'true' }}
    uses: ./.github/workflows/_SOT.yml
    needs: check-bypass

  xpu:
    name: Linux-XPU
    if: ${{ needs.check-bypass.outputs.bypass != 'true' }}
    uses: ./.github/workflows/_Linux-XPU.yml
    needs: check-bypass

  inference:
    name: PR-CI-Inference
    if: ${{ needs.check-bypass.outputs.bypass != 'true' }}
    uses: ./.github/workflows/_Inference.yml
    needs: check-bypass

  coverage:
    name: PR-CI-Coverage
    if: ${{ needs.check-bypass.outputs.bypass != 'true' }}
    uses: ./.github/workflows/_Coverage.yml
    needs: check-bypass

  cpu:
    name: Linux-CPU
    if: ${{ needs.check-bypass.outputs.bypass != 'true' }}
    uses: ./.github/workflows/_CPU.yml
    needs: check-bypass

  npu:
    name: Linux-NPU
    uses: ./.github/workflows/_NPU.yml
    needs: cpu
