name: Coverage

on:
  pull_request:
    types: [opened, synchronize]
    branches: [develop, release/**]

permissions: read-all

concurrency:
  group: ${{ github.event.pull_request.number }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  PR_ID: ${{ github.event.pull_request.number }}
  COMMIT_ID: ${{ github.event.pull_request.head.sha }}
  TASK: paddle-CI-${{ github.event.pull_request.number }}-coverage
  ci_scripts: /paddle/ci
  BRANCH: ${{ github.base_ref }}
  work_dir: /paddle
  PADDLE_ROOT: /paddle
  GIT_PR_ID: ${{ github.event.pull_request.number }}
  CI_name: coverage
  CFS_DIR: /home/data/cfs
  no_proxy: "bcebos.com,apiin.im.baidu.com,gitee.com,aliyun.com,.baidu.com,.tuna.tsinghua.edu.cn"

defaults:
  run:
    shell: bash

jobs:
  clone:
    name: Coverage clone
    uses: ./.github/workflows/_Clone-linux.yml
    with:
      workflow-name: 'coverage'
      clone_dir: Paddle-coverage

  build-docker:
    name: Coverage build docker
    needs: clone
    uses: ./.github/workflows/docker.yml
    with:
      clone_dir: Paddle-coverage
      task: coverage

  test:
    name: Coverage test
    needs: [build-docker]
    if: needs.build.outputs.can-skip != 'true'
    runs-on:
      group: BD_BJ-V100
    steps:
      - name: Upload coverage report
        uses: codecov/codecov-action@v4
        with:
          directory: build/coverage_files
          verbose: true

      - name: Terminate and delete the container
        if: always()
        run: |
          set +e
          rm Paddle.tar.gz
          docker exec -t ${{ env.container_name }} /bin/bash -c 'rm -rf * .[^.]*'
          docker stop ${{ env.container_name }}
          docker rm ${{ env.container_name }}
