name: Re-run

on:
  issue_comment:
    types: [created]

jobs:
  re-run:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/re-run')  && github.event.comment.user.login == github.event.issue.user.login }}
    runs-on:
      group: APPROVAL
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Job Name from comment
        id: get_job
        run: |
          job_name=$(python .github/actions/rerun-workflow/get_job_name.py "${{ github.event.comment.body }}" ".github/rerun-mapping.json")
          echo "job_name=$job_name" >> $GITHUB_OUTPUT

      - name: Rerun Workflow
        if: ${{ steps.get_job.outputs.job_name != '' }}
        uses: ./.github/actions/rerun-workflow
        with:
          PR_ID: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          JOB_NAME: ${{ steps.get_job.outputs.job_name }}
